### ISSUE TITLE
[Bug Report] Failure of using slider mouse to leave event in Popover

### ISSUE THREAD

**Issue by Mcler520** [element-plus/element-plus#1198] opened 2021-01-05 07:01 UTC
### Element Plus version
1.0.1-beta.20

### OS/Browsers version
Chrome 87.0.4280.88

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/EnMcler/pen/vYXjxzg

### Steps to reproduce
1. Click the icon to display Popover;

2. Slide the mouse and release the mouse;

3. The slider follows the mouse;

### What is Expected?
The mouse leaves the sliding button to stop moving.

### What is actually happening?
The mouse leaves the sliding button to follow the mouse position. Click outside the Popover to cancel;

**Comment by JeremyWuuuuu** [comment] 2021-01-05 07:04
Got it, this is caused by hijacking the events, and already fixed but not published, will do a release today.

**Comment by zazzaz** [comment] 2021-01-05 09:30
@JeremyWuuuuu  this should have been fixed in 1.0.1-beta.21 ?

**Comment by JeremyWuuuuu** [comment] 2021-01-05 09:34
Nope, will be fixed in beta.22

**Comment by Mcler520** [comment] 2021-01-05 09:37
@JeremyWuuuuu  ok, beta.21 verify no fix

**Closed** 2021-01-05 09:51 UTC
Labels: bug
