### ISSUE TITLE
el-select Vue warn

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#1012] opened 2020-12-16 02:52 UTC
之前是ok的 升级了版本之后就一堆的警告⚠️   beforeEnter
![image](https://user-images.githubusercontent.com/35122287/102298889-f5fe7f00-3f8c-11eb-9627-dac210280a32.png)

**Comment by zazzaz** [comment] 2020-12-16 04:43
Duplicate of #819 , #965

**Comment by JeremyWuuuuu** [comment] 2020-12-17 08:21
Caused by `Vue`, seems they don't think this is a big problem.
![image](https://user-images.githubusercontent.com/15975785/102461811-e877f080-4083-11eb-80ed-65d1f9c55161.png)

**Closed** 2020-12-17 08:22 UTC
