### ISSUE TITLE
The global zIndex still does  not take effect if it is imported on demand  with  use setConfig

### ISSUE THREAD

**Issue by kiki575** [element-plus/element-plus#1778] opened 2021-04-07 13:55 UTC
The global zIndex still does  not take effect if it is imported on demand  with  use setConfig

import { setConfig } from 'element-plus/lib/utils/config.js'

const install = (app): void => {

app.config.globalProperties.$ELEMENT =  { size: 'small', zIndex: 5000 }

setConfig( { size: 'small', zIndex: 5000 })

components.forEach(component => {
app.component(component.name, component)
})
plugins.forEach(plugin => {
app.use(plugin)
})
}

let ExportData =  { install }

const app = createApp( Entry )

app.use(ExportData)

**Comment by kiki575** [comment] 2021-04-07 13:57
Could someone please give the correct way  on demand ?

**Comment by kiki575** [comment] 2021-04-07 14:00
I tried various methods and it still didn't work，this problem is very unfavorable for the development of SDK components

**Comment by JeremyWuuuuu** [comment] 2021-04-08 03:44
This is simply a reference issue, you do something like this: 
```ts
const options = { size: 'small', zIndex: 5000 }
app.config.globalProperties.$ELEMENT = options
setConfig(options)
```

This will make it work. 
Or you can do something like this:

```ts
import { getConfig, setConfig } from 'config'
// this will also make it work, because you need the config that points to the same object.
setConfig({ size: 'small', zIndex: 5000 })
app.config.globalProperties = getConfig()
```

**Comment by JeremyWuuuuu** [comment] 2021-04-08 03:44
You don't want to change the object itself instead of its value.

**Comment by JeremyWuuuuu** [comment] 2021-04-08 03:45
Let me know if you still have this issue.

**Comment by kiki575** [comment] 2021-04-08 08:23
i still have this issue，**the setConfig**  ， **getConfig**  didn't work  ， the  setConfig way form element-plus/es/utils/config.js   or  element-plus/lib/utils/config.js  ，  Neither of these take effect

```
import { setConfig, getConfig } from 'element-plus/es/utils/config.js'

import {
ElDialog,
  ElMessage,

} from 'element-plus'

const components = [
ElDialog,
 ElMessage,
]

const install = (app): void => {
  const option = { size: 'small', zIndex: 9000}
  app.config.globalProperties.$ELEMENT = option
  setConfig(option)

  components.forEach(component => {
    app.component(component.name, component)
  })
}

let ExportData = { install }

const app = createApp( Entry )

app.use(ExportData)

```

We checked the source code, in the es or lib package, the  getConfig  never not called

```
let $ELEMENT = {};
const setConfig = (option) => {
    console.log('set',option)  // output {size:'small', zIndex: 9000}
    $ELEMENT = option;
};
const getConfig = (key) => {
    console.log('get')
    // This method is never not called when the el-dialog is opened
    return $ELEMENT[key];
};

export { getConfig, setConfig };
```

**Comment by JeremyWuuuuu** [comment] 2021-04-08 09:57
I'd like to ask you what component you were using?
Since `getConfig` only gets called by `PopupManager` when you use `el-tooltip` and others.

I did this locally, seems everything is fine.
![image](https://user-images.githubusercontent.com/15975785/114007110-9d345880-9893-11eb-8d8b-1d7d5a054421.png)
![image](https://user-images.githubusercontent.com/15975785/114007172-afae9200-9893-11eb-966e-ecc5c317d667.png)
I also logged the `getConfig` 
![image](https://user-images.githubusercontent.com/15975785/114007254-c228cb80-9893-11eb-8a25-4e30300e80c1.png)

**Comment by JeremyWuuuuu** [comment] 2021-04-08 10:08
But I could do that on the online IDEs, so I guess that was a problem, I will fix that.

**Comment by JeremyWuuuuu** [comment] 2021-04-08 10:08
Sorry for kept you waiting.

**Comment by JeremyWuuuuu** [comment] 2021-04-08 10:18
I think I have located the bug, here are some bug info:
![image](https://user-images.githubusercontent.com/15975785/114010162-66ac0d00-9896-11eb-8618-5f6b8658d5ad.png)

See the screenshot above, `PopupManager independently bundled a copy of `getConfig` instead of using the code in other file, which made it independent.

**Comment by JeremyWuuuuu** [comment] 2021-04-08 10:41
I've found a way to fix this, the fix will be delivered tonight. Sorry for the inconvenience.

**Comment by kiki575** [comment] 2021-04-08 10:44
thanks

**Comment by kiki575** [comment] 2021-04-08 10:46
> I'd like to ask you what component you were using?
like :
ElDialog,
ElMessage,

**Comment by JeremyWuuuuu** [comment] 2021-04-08 14:22
So this issue was caused by building the utils independently, when we build it, the tree-shaking thing just inlined all the methods and variables which caused our files lost their connections then caused the issue you have encountered.
I have made a PR to fix it #1788 , after it gets merged I will trigger a release you can bump the version to get the newest code. Then if you have any further issue please do reach out to me.

**Closed** 2021-04-09 02:00 UTC
Labels: bug

**Comment by JeremyWuuuuu** [comment] 2021-04-09 02:13
New release process has been dispatched, check this out: https://github.com/element-plus/element-plus/actions/runs/731584095

**Comment by JeremyWuuuuu** [comment] 2021-04-09 02:14
After you installed the new version if you still suffers from it, please reach out to us, we will help you until you no longer suffers from it.

**Comment by kiki575** [comment] 2021-04-09 05:08
I still encounter **a new construction problem** when using **the latest version**
 
ERROR  Failed to compile with 1 error                                  

 error  in ./node_modules/element-plus/lib/utils/validators.js

Module not found: Error: Can't resolve '@element-plus/utils/util' in ['/Users/hello/node_modules/element-plus/lib/utils']([url](url))

**Comment by JeremyWuuuuu** [comment] 2021-04-09 05:18
> I still encounter **a new construction problem** when using **the latest version**
> 
> ERROR Failed to compile with 1 error
> 
> error in ./node_modules/element-plus/lib/utils/validators.js
> 
> Module not found: Error: Can't resolve '@element-plus/utils/util' in ['/Users/hello/node_modules/element-plus/lib/utils'](%5Burl%5D(url))

I am so sorry that I missed this file while fixing the previous one. Will dispatch a hotfix soon 🙏🏻 sorry again

**Comment by kiki575** [comment] 2021-04-09 05:19
> After you installed the new version if you still suffers from it, please reach out to us, we will help you until you no longer suffers from it.
 @JeremyWuuuuu 
> `
![image](https://user-images.githubusercontent.com/51407471/114131937-0a98c580-9936-11eb-9d9e-9aad1c8c9d00.png)
`

install the latest version , then encountered this problem

**Comment by 0song** [comment] 2021-04-09 05:28
will fix soon

**Comment by 0song** [comment] 2021-04-09 05:52
> > After you installed the new version if you still suffers from it, please reach out to us, we will help you until you no longer suffers from it.
> > @JeremyWuuuuu
> > `![image](https://user-images.githubusercontent.com/51407471/114131937-0a98c580-9936-11eb-9d9e-9aad1c8c9d00.png)`
> 
> install the latest version , then encountered this problem

fixed in 1.0.2-beta.39

**Comment by JeremyWuuuuu** [comment] 2021-04-09 06:32
Please try it again, I am sincerely sorry that I caused this issue.

**Comment by kiki575** [comment] 2021-04-09 08:27
This problem has been solved perfectly, thank you very much

thank you for your selfless dedication
