### ISSUE TITLE
el-date-picker 选择以后value值改变了但是视图不显示

### ISSUE THREAD

**Issue by 1948037137** [element-plus/element-plus#678] opened 2020-11-24 08:32 UTC
![image](https://user-images.githubusercontent.com/46392442/100068559-ac7db100-2e72-11eb-9c34-67dce194dc59.png)

**Comment by JeremyWuuuuu** [comment] 2020-11-24 08:45
See #609 
Also See #603

**Comment by JeremyWuuuuu** [comment] 2020-11-24 08:46
Closing due to duplication

**Comment by JeremyWuuuuu** [comment] 2020-11-24 08:46
This is a bug caused by `Vue`, the simplest way to solve this is to lock your `Vue` version to `3.0.0` instead of using `^` to get the most compatible version.

**Closed by JeremyWuuuuu** 2020-11-24 08:46 UTC
Labels: duplicate
