### ISSUE TITLE
[Component] [select] 在Firefox浏览器中el-select选择框刚显示的时候，会被el-table遮挡

### ISSUE THREAD

**Issue by Marco-ding** [element-plus/element-plus#19407] opened 2024-12-26 02:20 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.9.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[CodePen](
https://github.com/user-attachments/assets/a4127398-82d7-40a6-907d-1740cd0174d8
)

### Steps to reproduce

1. 点击打开select选择框
2. 会发现select选择框刚出现的时候会被el-table遮挡

### What is Expected?

select不被el-table遮挡

### What is actually happening?

2

### Additional comments

_(empty)_

**Comment by btea** [comment] 2024-12-26 05:39
Duplicate of #13481

**Closed** 2024-12-26 05:39 UTC
