### ISSUE TITLE
[bugs] I found a md-loader bug in docs

### ISSUE THREAD

**Issue by rottenpen** [element-plus/element-plus#529] opened 2020-11-02 07:09 UTC
The code  `import xxx from 'vue'`  is not allow in docs. So Composition can't be import in docs. #512 
There are 2 ways to fix it.
1. Compostion Api should be code like 
```javascript
export default Vue.defineComponent({
  setup() {
    const state = Vue.ref("");
    return {
       state
    }
  }
})
```
but I think it is no a good idea

2. Import all composition Api in `website/md-loader/index.js`

which is better？And I will PR to fix it.

**Comment by JeremyWuuuuu** [comment] 2020-11-02 07:22
Sorry, I don't quite get it.
It seems just fine on my machine.
Closing this due to it's not reproducible.
![image](https://user-images.githubusercontent.com/15975785/97840574-3b3d5900-1d1f-11eb-957e-145c6c87f242.png)

**Closed by JeremyWuuuuu** 2020-11-02 07:22 UTC

**Comment by rottenpen** [comment] 2020-11-02 07:24
run `yarn website-dev` is all right?

**Comment by JeremyWuuuuu** [comment] 2020-11-02 07:27
Yes, it is alright. The bug you mentioned did not exist, please double checking your code.
One thing, you do need to remove `data` option when you use `setup`, in this case I get exact error like you did.

**Comment by rottenpen** [comment] 2020-11-02 07:37
oh... I get that `"vue"` "" is not allow, must be `'vue'`. It's ok now.
