### ISSUE TITLE
[Bug Report] import { ElMessage } from "element-plus";   TS type prompt error

### ISSUE THREAD

**Issue by an501920078** [element-plus/element-plus#3640] opened 2021-09-26 00:47 UTC
### Element Plus version
1.1.0-beta.16

### OS/Browsers version
win10

### Vue version
3.2.19

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
安装elementui 1.1.0-beta.16   在ts文件中使用使用 
import { ElMessage } from "element-plus";

使用ElMessage 后
提示

此表达式不可调用。
  "SFCWithInstall<Required<MessagePartial>>" 类型的部分要素不可调用。
    类型 "Required<MessagePartial> & { install: PluginInstallFunction; }" 没有调用签名。ts(2349)

### What is Expected?
无错误

### What is actually happening?
ts类型错误

**Comment by feenn** [comment] 2021-09-26 02:01
Have the same issue. ElMessage\ElNotification etc can be used by locally imported according to https://element-plus.gitee.io/en-US/component/notification.html#local-import. I think some refactors in 1.1.0-beta.13 is the root cause, beacause this error doesn't occurred when compiling with 1.1.0-beta.12 and below in TS mode. Someone else also has the same issue (maybe ref #3627).

**Comment by sxzz** [comment] 2021-09-26 02:42
Fixed in #3636

**Closed by sxzz** 2021-09-26 02:42 UTC
