### ISSUE TITLE
The [bug report] paging component does not display the total number of pages

### ISSUE THREAD

**Issue by mcck** [element-plus/element-plus#4652] opened 2021-12-03 04:03 UTC
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Chrome  95.0.4638.54

### Vue version
3.2.23

### Reproduction Link
https://elementui.github.io/

### Steps to reproduce
https://element-plus.gitee.io/zh-CN/component/pagination.html
总页数显示
共 {total} 条

### What is Expected?
共 100 条

### What is actually happening?
共 {total} 条

**Comment by emojiiii** [comment] 2021-12-03 04:18
Duplicate of #4617. Fix in #4619

**Closed** 2021-12-03 15:23 UTC
