### ISSUE TITLE
[Bug Report] pagination total

### ISSUE THREAD

**Issue by 18378559745** [element-plus/element-plus#4737] opened 2021-12-09 07:10 UTC
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
windows 10

### Vue version
3.2.24

### Reproduction Link
https://github.com/element-plus/element-plus.git

### Steps to reproduce
<el-pagination
  :page-sizes="[10, 20, 30, 40,50]"
  :current-page="page"
  :page-size="page_size"
  :total="100"
  layout=" total, sizes, prev, pager, next, jumper"
  @size-change="handleSizeChange"
  @current-change="handleCurrentChange"
>
</el-pagination>

### What is Expected?
Total 100

### What is actually happening?
Total {total}

**Comment by emojiiii** [comment] 2021-12-09 07:39
Duplicate of #4617. Fix in #4619

**Closed** 2021-12-09 11:17 UTC
