### ISSUE TITLE
[Bug Report] props.date.locale(...).localeData is not a function

### ISSUE THREAD

**Issue by OneSeven** [element-plus/element-plus#3635] opened 2021-09-25 13:03 UTC
### Element Plus version
1.1.0-beta.16

### OS/Browsers version
chrome 94

### Vue version
3.2.18

### Reproduction Link
https://jsfiddle.net/rqgcvb8h/

### Steps to reproduce
```
<el-date-picker
        v-model="time"
        type="datetime">
</el-date-picker>

data() {
        return {
            time: "Wed, 29 Sep 2021 16:00:00 GMT"
        }
    }
```

### What is Expected?
normal display

### What is actually happening?
```
[Vue warn]: Unhandled error during execution of setup function 

index.js:107 Uncaught (in promise) TypeError: props.date.locale(...).localeData is not a function
```

Report an error when modelValue has a default value
No error was reported in CDN mode,
There is an error in compile mode

**Comment by adarshmadrecha** [comment] 2021-09-25 17:39
Most probably duplicate of https://github.com/element-plus/element-plus/issues/3634

**Comment by wraptor** [comment] 2021-09-27 02:27
> Most probably duplicate of #3634

When will the new version be released，it make system can not be work

**Comment by adarshmadrecha** [comment] 2021-09-28 12:57
> When will the new version be released，it make system can not be work
v1.1.0 beta 17 fixes this issue.

**Closed** 2021-09-28 13:11 UTC
