### ISSUE TITLE
[Bug Report] ElNotification样式错乱

### ISSUE THREAD

**Issue by tfn290181662** [element-plus/element-plus#5968] opened 2022-02-11 09:06 UTC
### Element Plus version
2.0.1

### OS/Browsers version
latest

### Vue version
3.2.30

### Reproduction Link
https://github.com/tfn290181662/element-plus-test

### Steps to reproduce
运行项目，手动路由到http://localhost:3000/#/about，即可复现

### What is Expected?
ElNotification正常显示

### What is actually happening?
ElNotification样式错乱

**Comment by tfn290181662** [comment] 2022-02-11 09:08
![image](https://user-images.githubusercontent.com/92365265/153564397-57db30b2-0fe1-4e91-9b95-4058c05a3305.png)

**Comment by tfn290181662** [comment] 2022-02-11 09:09
![image](https://user-images.githubusercontent.com/92365265/153564537-d3bd5b53-dc90-4a92-a437-1b31ed615c03.png)

**Comment by orzalter** [comment] 2022-02-11 09:12
手动import css后 我跟你一样~ 不import css 会在页面下显示...

**Comment by emojiiii** [comment] 2022-02-11 12:27
Duplicate of #5667

**Closed** 2022-02-11 12:27 UTC
Labels: bug, duplicate, style related, CI
