### ISSUE TITLE
[Component] [message-box] MOBILE ONLY | Alertbox, promptbox and confirmbox layout

### ISSUE THREAD

**Issue by LoryPelli** [element-plus/element-plus#11919] opened 2023-03-08 16:42 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `Chrome 111`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Link](https://texteditoronline.pages.dev)

### Steps to reproduce

Click the ... button or the save button

### What is Expected?

Have a promptbox centered in the page

### What is actually happening?

The promptbox is at the top of the page and you can scroll down but this makes no sense

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/87276663/223774663-514e32c8-d5ee-408a-a595-3135170446e9.png)

**Comment by LoryPelli** [comment] 2023-03-08 16:42
My old issue about this was inactive

**Comment by jw-foss** [comment] 2023-03-09 01:28
Sure, I will investigate this myself and see if what I can do. Would you mind give me some extra information for debugging? For instance, what resolution you are using when this occurs.

**Comment by jw-foss** [comment] 2023-03-09 01:37
Confirmed that this is related with the recent change I made in #11881, I'll fix that right away! Sorry about that :cry:, you'll receive a patch on 10 Mar GMT+8.

**Comment by LoryPelli** [comment] 2023-03-09 06:06
> Confirmed that this is related with the recent change I made in #11881, I'll fix that right away! Sorry about that 😢, you'll receive a patch on 10 Mar GMT+8.

As you can see the popup is also at the top of the page, should it be centered?

**Comment by jw-foss** [comment] 2023-03-09 06:12
@LoryPelli yes it should, the root cause of this issue is that while I was fixing the namespacing issue, I mistakenly passed a namespace with `[namespace]-message-box` down to the `lockScreen` hook, which caused the class attached on the body to become `[namespace]-message-box-parent--hidden` and it should be `[namespace]-popup-parent--hidden`

**Comment by jw-foss** [comment] 2023-03-09 06:12
My PR in #11921 should fix this.

**Comment by LoryPelli** [comment] 2023-03-09 06:19
> My PR in #11921 should fix this.

But this is happening since I started using the library a month ago if I'm not wrong

**Comment by jw-foss** [comment] 2023-03-09 06:22
> > My PR in #11921 should fix this.
> 
> But this is happening since I started using the library a month ago if I'm not wrong

Well, if that is the case, would you mind giving me a minimal reproducible demo code for me to investigate that one? As simple as possible

**Comment by LoryPelli** [comment] 2023-03-09 14:00
> > > My PR in #11921 should fix this.
> > 
> > 
> > But this is happening since I started using the library a month ago if I'm not wrong
> 
> Well, if that is the case, would you mind giving me a minimal reproducible demo code for me to investigate that one? As simple as possible

Is it a problem for you to use my website https://texteditoronline.pages.dev ? it's also open source on github https://github.com/lorypelli/text-editor-online

**Comment by jw-foss** [comment] 2023-03-10 07:04
@LoryPelli Np, I'll look into this and fix it ASAP

**Comment by jw-foss** [comment] 2023-03-10 07:08
@LoryPelli I cannot reproduce the `mis-position` issue on my machine, only have the unlocked content. We will release a new version today to fix the unlock content issue, I'll verify the issue on my machine after the release is done.

**Comment by jw-foss** [comment] 2023-03-10 07:08
Reopening this issue, I'll follow this up myself.

**Comment by LoryPelli** [comment] 2023-03-10 14:42
@jw-foss any updates?

**Comment by jw-foss** [comment] 2023-03-11 12:47
@LoryPelli sorry for getting back late, we were not able to publish a new release, I promise I will do that as long as the release is out.

**Comment by LoryPelli** [comment] 2023-03-11 13:05
> @LoryPelli sorry for getting back late, we were not able to publish a new release, I promise I will do that as long as the release is out.

ETA?

**Comment by LoryPelli** [comment] 2023-03-13 07:05
@jw-foss with the new release, it didn't get fixed

**Comment by jw-foss** [comment] 2023-03-13 14:27
@LoryPelli looking 👀

**Comment by jw-foss** [comment] 2023-03-13 14:39
@LoryPelli I think I have an idea about what was happening to you, I compared your app with our own doc app and I found that the attributes for both version were identical and the only difference is that, the `box-type` was different, with `box-sizing: border-box` the message content is correctly centered.

<img width="660" alt="CleanShot 2023-03-13 at 22 36 30@2x" src="https://user-images.githubusercontent.com/15975785/224733609-9c6c1f50-111e-4a44-b080-ff2ca7a88116.png">

<img width="660" alt="CleanShot 2023-03-13 at 22 37 32@2x" src="https://user-images.githubusercontent.com/15975785/224733908-a4633a49-1cc2-4e5d-a02e-45795dc8cded.png">

It looks like you can make a quick fix to your code with 

```css
// global.css
// since you didn't change any namespace.
.el-message-box {
  box-sizing: border-box;
}

```

**Comment by jw-foss** [comment] 2023-03-13 14:48
The reason behind this is that when the property was not set the default value for `box-sizing` would be `content-box` and when that happens the `1px` horizontal borders add up to `2px` which makes the box to overflow the parent wrapper in this case our `overlay`. And because of the overflow it made the positioning go wrong, I have no idea why though TBH, I think we should explicitly mark that `box-sizing: border-box` for `message-box` component, for a quick fix, the comment I just left should do the trick.

**Comment by LoryPelli** [comment] 2023-03-13 15:38
Ok, but you should fix this in the library component, so I won't need to do this

**Comment by jw-foss** [comment] 2023-03-13 15:44
@LoryPelli yes indeed, and I will make sure this is included in the next release.

**Comment by LoryPelli** [comment] 2023-03-13 16:04
> @LoryPelli yes indeed, and I will make sure this is included in the next release.

Can you please link the pull request to this issue so I can see that it has actually been made?

**Comment by LoryPelli** [comment] 2023-03-14 06:09
@jw-foss any update?

**Comment by jw-foss** [comment] 2023-03-14 06:12
@LoryPelli we have a regular release on every Fri, the fix will be included in this Fri.(17th Ma), last week I made mistakes while refactoring the code which caused the irregular releases.

**Comment by LoryPelli** [comment] 2023-03-15 10:09
> @LoryPelli we have a regular release on every Fri, the fix will be included in this Fri.(17th Ma), last week I made mistakes while refactoring the code which caused the irregular releases.

@jw-foss what about the pull request?

**Closed** 2023-03-16 23:31 UTC
Labels: Quality::Regression, Component::Dialog

**Comment by LoryPelli** [comment] 2023-03-17 14:37
@jw-foss when will the release be out?
