### ISSUE TITLE
[Component] [select, option] Select 选择器添加搜索功能后，prefix组件头部内容点击事件被遮挡失效，展开箭头失效

### ISSUE THREAD

**Issue by ggooogg** [element-plus/element-plus#13507] opened 2023-07-07 08:52 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.2`
- Element Plus Version: `2.2.12`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-option`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tIFwidnVlXCI7XG5cbiAgY29uc3QgdmFsdWUxID0gcmVmKFtdKTtcbiAgY29uc3QgdmFsdWUyID0gcmVmKFtdKTtcbiAgY29uc3QgdmFsdWUzID0gcmVmKFtdKTtcbiAgY29uc3QgdmFsdWU0ID0gcmVmKFtdKTtcbiAgY29uc3Qgb3B0aW9ucyA9IFtcbiAgICB7XG4gICAgICB2YWx1ZTogXCJPcHRpb24xXCIsXG4gICAgICBsYWJlbDogXCJPcHRpb24xXCIsXG4gICAgfSxcbiAgICB7XG4gICAgICB2YWx1ZTogXCJPcHRpb24yXCIsXG4gICAgICBsYWJlbDogXCJPcHRpb24yXCIsXG4gICAgfSxcbiAgICB7XG4gICAgICB2YWx1ZTogXCJPcHRpb24zXCIsXG4gICAgICBsYWJlbDogXCJPcHRpb24zXCIsXG4gICAgfSxcbiAgICB7XG4gICAgICB2YWx1ZTogXCJPcHRpb240XCIsXG4gICAgICBsYWJlbDogXCJPcHRpb240XCIsXG4gICAgfSxcbiAgICB7XG4gICAgICB2YWx1ZTogXCJPcHRpb241XCIsXG4gICAgICBsYWJlbDogXCJPcHRpb241XCIsXG4gICAgfSxcbiAgXTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZTJcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIGNvbGxhcHNlLXRhZ3NcbiAgICAgIGZpbHRlcmFibGVcbiAgICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICA+XG4gICAgICA8dGVtcGxhdGUgI3ByZWZpeD5cbiAgICAgICAgPGVsLXRhZ1xuICAgICAgICAgIEBjbGljaz1cIlxuICAgICAgICAgICAgKCkgPT4ge1xuICAgICAgICAgICAgICBjb25zb2xlLmxvZyg2NjYpO1xuICAgICAgICAgICAgfVxuICAgICAgICAgIFwiXG4gICAgICAgICAgPuWFqOmAiTwvZWwtdGFnXG4gICAgICAgID5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICAvPlxuICAgIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref } from "vue";

  const value1 = ref([]);
  const value2 = ref([]);
  const value3 = ref([]);
  const value4 = ref([]);
  const options = [
    {
      value: "Option1",
      label: "Option1",
    },
    {
      value: "Option2",
      label: "Option2",
    },
    {
      value: "Option3",
      label: "Option3",
    },
    {
      value: "Option4",
      label: "Option4",
    },
    {
      value: "Option5",
      label: "Option5",
    },
  ];
</script>

<template>
  <el-select
      v-model="value2"
      multiple
      collapse-tags
      filterable
      placeholder="Select"
      style="width: 240px"
    >
      <template #prefix>
        <el-tag
          @click="
            () => {
              console.log(666);
            }
          "
          >全选</el-tag
        >
      </template>
      <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value"
      />
    </el-select>
</template>
```

点击展开按钮与全选按钮均失效。

### What is Expected?

开启搜索功能后不影响其他功能的点击事件。

### What is actually happening?

开启搜索后需要点击插槽中新增的tag组件。

### Additional comments

_(empty)_

**Comment by init-qy** [comment] 2023-07-07 09:29
seems #11524 cause this issue, v2.3.5 works
Duplicate of #13487

**Closed** 2023-07-08 01:58 UTC
Labels: duplicate
