### ISSUE TITLE
[Component] [All] Cascader 级联选择器输入显示

### ISSUE THREAD

**Issue by 51511zz** [element-plus/element-plus#11025] opened 2022-12-19 10:11 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/cascader.html#%E5%8F%AF%E6%90%9C%E7%B4%A2)

### Steps to reproduce

输入打字字符时，提示语不会消失复现步骤
1、点击输入框
2、输入拼音

### What is Expected?

提示语自动消失

### What is actually happening?

拼音和提示语重叠

### Additional comments

_(empty)_
![image](https://user-images.githubusercontent.com/103979563/208401624-33e202e2-d177-4972-95d8-121f659da392.png)

**Comment by btea** [comment] 2022-12-19 13:47
Duplicate of #11024

**Closed by btea** 2022-12-19 13:47 UTC
