### ISSUE TITLE
[Feature Request] 希望Select可以支持对大数据量树形结构数据进行选择

### ISSUE THREAD

**Issue by li936393** [element-plus/element-plus#5062] opened 2021-12-30 12:55 UTC
### Existing Component
No

### Component Name
TreeSelect

### Description
Select可以支持对大数据量树形结构数据进行选择，类似el-select-v2下拉支持虚拟树（el-tree-v2）

**Comment by emojiiii** [comment] 2021-12-30 14:03
do you mean `el-select-tree-v2` ?

**Comment by li936393** [comment] 2021-12-31 02:30
> 
https://github.com/element-plus/element-plus/issues/5062#issuecomment-1003042261
是的，AntDesign、ArcoDesign都有类似ThreeSelect的实现

**Comment by emojiiii** [comment] 2021-12-31 03:52
We are already planning to do `el-select-tree`, but `el-select-tree-v2`, but `el-select-tree-v2` has no plan yet.

**Comment by li936393** [comment] 2021-12-31 08:56
谢谢，el-select-tree大概计划啥时候支持呢？

**Comment by emojiiii** [comment] 2021-12-31 09:20
I can only say, we are doing, we are doing !!! 😄

**Comment by emojiiii** [comment] 2022-01-04 02:04
please see this [issue](https://github.com/element-plus/element-plus/issues/2037)

**Comment by emojiiii** [comment] 2022-01-04 02:07
Duplicate of #2037

**Closed** 2022-01-04 02:07 UTC
Labels: duplicate, feature request, Component：Select-Tree
