### ISSUE TITLE
搭建开发环境，运行提示VueCompilerError: Element is missing end tag.

### ISSUE THREAD

**Issue by iceycc** [element-plus/element-plus#761] opened 2020-12-02 01:21 UTC
读md文件时出错

**Comment by JeremyWuuuuu** [comment] 2020-12-02 01:24
Could you please add detailed description in the issue? Issue without description of minimal reproducible code will be closed directly, thanks

**Comment by iceycc** [comment] 2020-12-02 01:39
有点小包的问题。。我是想自己开发一下，不知道是我的环境问题还是编辑器问题，把整个项目down下来,编辑器是webstorm，`yarn bootstrap`。然后`yarn website-dev` 后,控制台提示下面类似的报错，md文件都提示这个错误。。。

```
ERROR in ./website/docs/zh-CN/calendar.md
Module Error (from ./node_modules/vue-loader/dist/index.js):

VueCompilerError: Element is missing end tag.
at /Users/bingyang/Documents/Project/element-plus/website/docs/zh-CN/calendar.md:71:5
69 |  <td>range</td>
70 |  <td>时间范围，包括开始时间与结束时间。开始时间必须是周起始日，结束时间必须是周结束日，且时间跨度不能超过两个月。</td>
71 |  <td><Date>Array</td>
   |      ^
72 |  <td>—</td>
73 |  <td>—</td>

```

**Comment by iceycc** [comment] 2020-12-02 01:43
node v12.13.1
电脑 mac 10.15.7

**Comment by JeremyWuuuuu** [comment] 2020-12-02 01:54
Got it I'm going to verify this

**Comment by JeremyWuuuuu** [comment] 2020-12-02 02:24
I ran it on my machine it worked fine 
![image](https://user-images.githubusercontent.com/15975785/100820098-78b11580-3488-11eb-812f-6f34df7f4de4.png)
node v14.10.0
MacOS Big Sur 11.0.1

**Comment by JeremyWuuuuu** [comment] 2020-12-03 13:47
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Closed by JeremyWuuuuu** 2020-12-03 13:47 UTC
