### ISSUE TITLE
[Bug Report] 全局配置失效

### ISSUE THREAD

**Issue by Luotianxu-ltx** [element-plus/element-plus#5125] opened 2022-01-04 06:06 UTC
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Chrome 95.0.4638.54

### Vue version
3.2.26

### Reproduction Link
https://github.com/Luotianxu-ltx/element.git

### Steps to reproduce
import { createApp } from 'vue'
import App from './App.vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'

const app = createApp(App)
app.use(ElementPlus, { size: 'small', zIndex: 3000 })
app.mount('#app')

### What is Expected?
全局设置组件大小

### What is actually happening?
设置大小无效

**Comment by emojiiii** [comment] 2022-01-04 06:09
Duplicate of #5078

**Closed** 2022-01-04 06:10 UTC
Labels: duplicate, New Version
