### ISSUE TITLE
[Bug Report] Cascader `lazyLoad` triggers on every re-render

### ISSUE THREAD

**Issue by wenfangdu** [element-plus/element-plus#2317] opened 2021-06-24 01:41 UTC
### Element Plus version
1.0.2-beta.51

### OS/Browsers version
Windows 10
Chrome v91

### Vue version
3.1.2

### Reproduction Link
https://github.com/wenfangdu/cascader-lazy-load-repro

### Steps to reproduce
Please use the repro link.

### What is Expected?
`props` are checked by content, e.g. using `lodash`'s `isEqual`, if it indeed changed, then run `lazyLoad`.

### What is actually happening?
`lazyLoad` triggers on every re-rerender.

**Comment by JeremyWuuuuu** [comment] 2021-06-24 03:45
I haven’t inspect the source code yet but if this is truely happening, then it should be marked as a bug. Do you have any idea of fixing this? If you do that’d be fantastic.

**Comment by JeremyWuuuuu** [comment] 2021-06-24 03:46
Please take a look on this as well.

**Comment by msidolphin** [comment] 2021-06-24 03:53
same problem #1871

**Comment by msidolphin** [comment] 2021-06-24 03:54
you should:

`
<Comp :config="config" />

setup(){
const config = {a:1}
return{
	...
	config
	}
}
`

**Comment by JeremyWuuuuu** [comment] 2021-06-24 03:57
@msidolphin would you like fixing this?

**Comment by msidolphin** [comment] 2021-06-24 03:59
> @msidolphin would you like fixing this?

That issue mentioned the solution, and I submitted the PR

**Comment by JeremyWuuuuu** [comment] 2021-06-24 04:01
> > @msidolphin would you like fixing this?
> 
> That issue mentioned the solution, and I submitted the PR

Oh I must’ve missed it. Could you send me the link?

**Comment by msidolphin** [comment] 2021-06-24 04:03
> > > @msidolphin would you like fixing this?
> > 
> > 
> > That issue mentioned the solution, and I submitted the PR
> 
> Oh I must’ve missed it. Could you send me the link?

https://github.com/element-plus/element-plus/pull/2298

**Comment by SimonaliaChen** [comment] 2021-06-24 07:20
It is by design but not a bug. There are truly some cases `config` should be reactive, and re-init when it change. So I think the bug is a usage problem. As you know, vue 3.x will run `setup()` on every re-render, so pass `props` a plain object directly  will always be a new reference. To keep `config` immutable, you should wrap `props` with `ref` or `reactive` instead.

**Comment by wenfangdu** [comment] 2021-06-24 07:40
@SimonaliaChen 

> As you know, vue 3.x will run setup() on every re-render ...

I think you meant to say "run render function on every re-render"?

> pass props a plain object directly will always be a new reference.

Therefore, I think `props` is better to be checked by content, e.g. using lodash's `isEqual`, if so, even if the user passes a literal object for `props`, it won't trigger on re-renders.

**Comment by JeremyWuuuuu** [comment] 2021-06-24 07:45
This is just like React rendering strategy when you pass `() => dosomething` to a component, every re-render creates a new function instance and passed down to the component. In your case, you used a object literal inside the render function which gets triggered by every re-render(including the very first one). You can try to cache the object above the function you returned. You will not get the the unexpected result.

**Comment by JeremyWuuuuu** [comment] 2021-06-24 07:50
Same goes to the object literal. In your code
```jsx
mport { defineComponent, ref } from 'vue'

export default defineComponent({
  setup() {
    const cascader = ref([])
    let id = 0

    return () => (
      <ElCascader
        vModel={cascader.value}
        props={{
          lazy: true,
          // 👇 triggers on every re-render, should be checked by content, e.g. using lodash's isEqual
          lazyLoad(node, resolve) {
            const { level } = node
            setTimeout(() => {
              const nodes = Array.from({ length: level + 1 }).map(() => ({
                value: ++id,
                label: `选项${id}`,
                leaf: level >= 2,
              }))
              // 通过调用resolve将子节点数据返回，通知组件数据加载完成
              resolve(nodes)
            }, 1000)
          },
        }}
      />
    )
  },
})
```
If you do this:

```jsx
mport { defineComponent, ref } from 'vue'

export default defineComponent({
  setup() {
    const cascader = ref([])
    const props = {
          lazy: true,
          // 👇 triggers on every re-render, should be checked by content, e.g. using lodash's isEqual
          lazyLoad(node, resolve) {
            const { level } = node
            setTimeout(() => {
              const nodes = Array.from({ length: level + 1 }).map(() => ({
                value: ++id,
                label: `选项${id}`,
                leaf: level >= 2,
              }))
              // 通过调用resolve将子节点数据返回，通知组件数据加载完成
              resolve(nodes)
            }, 1000)
          },
        }
    let id = 0

    return () => (
      <ElCascader
        vModel={cascader.value}
        // this doesn't really have to be a reactive, simply use it as a plain object or you can use `Readonly`
        props={props}
      />
    )
  },
})


```

**Comment by JeremyWuuuuu** [comment] 2021-06-24 07:53
Besides, I didn't see any overhead going on with the code.

**Comment by wenfangdu** [comment] 2021-06-24 08:02
@JeremyWuuuuu The problem I was facing is there are a lot of cascaders in the component, I'm currently doing the following to group them:

```js
const formA = {
  cascader: {
    modelValue: [],
    props: {...},
  },
  ...otherFields,
}

const formB = {
  cascader: {
    modelValue: [],
    props: {...},
  },
  ...otherFields,
}

const formC = {
  cascader: {
    modelValue: [],
    props: {...},
  },
  ...otherFields,
}

...
```

If I could do:

```js
const formA = {
  cascader: [],
  ...otherFields,
}

const formB = {
  cascader: [],
  ...otherFields,
}

const formC = {
  cascader: [],
  ...otherFields,
}

...
```

The form structures would be simpler, anyway, it's just my personal opinion, please feel free to ignore this request if you think it's premature optimization.

**Comment by JeremyWuuuuu** [comment] 2021-06-24 08:06
IMHO, configurations which were not meant to be reactive can be separated from the reactive object, also you can still do the spreading operation on a jsx element since you don't create any new objects just mapping it down to the sub component which will not cause any re-rendering issues

**Comment by JeremyWuuuuu** [comment] 2021-06-24 08:07
As we said, the way you implemented the code creates new object and assigned to the subcomponent which is not wrong in the way of writing code. But it is wrong if you don't want the component behave like that.

**Comment by wenfangdu** [comment] 2021-06-24 08:27
@JeremyWuuuuu Yeah, I agree. But I do know the cost of new `props` being created, and still prefer leaving them be if `lazyLoad` won't be triggered on re-renders just for cleaner code 😄.

**Comment by JeremyWuuuuu** [comment] 2021-06-24 08:30
Could you give me more insights about the work you are doing right now? I'd like to provide as many help as I can to help you out of this issue. If you do feel like you can share that with me please do not hesitate to ping me.

**Comment by wenfangdu** [comment] 2021-06-24 12:03
@JeremyWuuuuu Thanks, really appreciated it.

**Comment by SimonaliaChen** [comment] 2021-06-24 12:09
@wenfangdu 
> I think you meant to say "run render function on every re-render"?
Yeah, you are right. 

> Therefore, I think props is better to be checked by content, e.g. using lodash's isEqual, if so, even if the user passes a literal object for props, it won't trigger on re-renders.
Truly, watch its value but not reference is helpful in some cases such as https://github.com/element-plus/element-plus/issues/2317. However, in your case,   `props` contains a function `lazyload()`, and there is no way to compare the values of two functions. In other words, `lodash.isEqual(() => 0, () => 0)` will always return `false`. 

So IMHO, the only solution is hoisting `props`, like @JeremyWuuuuu  said.

```
import { defineComponent, ref } from 'vue'

export default defineComponent({
  setup() {
    const cascader = ref([])
    const props = {
          lazy: true,
          // 👇 triggers on every re-render, should be checked by content, e.g. using lodash's isEqual
          lazyLoad(node, resolve) {
            const { level } = node
            setTimeout(() => {
              const nodes = Array.from({ length: level + 1 }).map(() => ({
                value: ++id,
                label: `选项${id}`,
                leaf: level >= 2,
              }))
              // 通过调用resolve将子节点数据返回，通知组件数据加载完成
              resolve(nodes)
            }, 1000)
          },
        }
    let id = 0

    return () => (
      <ElCascader
        vModel={cascader.value}
        // this doesn't really have to be a reactive, simply use it as a plain object or you can use `Readonly`
        props={props}
      />
    )
  },
})

```

**Comment by wenfangdu** [comment] 2021-06-24 12:32
@SimonaliaChen You can use [`isEqualWith`](https://lodash.com/docs/4.17.15#isEqualWith), in this case:

```js
import { isEqualWith, isFunction } from 'lodash-es'

const o1 = { fn() {} }

const o2 = { fn() {} }

const equal = isEqualWith(o1, o2, (v1, v2) =>
  isFunction(v1) && isFunction(v2)
    ? v1.toString() === v2.toString()
    : undefined,
)

console.log({ equal }) // { equal: true }
```

**Comment by SimonaliaChen** [comment] 2021-06-24 15:13
> @SimonaliaChen You can use [`isEqualWith`](https://lodash.com/docs/4.17.15#isEqualWith) instead, in this case:
> 
> ```js
> import { isEqualWith, isFunction } from 'lodash-es'
> 
> const o1 = { fn() {} }
> 
> const o2 = { fn() {} }
> 
> const equal = isEqualWith(o1, o2, (v1, v2) =>
>   // if `customizer` returns `undefined`, comparisons are handled by the method instead
>   isFunction(v1) && isFunction(v2) ? `${v1}` === `${v2}` : undefined,
> )
> 
> console.log({ equal }) // { equal: true }
> ```

LGTM.

**Comment by wenfangdu** [comment] 2021-06-24 23:40
@JeremyWuuuuu @SimonaliaChen Could you consider reopening this issue given it's technically viable?

**Comment by SimonaliaChen** [comment] 2021-06-25 02:44
> @JeremyWuuuuu @SimonaliaChen Could you consider reopening this issue given it's technically viable?

Done. I will revert https://github.com/element-plus/element-plus/pull/2298 and submit another pr ASAP

**Comment by msidolphin** [comment] 2021-06-25 03:18
> It is by design but not a bug. There are truly some cases `config` should be reactive, and re-init when it change. So I think the bug is a usage problem. As you know, vue 3.x will run `setup()` on every re-render, so pass `props` a plain object directly will always be a new reference. To keep `config` immutable, you should wrap `props` with `ref` or `reactive` instead. @msidolphin

But it doesn't seem necessary to initialize it once? config is already reactive.

**Comment by SimonaliaChen** [comment] 2021-06-25 05:34
> > It is by design but not a bug. There are truly some cases `config` should be reactive, and re-init when it change. So I think the bug is a usage problem. As you know, vue 3.x will run `setup()` on every re-render, so pass `props` a plain object directly will always be a new reference. To keep `config` immutable, you should wrap `props` with `ref` or `reactive` instead. @msidolphin
> 
> But it doesn't seem necessary to initialize? config is already reactive.

When `config` change, such as  from single selection to multiple selection, the component should re-init. Of course, here's an optimal way to only watch `config`'s value change. I will submit it soon.

**Closed** 2021-06-25 08:08 UTC
Labels: bug
