### ISSUE TITLE
The El time select package runs nginx, and the options are not fully displayed

### ISSUE THREAD

**Issue by conan2008** [element-plus/element-plus#1630] opened 2021-03-13 10:17 UTC
When everything is normal in the development environment and running online, option can only display the property that disable is true, disable is false and not displayed

**Comment by bastarder** [comment] 2021-03-15 08:18
Issues without a valid reproduction link will be closed directly.
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Closed by bastarder** 2021-03-15 08:18 UTC
