### ISSUE TITLE
[Bug Report] Docs website seems not work

### ISSUE THREAD

**Issue by justforuse** [element-plus/element-plus#5080] opened 2021-12-31 06:43 UTC
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
MacOS

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/9tx3fr65/

### Steps to reproduce
Just visit the docs site

### What is Expected?
Works normally

### What is actually happening?
All the demos not work, and `404` on the console. Time is `Fri Dec 31 2021 14:43:26 GMT+0800`

**Comment by Nicholaslanic** [comment] 2021-12-31 06:51
some  pages seems not work  >_<

**Comment by emojiiii** [comment] 2021-12-31 07:03
Duplicate of #5079

**Closed** 2021-12-31 07:03 UTC
Labels: documentation, duplicate
