### ISSUE TITLE
[Feature Request] ElDropdown selected without highlighting

### ISSUE THREAD

**Issue by kailong321200875** [element-plus/element-plus#5111] opened 2022-01-03 02:09 UTC
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Google Chrome 版本 96.0.4664.110（正式版本） （64 位）

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/02zcjLqx/

### Steps to reproduce
No highlight

### What is Expected?
I want to add a V-model to control the highlighting behavior

### What is actually happening?
No highlight

**Comment by TeCHiScy** [comment] 2022-01-03 02:47
Seems like this is a feature request, not a bug?

**Comment by kailong321200875** [comment] 2022-01-03 05:28
> Seems like this is a feature request, not a bug?

yes, you are right

**Comment by Alanscut** [comment] 2022-01-04 02:51
do you mean highlighting  like this？
![image](https://user-images.githubusercontent.com/21104054/148003187-68a84243-08a2-463a-ac4d-7114b981a475.png)
![image](https://user-images.githubusercontent.com/21104054/148003195-0a41ff40-ffd4-495d-a4b7-9d66298ada0c.png)

**Comment by kailong321200875** [comment] 2022-01-04 03:49
> do you mean highlighting like this？ ![image](https://user-images.githubusercontent.com/21104054/148003187-68a84243-08a2-463a-ac4d-7114b981a475.png) ![image](https://user-images.githubusercontent.com/21104054/148003195-0a41ff40-ffd4-495d-a4b7-9d66298ada0c.png)

yes

**Comment by Alanscut** [comment] 2022-01-04 03:53
it seems you can set `style` or `class` to display highlighting, I don't think it need to add a new attribute

**Comment by kailong321200875** [comment] 2022-01-04 04:05
> it seems you can set `style` or `class` to display highlighting, I don't think it need to add a new attribute

I think this is necessary, because if you customize the style, it may not be consistent with the highlighting of other components

**Comment by emojiiii** [comment] 2022-01-04 06:09
> I think this is necessary, because if you customize the style, it may not be consistent with the highlighting of other components
I think the highlight should be left to the user. If you are worried about consistency, you can implement a similar `config-provider` to control

**Comment by Alanscut** [comment] 2022-01-04 06:25
> > I think this is necessary, because if you customize the style, it may not be consistent with the highlighting of other components
> 
> I think the highlight should be left to the user. If you are worried about consistency, you can implement a similar `config-provider` to control

i think so

**Comment by kailong321200875** [comment] 2022-01-05 00:22
> > > I think this is necessary, because if you customize the style, it may not be consistent with the highlighting of other components
> > 
> > 
> > I think the highlight should be left to the user. If you are worried about consistency, you can implement a similar `config-provider` to control
> 
> i think so

I think it's reasonable to add a default highlight, because after all, only a few people will customize this behavior

**Comment by emojiiii** [comment] 2022-01-05 00:33
if you want to highlight, i suggest you use `el-select`. because `el-dropdown` has no selection effect

**Comment by Alanscut** [comment] 2022-01-11 02:36
@kailong321200875 
what do you think?
if you don't have other problem of this, we will close the issue

**Comment by kailong321200875** [comment] 2022-01-12 00:59
> @kailong321200875 what do you think? if you don't have other problem of this, we will close the issue

OK, you can close it

**Closed** 2022-01-12 01:01 UTC
Labels: feature request, needs discussion, has workaround, Component: Dropdown
