### ISSUE TITLE
[Help] Dropdown issue

### ISSUE THREAD

**Issue by vadimt2** [element-plus/element-plus#1768] opened 2021-04-06 12:54 UTC
it break entire application
```
 <el-dropdown trigger="click">
      <span class="el-dropdown-link">
        Dropdown List<i class="el-icon-arrow-down el-icon--right"></i>
      </span>
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item icon="el-icon-plus">Action 1</el-dropdown-item>
          <el-dropdown-item icon="el-icon-circle-plus">Action 2</el-dropdown-item>
          <el-dropdown-item icon="el-icon-circle-plus-outline">Action 3</el-dropdown-item>
          <el-dropdown-item icon="el-icon-check">Action 4</el-dropdown-item>
          <el-dropdown-item icon="el-icon-circle-check">Action 5</el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>
```

Error:
```
[Vue warn]: Unhandled error during execution of mounted hook 
  at <ElDropdownMenu> 
  at <ElScrollbar ref="scrollbar" tag="ul" wrap-style="max-height: "  ... > 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> onBeforeEnter=fn<onBeforeEnter>  ... > 
  at <Transition name="el-zoom-in-top" onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave>  ... > 
  at <ElPopper ref="triggerVnode" visible=false onUpdate:visible=fn  ... > 
  at <ElDropdown trigger="click" > 
  at <FileDocument onRemoveSingleFile=fn<bound removeSingleFile> isSignaleR=true fileMeta= Object  ... > 
  at <ElTableBody context= Object highlight=false row-class-name=undefined  ... > 
  at <ElTable key=0 ref="propFileTreeTable" data= Array(2)  ... > 
  at <MyComponentName ref="filesComponent" documentsData= Array(2) fileMeta= Object  ... > 
  at <ElRow element-loading-text="Загрузка..." style= Object > 
  at <PropertiesTab ref="propertiesComponent" onChnageStructureTree=fn<bound chnageStructureTree> onShowModelTree=fn<bound showModelTree> > 
  at <ElTabPane label="Свойства" name="properties" > 
  at <ElTabs modelValue="properties" onUpdate:modelValue=fn type="card" > 
  at <ElCard class="control-panel filter-card" ref="propertiesPanel" > 
  at <ElRow class="project-container" element-loading-text="::ProjectChangingPleaseWait::..." id="34" > 
  at <Project id="34" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy > > 
  at <RouterView> 
  at <ElMain> 
  at <Main onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy > > 
  at <RouterView> 
  at <App>
```

After i comment the drop-down all my application is working how it should be

**Comment by JeremyWuuuuu** [comment] 2021-04-07 02:25
Sorry that we made breaking changes in this version, I will reply in this thread to keep you notified once I identified the root cause.

**Comment by JeremyWuuuuu** [comment] 2021-04-07 02:38
I pasted your code locally and online IDE see [CodeSandBox](https://codesandbox.io/s/naughty-booth-m88f8?file=/src/App.vue), and the screenshot I pasted below, both are working as expected, could you provide your version of:
1. Vue
2. ElementPlus

to me?
Attachments:
![image](https://user-images.githubusercontent.com/15975785/113802454-5bb98580-978d-11eb-877f-feb8ce7ce1e5.png)

**Comment by vadimt2** [comment] 2021-04-07 06:42
I don't know why i had this issue, it happened when i was clicking on some elements in the DOM
and then i had that error message.
My solution:
I have switched the functionality to **popover** 
https://element-plus.org/#/en-US/component/popover

**Comment by JeremyWuuuuu** [comment] 2021-04-07 07:17
We still have a component named: `el-select` almost does the same thing like `el-dropdown`. Even though you had a work around, but we still need to find out what was going on with your issue, if you can provide a detailed reproducible code sample with Vue's version and ElementPlus's version that should help us to locate the root cause.

**Comment by JeremyWuuuuu** [comment] 2021-04-08 03:29
I will close this issue since you have solved the problem, feel free to reopen it.

**Closed by JeremyWuuuuu** 2021-04-08 03:29 UTC
