### ISSUE TITLE
[Bug Report] el-dropdown-item is not set as a class, as an attr only

### ISSUE THREAD

**Issue by ReWWeR** [element-plus/element-plus#5783] opened 2022-02-04 10:39 UTC
### Element Plus version
1.3.0-beta.10

### OS/Browsers version
Mac OS, Chrome

### Vue version
3.2.29

### Reproduction Link
https://jsfiddle.net/mdueysa7/

### Steps to reproduce
- Click on dropdown link.
- Check that class is not set

### What is Expected?
Class is set as a class

### What is actually happening?
Class not setted, only exists in attrs

**Comment by emojiiii** [comment] 2022-02-05 04:37
Duplicate of #5768

**Closed** 2022-02-05 04:37 UTC
Labels: bug, duplicate, Component: Dropdown
