### ISSUE TITLE
DatePicker, DateTimePicker are wrapped by Card，overflow: hidden;

### ISSUE THREAD

**Issue by lqsong** [element-plus/element-plus#764] opened 2020-12-02 02:52 UTC
```vue
<template>
<el-card >
    <el-date-picker 
        type="daterange" 
        v-model="value1" 
        range-separator="至" 
        start-placeholder="开始日期" 
        end-placeholder="结束日期">                            
   </el-date-picker>
</el-card>
</template>
<script>
  export default {
    data() {
      return {       
        value1: '',
      };
    }
  };
</script>
```
![20201202105219](https://user-images.githubusercontent.com/22975974/100822018-7a7cd800-348c-11eb-9729-abc38c5196b5.png)

**Comment by JeremyWuuuuu** [comment] 2020-12-02 02:56
Right, this was a regression bug caused by the change to `el-popper`. Will be fixed soon.

**Closed** 2020-12-02 03:38 UTC
Labels: bug
