### ISSUE TITLE
[Bug Report] el-input使用 suffix插槽导致.el-icon优先级高于.el-input__icon，icon无法居中

### ISSUE THREAD

**Issue by yudan215** [element-plus/element-plus#5702] opened 2022-01-30 02:21 UTC
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
win10

### Vue version
3.2.29

### Reproduction Link
https://github.com/TothingWay/test-ep

### Steps to reproduce
<el-input v-model="model.numer">
            <template #suffix>
              <el-icon class="el-input__icon" @click="tableRef.reload()">
                <search />
              </el-icon>
            </template>
          </el-input>

### What is Expected?
正常显示

### What is actually happening?
样式被覆盖
![image](https://user-images.githubusercontent.com/26323005/151684236-75554f70-273b-403b-8885-8d6c1760f338.png)

**Comment by emojiiii** [comment] 2022-01-30 16:18
Duplicate of #5667

**Closed** 2022-01-30 16:18 UTC
Labels: duplicate, Component: Input
