### ISSUE TITLE
[Bug Report] Pagination: i18n error

### ISSUE THREAD

**Issue by CarterLi** [element-plus/element-plus#5123] opened 2022-01-04 03:07 UTC
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
N/A

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/do/not/use/

### Steps to reproduce
https://element-plus.gitee.io/zh-CN/component/pagination.html#%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD

### What is Expected?
i18n should work. Chinese words should be shown instead of English words.

### What is actually happening?
English words are shown

**Comment by emojiiii** [comment] 2022-01-04 03:14
Duplicate of #5078

**Closed** 2022-01-04 03:14 UTC
