### ISSUE TITLE
[Bug Report] el-date-picker/el-time-picker component generates warnings when using v-show directive, "Runtime directive used on component with non-element root node...."

### ISSUE THREAD

**Issue by YuancaiDing** [element-plus/element-plus#2279] opened 2021-06-20 13:02 UTC
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
Chrome

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-ms973?file=/src/App.vue:0-143

### Steps to reproduce
<template>
  <div>
    <el-date-picker
      v-show="true"
      v-model="value1"
      type="date">
    </el-date-picker>
  </div>
</template>

### What is Expected?
Browser console should not have warnings for a mature component used in page 

### What is actually happening?

runtime-core.esm-bundler.js:38 [Vue warn]: Runtime directive used on component with non-element root node. The directives will not function as intended. 
  at <ElPopper ref="refPopper" visible=false onUpdate:visible=fn  ... > 
  at <Picker modelValue="" type="date" placeholder="选择日期"  ... > 
  at <ElDatePicker modelValue="" onUpdate:modelValue=fn type="date"  ... > 
  at <ElDatePicker onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <App>

**Comment by XingXiaoWu** [comment] 2021-06-25 06:57
can you provide any reproduction link?

**Comment by sxzz** [comment] 2021-09-10 15:57
It seems to be a duplicate of #3281

**Closed by sxzz** 2021-09-10 15:57 UTC
Labels: 🤔 need reproduce
