### ISSUE TITLE
menu的折叠动画不起效果

### ISSUE THREAD

**Issue by wzohxia** [element-plus/element-plus#968] opened 2020-12-11 06:31 UTC
```
<el-menu default-active="2" class="el-menu-vertical-demo">
    <el-submenu index="1">
      <template #title>
        <i class="el-icon-location"></i>
        <span>导航一</span>
      </template>
      <el-menu-item-group>
        <template #title>分组一</template>
        <el-menu-item index="1-1">选项1</el-menu-item>
        <el-menu-item index="1-2">选项2</el-menu-item>
      </el-menu-item-group>
      <el-menu-item-group title="分组2">
        <el-menu-item index="1-3">选项3</el-menu-item>
      </el-menu-item-group>
      <el-submenu index="1-4">
        <template #title>选项4</template>
        <el-menu-item index="1-4-1">选项1</el-menu-item>
      </el-submenu>
    </el-submenu>
    <el-menu-item index="2">
      <i class="el-icon-menu"></i>
      <template #title>导航二</template>
    </el-menu-item>
    <el-menu-item index="3" disabled>
      <i class="el-icon-document"></i>
      <template #title>导航三</template>
    </el-menu-item>
    <el-menu-item index="4">
      <i class="el-icon-setting"></i>
      <template #title>导航四</template>
    </el-menu-item>
  </el-menu>
```

**Comment by JeremyWuuuuu** [comment] 2020-12-11 06:33
@Liiked is on his way of fixing this.

**Comment by Bo-LiangD** [comment] 2020-12-11 08:29
问题 解决了嘛 弱弱的 问一句 嘿嘿

**Comment by Liiked** [comment] 2020-12-11 08:42
> 问题 解决了嘛 弱弱的 问一句 嘿嘿

Is your problem same as #832 ?

**Comment by Bo-LiangD** [comment] 2020-12-11 08:57
是的

**Comment by erbaihuang** [comment] 2020-12-14 06:30
Has it been fixed in 1.0.1-beta.8?

**Comment by JeremyWuuuuu** [comment] 2020-12-14 06:59
> Has it been fixed in 1.0.1-beta.8?

Nah, we will try our best to fix that as fast as we can. Once this issue is fixed, this issue will get closed along with the PR.

**Comment by Liiked** [comment] 2020-12-14 08:47
the issue is related to the feature of [new transition class in vue3](https://v3.vuejs.org/guide/migration/transition.html), which triggers the [#2593](https://github.com/vuejs/vue-next/issues/2593) & [#2531](https://github.com/vuejs/vue-next/issues/2531).

fix of 2593 & 2531 is worked, but causes animation failure in hooks of 'leave'. We'll find a moderate way to fix this ASAP.

**Comment by wangshixiang1984** [comment] 2020-12-14 09:07
Have the same problem, when collapse and expand, no animation . when click submenu,  have animation on drop dwon but no on slide up

**Comment by JeremyWuuuuu** [comment] 2020-12-15 06:46
> Have the same problem, when collapse and expand, no animation . when click submenu, have animation on drop dwon but no on slide up

Got it, will fix soon.

**Closed** 2020-12-16 14:28 UTC
Labels: bug, investigating

**Comment by bytrix** [comment] 2021-11-13 04:49
You guys are all Chinese, why communicate in English?

**Comment by sxzz** [comment] 2021-11-13 05:02
@bytrix Please refer to https://www.zhihu.com/question/49884331/answer/1872198782
