### ISSUE TITLE
[Bug Report] el-popover 'after-enter', 'after-leave' events not emitting

### ISSUE THREAD

**Issue by Giwayume** [element-plus/element-plus#5669] opened 2022-01-27 05:08 UTC
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
Any

### Vue version
3.2.29

### Reproduction Link
https://jsfiddle.net/msrjagvw/

### Steps to reproduce
Listen to after-enter or after-leave event on an el-popover, never emits.

### What is Expected?
after-enter and after-leave events emit.

### What is actually happening?
after-enter or after-leave do not emit.

**Comment by emojiiii** [comment] 2022-01-27 14:15
Duplicate of #5467

**Closed** 2022-01-27 14:15 UTC
Labels: bug, duplicate, Component：Popover
