### ISSUE TITLE
[Bug Report] dropdown disabled不管用

### ISSUE THREAD

**Issue by guohuihot** [element-plus/element-plus#5641] opened 2022-01-26 02:08 UTC
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
1

### Vue version
3.2.29

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
disabled不管用

### What is Expected?
```jsx
<el-dropdown
        disabled={true}
        vSlots={{
          dropdown: () => {
            return (
              <el-dropdown-menu>
                <el-dropdown-item>Action 1</el-dropdown-item>
                <el-dropdown-item>Action 2</el-dropdown-item>
                <el-dropdown-item>Action 3</el-dropdown-item>
                <el-dropdown-item disabled>Action 4</el-dropdown-item>
                <el-dropdown-item divided>Action 5</el-dropdown-item>
              </el-dropdown-menu>
            )
          },
        }}
      >
        <span class='el-dropdown-link'>
          Dropdown List
          <el-icon class='el-icon--right'>
            <arrow-down />
          </el-icon>
        </span>
      </el-dropdown>
```

### What is actually happening?
```jsx
<el-dropdown
        disabled={true}
        vSlots={{
          dropdown: () => {
            return (
              <el-dropdown-menu>
                <el-dropdown-item>Action 1</el-dropdown-item>
                <el-dropdown-item>Action 2</el-dropdown-item>
                <el-dropdown-item>Action 3</el-dropdown-item>
                <el-dropdown-item disabled>Action 4</el-dropdown-item>
                <el-dropdown-item divided>Action 5</el-dropdown-item>
              </el-dropdown-menu>
            )
          },
        }}
      >
        <span class='el-dropdown-link'>
          Dropdown List
          <el-icon class='el-icon--right'>
            <arrow-down />
          </el-icon>
        </span>
      </el-dropdown>
```

**Comment by emojiiii** [comment] 2022-01-26 03:00
Duplicate of #4319

**Closed** 2022-01-26 03:01 UTC
Labels: bug, duplicate, Component: Dropdown
