### ISSUE TITLE
[bug report] pagination {total} error

### ISSUE THREAD

**Issue by 360060316** [element-plus/element-plus#4715] opened 2021-12-07 14:08 UTC
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Pagination 分页 {total} 错误

### Vue version
3.2.24

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/666/

### Steps to reproduce
Pagination 分页 {total} 错误

### What is Expected?
Pagination 分页 {total} 错误

### What is actually happening?
Pagination 分页 {total} 错误

**Comment by btea** [comment] 2021-12-08 01:08
Duplicate of #4617. Fix in #4619

**Comment by kuaifengle** [comment] 2021-12-08 02:03
![image](https://user-images.githubusercontent.com/24524172/145135343-fc3de823-8791-4b34-8ee3-b70e5ebd03e4.png)
![image](https://user-images.githubusercontent.com/24524172/145135364-39fecd3d-1d1d-42ad-b739-b7d901d1caf3.png)

**Comment by neohan666** [comment] 2021-12-08 09:23
+1

**Comment by sxzz** [comment] 2021-12-08 10:39
此 bug 以修复，请等待下一个版本发布。

**Closed** 2021-12-08 10:38 UTC
Labels: duplicate
