### ISSUE TITLE
[Component] [form-item] Form Item 属性required设置为true时，当校验不通过时，显示提示信息为英文

### ISSUE THREAD

**Issue by YuShengSenior** [element-plus/element-plus#9778] opened 2022-09-15 08:10 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.16`
- Browser / OS: `chrome 105.0.5195.125（正式版本） (arm64)/macOS12.6`
- Build Tool: `Vite`

### Related Component

- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgPGVsLWZvcm0taXRlbSByZXF1aXJlZCBsYWJlbD1cIkNvbmZpcm1cIiBwcm9wPVwiY2hlY2tQYXNzXCI+XG4gICAgICA8ZWwtaW5wdXRcbiAgICAgICAgdi1tb2RlbD1cIm1zZ1wiXG4gICAgICAgIGF1dG9jb21wbGV0ZT1cIm9mZlwiXG4gICAgICAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

鼠标失去焦点时，触发非空校验，在项目中el-config-provider已经设置为中文，但是提示信息仍为英文

### What is Expected?

提示信息“消息不能为空”

### What is actually happening?

提示信息“msg is required”

### Additional comments

_(empty)_

**Comment by sxzz** [comment] 2022-09-16 16:57
duplicate of #6788

**Closed by sxzz** 2022-09-16 16:57 UTC
