### ISSUE TITLE
Bug with Slider

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#1046] opened 2020-12-18 09:17 UTC
The slider button still move when mouseup on the tooltip.
Reproduction steps:
1. Drag the round button and mousemove. ![image](https://user-images.githubusercontent.com/38392315/102596732-90f58580-4154-11eb-8389-ae262188f93c.png)
2. Mouse up on the tooltip. ![image](https://user-images.githubusercontent.com/38392315/102596699-7e7b4c00-4154-11eb-8384-141145cb4074.png)
3. Mousemove and you'll see.

**Comment by JeremyWuuuuu** [comment] 2020-12-18 09:44
Seems like the same bug in #1029 ?

**Comment by Ryan2128** [comment] 2020-12-21 02:28
will fix.

**Comment by serializedowen** [comment] 2020-12-21 09:53
Duplicate of #1029

**Closed** 2020-12-23 10:10 UTC
Labels: bug
