### ISSUE TITLE
[Component] [table] showAfter option of tooltip-options not work

### ISSUE THREAD

**Issue by qiuhengyu** [element-plus/element-plus#13401] opened 2023-06-28 12:50 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.2`
- Element Plus Version: `2.3.7`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IiAgICBcbiAgICA8dGVtcGxhdGU+XG4gICAgICAgXG4gICAgICA8ZWwtdGFibGVcbiAgICAgIDpkYXRhPVwibGlzdFwiXG4gICAgICAgIDp0b29sdGlwLW9wdGlvbnM9XCJ7c2hvd0FmdGVyOjEwMDAsZW50ZXJhYmxlOmZhbHNlLHBsYWNlbWVudDonbGVmdCd9XCI+XG4gICAgICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgICAgcHJvcD1cInRpdGxlXCJcbiAgICAgICAgc2hvdy1vdmVyZmxvdy10b29sdGlwXG4gICAgICAgIGxhYmVsPVwi5qCH6aKYXCJcbiAgICAgICAgd2lkdGg9XCIzMDBcIj5cbiAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgPC9lbC10YWJsZT5cbiAgICA8L3RlbXBsYXRlPlxuICAgIFxuICAgIDxzY3JpcHQ+XG4gICAgZXhwb3J0IGRlZmF1bHQge1xuICAgICAgICBkYXRhKCkge1xuICAgICAgICAgIHJldHVybiB7XG4gICAgICAgICAgICBsaXN0OiBbe3RpdGxlOidUb21Ub21Ub21Ub21Ub21Ub21Ub21Ub21Ub21Ub21Ub21Ub21Ub21Ub21Ub21Ub21Ub20nfV0sXG4gICAgICAgICAgfTtcbiAgICAgICAgfSxcbiAgICB9XG4gICAgPC9zY3JpcHQ+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

hover the title

### What is Expected?

show tooltip after 1000ms

### What is actually happening?

show immediately

### Additional comments

the option of 'enterable' not work too

**Comment by btea** [comment] 2023-06-28 22:58
Duplicate of #12564

**Closed** 2023-06-28 22:58 UTC
