### ISSUE TITLE
El-select - in multiple el-select, select not display correctly

### ISSUE THREAD

**Issue by ntgraph** [element-plus/element-plus#687] opened 2020-11-24 23:58 UTC
On multiple cascading dropdown ( multiple select) . 
Example, on selecting a city in a list, page should display country and province
Country is already preload in state, so the first select display the label correctly.
List of provinces is loaded in mounted cycle when providing the city object, inside this object there is a province id. however it seems like this data list come too late and the second select display the id (number) instead of the corresponding label of the province..

I test with a provided list of province in data, then the second select display correctly.

This is in Vue 3, list of provinces when arrived is in form of Proxy, I read a bit of reactivity change in Vue 3, but I don't know how to apply.  Can you kindly show me.

Thanks

**Comment by JeremyWuuuuu** [comment] 2020-11-25 02:38
Issues without a valid reproduction link will be closed directly.
Unless you could provide us a minimal reproducible code, we were not able to help you with that.

**Comment by JeremyWuuuuu** [comment] 2020-11-25 03:05
I think this is a typical `Cascader` situation. Check this out: [Cascader](https://element-plus.org/#/en-US/component/cascader) checkout the `Dynamic loading` section, this could be something you want I suppose.

**Comment by JeremyWuuuuu** [comment] 2020-11-25 03:06
I still want you to provide us some sort of code that we can help you better with a demo

**Comment by ntgraph** [comment] 2020-11-25 14:11
Here is my code, it works well in Vue 2.6 with Element UI

``` <label
                for="countryName"
                class="block text-left pt-4 pb-2"
                :class="{required: countryNameRequired}"
            >
                {{ $t('city.countryName')}}
            </label>
            <div class="sm:w-full md:w-3/5 lg:w-2/5">
                <el-select
                    v-model="city.country_id"
                    :placeholder="$t('city.selectCountry')"
                    class="w-full administration"
                    @change="onCountryChange"
                >
                    <el-option
                        v-for="item in countries"
                        :key="`country-${item.id}`"
                        :label="item[getCountry]"
                        :value="item.id">
                        <span style="float: left" class="administration">{{ item[getCountry] }}</span>
                    </el-option>
                </el-select>
            </div>
            <label
                for="provinceName"
                class="block text-left pt-4 pb-2"
                :class="{required: provinceNameRequired}"
            >
                {{ $t('city.provinceName')}}
            </label>
            <div class="sm:w-full md:w-3/5 lg:w-2/5">
                <el-select v-model="city.province_id" :placeholder="$t('city.selectProvince')" class="w-full administration" :disabled="!city.country_id">
                    <el-option
                        v-for="item in provinces"
                        :key="`province-${item.id}`"
                        :label="item[getProvince]"
                        :value="item.id">
                        <span style="float: left" class="administration">{{ item[getProvince] }}</span>
                    </el-option>
                </el-select>
            </div>
<script>
    import { mapGetters } from 'vuex';
    import City from '../../entities/City.js';
    import province from '../../api/province.js';
    import city from '../../api/city.js';

    export default {
        name: 'EditCity',

        data() {
            return {
                city: new City(),
                countries: [],
                provinces: [],
                errors: [],
                loading: false,
                provinces2: [
                    {id:1, provinceName_en: "Ontario"},
                    {id:2, provinceName_en: "Quebec"},
                    {id:3, provinceName_en: "Alberta"},
                    {id:4, provinceName_en: "Newfoundland"},
                    {id:5, provinceName_en: "Manitoba"},
                ]
            };
        },

        computed: {
            ...mapGetters([
                'getConfigs',
            ]),

            getCountry() {
                return `countryName_${this.$i18n.locale}`;
            },

            getProvince() {
                return `provinceName_${this.$i18n.locale}`;
            },

            disabled() {
                return this.countryNameRequired
                    || this.provinceNameRequired
                    || this.cityNameEnRequired
                    || this.cityNameFrRequired
                    || this.cityNameEsRequired;
            },


            countryNameRequired() {
                return !this.city.country_id;
            },

            provinceNameRequired() {
                return !this.city.province_id;
            },

            cityNameEnRequired() {
                return !this.city.cityName_en;
            },

            cityNameFrRequired() {
                return !this.city.cityName_fr;
            },

            cityNameEsRequired() {
                return !this.city.cityName_es;
            },
        },

        methods: {
            async fetchCity() {
                try {
                    this.city = await city.show(this.$route.params.id);

                    if (this.city.country_id) {
                        this.provinces = await province.listProvincePerCountry(this.city.country_id);
                        const provinceName = this.getProvince;
                        this.provinces.sort((a,b) => (a[provinceName] > b[provinceName]) ? 1: -1);
                    }

                } catch (error) {
                    if (!error.response)
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.contactSupport') + 'Code F0013',
                            duration: 0
                        });

                    if (error.response.status === 403) {
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.forbidden'),
                            duration: 0
                        });
                    }
                }
            },

            async onCountryChange(countryId) {
                this.city.province_id = null;
                this.provinces = await province.listProvincePerCountry(countryId);
                const provinceName = this.getProvince;
                this.provinces.sort((a,b) => (a[provinceName] > b[provinceName]) ? 1: -1);
            },

            async updateCity() {
                try {
                    this.loading = true;
                    await city.update(this.$route.params.id, this.city);
                    this.loading = false;
                    this.$notify.success({
                        title: this.$t('alert.success'),
                        message: this.$t('alert.successfullyUpdated'),
                    });
                    this.cancel();

                } catch (error) {
                    this.loading = false;
                    if (!error.response) {
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.contactSupport') + 'Code F0014',
                            duration: 0
                        });
                    }

                    if (error.response.status === 403) {
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.forbidden'),
                            duration: 0
                        });
                    }

                    if (error.response.data.error) {
                        this.errors = [];
                        this.errors = Object.values(error.response.data.error.message);
                    }
                }
            },

            cancel() {
                this.$router.push({ name: 'city.index' });
            },

            translationKey(value) {
                return `validation.city.${value}`;
            },

            async init() {
                const countryName = this.getCountry;
                this.countries = this.getConfigs.countries.sort((a,b) => (a[countryName] > b[countryName]) ? 1: -1);

                await this.fetchCity();
            }
        },

        async mounted() {
            await this.init();
        }
    }
</script>

**Comment by ntgraph** [comment] 2020-11-26 14:08
Hi Jeremy, 
please check your email. I were not able to put all my codes and images on this issue here.  I am a beginner in Github, please forgive me.    
Thanks,
Lap

**Comment by JeremyWuuuuu** [comment] 2020-11-26 15:17
> Hi Jeremy,
> please check your email. I were not able to put all my codes and images on this issue here. I am a beginner in Github, please forgive me.
> Thanks,
> Lap

Gotcha, I will take a look tomorrow on my local time.

**Comment by JeremyWuuuuu** [comment] 2020-11-27 05:45
So I got your code pasted below:

```vue
<template>
    <div class="-mt-70px rounded mx-2 bg-white my-2 shadow-md administration">
        <h1>{{ $t('sidebarNav.city')}}</h1>
        <h2>{{ $t('city.editCity') }}</h2>
        <form
            class="mx-2"
            autocomplete="on"
            @submit.prevent="updateCity"
            method="post"
        >
            <label
                for="countryName"
                class="block text-left pt-4 pb-2"
                :class="{required: countryNameRequired}"
            >
                {{ $t('city.countryName')}}
            </label>
            <div class="sm:w-full md:w-3/5 lg:w-2/5">
                <el-select
                    v-model="city.country_id"
                    :placeholder="$t('city.selectCountry')"
                    class="w-full administration"
                    @change="onCountryChange"
                >
                    <el-option
                        v-for="item in countries"
                        :key="`country-${item.id}`"
                        :label="item[getCountry]"
                        :value="item.id">
                        <span style="float: left" class="administration">{{ item[getCountry] }}</span>
                    </el-option>
                </el-select>
            </div>
            <label
                for="provinceName"
                class="block text-left pt-4 pb-2"
                :class="{required: provinceNameRequired}"
            >
                {{ $t('city.provinceName')}}
            </label>
            <div class="sm:w-full md:w-3/5 lg:w-2/5">
                <el-select v-model="city.province_id" :placeholder="$t('city.selectProvince')" class="w-full administration" :disabled="!city.country_id">
                    <el-option
                        v-for="item in provinces"
                        :key="`province-${item.id}`"
                        :label="item[getProvince]"
                        :value="item.id">
                        <span style="float: left" class="administration">{{ item[getProvince] }}</span>
                    </el-option>
                </el-select>
            </div>
            <label
                for="cityName_en"
                class="block text-left pt-4 pb-2"
                :class="{required: cityNameEnRequired}"
            >
                {{ $t('city.cityNameInEnglish')}}</label>
            <div class="sm:w-full md:w-3/5 lg:w-2/5">
                <app-input
                    type="text"
                    clearable
                    autofocus
                    required
                    :maxlength="50"
                    v-model:text="city.cityName_en"
                />
            </div>
            <label
                for="cityName_fr"
                class="block text-left pt-4 pb-2"
                :class="{required: cityNameFrRequired}"
            >
                {{ $t('city.cityNameInFrench')}}</label>
            <div class="sm:w-full md:w-3/5 lg:w-2/5">
                <app-input
                    type="text"
                    clearable
                    autofocus
                    required
                    :maxlength="50"
                    v-model:text="city.cityName_fr"
                />
            </div>
            <label
                for="cityName_es"
                class="block text-left pt-4 pb-2"
                :class="{required: cityNameEsRequired}"
            >
                {{ $t('city.cityNameInSpanish')}}</label>
            <div class="sm:w-full md:w-3/5 lg:w-2/5">
                <app-input
                    type="text"
                    clearable
                    autofocus
                    required
                    :maxlength="50"
                    v-model:text="city.cityName_es"
                />
            </div>
            <template v-if="errors.length">
                <br>
                <div class="bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4 mx-8 break-normal" role="alert" >
                    <p class="font-bold">{{ $t('alert.errorValidationMessage') }}</p>
                    <ul >
                        <li class="list-disc ml-5" v-for="(value, index) in errors" :key="index">
                            {{ $t(translationKey(value)) }}
                        </li>
                    </ul>
                </div>
            </template>
            <div class="ml-2">
                <app-button
                    class="btn-common hover:bg-cancel-100 hover:text-cancel hover:border-cancel-200 px-4 mb-4 rounded"
                    @click="cancel"
                >
                    {{ $t('button.cancel')}}
                </app-button>
                <app-button
                    class="btn-common-navy-blue bg-navy-blue hover:bg-navy-blue-900 text-white mt-4 mx-2 px-4 mb-4 rounded"
                    submit
                    :disabled="disabled"
                    :class="disabled ? 'cursor-not-allowed' : ''"
                    :loading="loading"
                >
                    <i class="fal fa-check mr-2" /> {{ $t('button.update')}}
                </app-button>
            </div>
        </form>
    </div>
</template>

<script>
    import { mapGetters } from 'vuex';
    import City from '../../entities/City.js';
    import province from '../../api/province.js';
    import city from '../../api/city.js';
    import { isReactive } from 'vue'

    export default {
        name: 'EditCity',

        data() {
            return {
                city: new City(),
                countries: [],
                provinces: [],
                errors: [],
                loading: false,
                provinces2: [
                    {id:1, provinceName_en: "Ontario"},
                    {id:2, provinceName_en: "Quebec"},
                    {id:3, provinceName_en: "Alberta"},
                    {id:4, provinceName_en: "Newfoundland"},
                    {id:5, provinceName_en: "Manitoba"},
                ]
            };
        },

        computed: {
            ...mapGetters([
                'getConfigs',
            ]),

            getCountry() {
                return `countryName_${this.$i18n.locale}`;
            },

            getProvince() {
                return `provinceName_${this.$i18n.locale}`;
            },

            disabled() {
                return this.countryNameRequired
                    || this.provinceNameRequired
                    || this.cityNameEnRequired
                    || this.cityNameFrRequired
                    || this.cityNameEsRequired;
            },


            countryNameRequired() {
                return !this.city.country_id;
            },

            provinceNameRequired() {
                return !this.city.province_id;
            },

            cityNameEnRequired() {
                return !this.city.cityName_en;
            },

            cityNameFrRequired() {
                return !this.city.cityName_fr;
            },

            cityNameEsRequired() {
                return !this.city.cityName_es;
            },
        },

        methods: {
            async fetchCity() {
                try {
                    this.city = await city.show(this.$route.params.id);

                    if (this.city.country_id) {
                        this.provinces = await province.listProvincePerCountry(this.city.country_id);
                        const provinceName = this.getProvince;
                        this.provinces.sort((a,b) => (a[provinceName] > b[provinceName]) ? 1: -1);
                    }
console.log('provinces', isReactive(this.provinces));
console.log('this el', this)
                } catch (error) {
                    if (!error.response)
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.contactSupport') + 'Code F0013',
                            duration: 0
                        });

                    if (error.response.status === 403) {
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.forbidden'),
                            duration: 0
                        });
                    }
                }
            },

            async onCountryChange(countryId) {
                this.city.province_id = null;
                this.provinces = await province.listProvincePerCountry(countryId);
                const provinceName = this.getProvince;
                this.provinces.sort((a,b) => (a[provinceName] > b[provinceName]) ? 1: -1);
            },

            async updateCity() {
                try {
                    this.loading = true;
                    await city.update(this.$route.params.id, this.city);
                    this.loading = false;
                    this.$notify.success({
                        title: this.$t('alert.success'),
                        message: this.$t('alert.successfullyUpdated'),
                    });
                    this.cancel();

                } catch (error) {
                    this.loading = false;
                    if (!error.response) {
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.contactSupport') + 'Code F0014',
                            duration: 0
                        });
                    }

                    if (error.response.status === 403) {
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.forbidden'),
                            duration: 0
                        });
                    }

                    if (error.response.data.error) {
                        this.errors = [];
                        this.errors = Object.values(error.response.data.error.message);
                    }
                }
            },

            cancel() {
                this.$router.push({ name: 'city.index' });
            },

            translationKey(value) {
                return `validation.city.${value}`;
            },

            async init() {
                const countryName = this.getCountry;
                this.countries = this.getConfigs.countries.sort((a,b) => (a[countryName] > b[countryName]) ? 1: -1);

                await this.fetchCity();
            }
        },

        async created() {
            await this.init();
        }
    }
</script>

<style lang="less">
    /* Input */
    div.administration .el-input__inner:focus {
        border-color: #0057ff;
    }

    /* Select */
    div.administration .el-select .el-input.is-focus .el-input__inner, .el-select .el-input__inner:focus {
        border-color: #0057ff;
    }

    div.administration div.el-input.el-input--suffix.is-focus input.el-input__inner{
        border-color: #0057ff;
    }

    .el-select-dropdown__item.selected span.administration {
        font-weight: 700;
        color: #0057ff;
    }
</style>
```

In order to find the problem I need you to provide the `City` class, also from the screenshot:
![Screenshot](https://user-images.githubusercontent.com/15975785/100414726-5d738e00-30b5-11eb-9d5a-400b9eda3c0f.PNG)
So the value displayed on the UI is a mapping to `:value` binding in `el-option` in your case here is 
```vue
<el-option
    v-for="item in provinces"
    :key="`province-${item.id}`"
    :label="item[getProvince]" // expected to display
    :value="item.id"> // actually displayed
        <span style="float: left" class="administration">{{ item[getProvince] }}</span>
</el-option>
```

**Comment by JeremyWuuuuu** [comment] 2020-11-27 05:46
And I am sure that this is a bug from us, which needs to be fixed. Sorry for causing you trouble. I will fix it ASAP

**Comment by JeremyWuuuuu** [comment] 2020-11-27 06:02
This code below is a basic usage of select. which is the basic usage of `ElSelect`
```vue
<template>
  <el-select v-model="value" placeholder="Select">
    <el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value">
      item {{ item.value }}
    </el-option>
  </el-select>
</template>

<script>
  export default {
    data() {
      return {
        options: [{
          value: '1',
          label: 'Option1'
        }, {
          value: '2',
          label: 'Option2'
        }, {
          value: '3',
          label: 'Option3'
        }, {
          value: '4',
          label: 'Option4'
        }, {
          value: '5',
          label: 'Option5'
        }],
        value: ''
      }
    }
  }
</script>
```

And the result you can see here

![image](https://user-images.githubusercontent.com/15975785/100416031-70d42880-30b8-11eb-941a-731c4ddc4458.png)

So the bug must be happened here:
```
            getProvince() {
                return `provinceName_${this.$i18n.locale}`;
            },
```

Which causes `item[getProvince]` evaluating unexpected value back to the binding.

Try this in `onMounted`:

```ts
mounted() {
  console.log(this.provinces[0][getProvince])
}
```
see what you got

**Comment by JeremyWuuuuu** [comment] 2020-11-27 06:04
Also one thing that I wanted to mention is that, `vue-i18n` is not fully integrated into `ElementPlus` yet. See #608 for more information.

**Comment by ntgraph** [comment] 2020-11-27 13:51
Thanks for your collaboration, by reading your comment, I remove the vue-i18n, hence the getProvince and bind the options directly with provinceName_en.  It is still not display correctly.

``` <el-select v-model="city.province_id" :placeholder="$t('city.selectProvince')" class="w-full administration" :disabled="!city.country_id">
                    <el-option
                        v-for="item in provinces"
                        :key="`province-${item.id}`"
                        :label="item.provinceName_en"
                        :value="item.id">
<!--                        <span style="float: left" class="administration">{{ item[getProvince] }}</span>-->
                        <span style="float: left" class="administration">{{ item.provinceName_en }}</span>
                    </el-option>
                </el-select>
```
I also provide the city class here
```export default class City {
    constructor(id, country_id, province_id, cityName_en, cityName_fr, cityName_es)
    {
        this.id = id;
        this.country_id = country_id;
        this.province_id = province_id;
        this.cityName_en = cityName_en;
        this.cityName_fr = cityName_fr;
        this.cityName_es = cityName_es;
    }
}
```
unluckily, still not working.  
question on the side, how to paste code in here with nice formatting and color?
Thanks for your help

**Comment by JeremyWuuuuu** [comment] 2020-11-27 14:14
For formatting you can give hint to github via "```language" notation

**Comment by JeremyWuuuuu** [comment] 2020-11-27 14:16
Can you provide some sample of provinces? Doesn't have to be real data, sample will do. Let's get this solved.

**Comment by JeremyWuuuuu** [comment] 2020-11-27 14:28
With data option all members will be marked as reactive that's for sure

**Comment by ntgraph** [comment] 2020-11-27 14:28
![image](https://user-images.githubusercontent.com/7518854/100459036-c39ae980-3092-11eb-9128-616241c1d8e0.png)

here is what the fetch come to this.provinces

**Comment by JeremyWuuuuu** [comment] 2020-11-27 14:34
Got it I'll use that for testing

**Comment by JeremyWuuuuu** [comment] 2020-11-27 15:04
https://codesandbox.io/s/sad-dream-qmwws?file=/src/App.vue @ntgraph take a look at this

**Comment by JeremyWuuuuu** [comment] 2020-11-27 15:05
Seems everything is working fine on my testing data.

**Comment by ntgraph** [comment] 2020-11-27 15:09
I have described earlier if provinces is defined in data (provinces2), then it works.  But if provinces is coming from an api, it has certain delay, then it won't bind.

**Comment by JeremyWuuuuu** [comment] 2020-11-27 15:12
> I have described earlier if provinces is defined in data (provinces2), then it works. But if provinces is coming from an api, it has certain delay, then it won't bind.

Sorry I forgot that. I'll make an async one.

**Comment by JeremyWuuuuu** [comment] 2020-11-27 15:23
https://codesandbox.io/s/sad-dream-qmwws?file=/src/App.vue Right now it's set asynchronously

**Comment by ntgraph** [comment] 2020-11-27 15:59
I have tried the nexttick...
sandbox, select display select

**Comment by JeremyWuuuuu** [comment] 2020-11-27 17:01
> I have tried the nexttick...
> sandbox, select display select

What do you mean "select displays select'?
I don't get it

**Comment by JeremyWuuuuu** [comment] 2020-11-27 17:06
After I made this demo, I just realize that if the v-model you bind with does not match any value in that option group it won't get mapped because there were no value for it to map to. Also if you are fetching the data lazily, you might want the v-model that binds to it to be undefined or initialize it with the first value in that option group here in this case "provinces"

**Comment by ntgraph** [comment] 2020-11-27 19:49
Let me explain,
select v-model is linked to city.province_id.
at first, on created, fetchCity is called, it retrieve city from api, it contains city.province_id,
then it fetch provinces, so the options is fetch with provinces and selected value id match with the v-model from select.

I repeat that this same code works well in Vue2.6 and element-ui.

**Comment by ntgraph** [comment] 2020-11-27 19:55
the sandbox code display the placeholder text: select, not the value

**Comment by ntgraph** [comment] 2020-11-27 21:37
Unhandled error during execution of component event handler 
  at <ElSelect modelValue=2 onUpdate:modelValue=fn placeholder="Sélectionez une province/état..."  ... > 
  at <EditCity onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy {$i18n: {…}, $t: ƒ, $tc: ƒ, $te: ƒ, $d: ƒ, …}
 > > 
  at <RouterView> 
  at <DefaultLayout> 
  at <App>

**Comment by JeremyWuuuuu** [comment] 2020-11-28 01:20
I think I kinda got it. Correct me if I am wrong:
Before the provinces was fetched from the server, city was fetched and selected, which contains a `province_id` inside of the city object, so at this time, the value of v-model was set with the value `city.province_id`, then the options of province selector gets fetched and it should contains a value matches the `city.province_id` in your show case, but even when the provinces was fetched from the server and matches what you selected it doesn’t gets updated. Right?

**Comment by ntgraph** [comment] 2020-11-28 16:40
Yes, you are right on!

**Comment by JeremyWuuuuu** [comment] 2020-11-29 12:38
This could be a potential bug with `ElementPlus`, I think if the v2 version works fine for you then v3 version should work as well, I think your case is just as usual as the others so it should work as you expected, let me see what I can do to make it right.

**Comment by ntgraph** [comment] 2020-12-03 01:13
Hello,
is this fixed?  I download beta.2 it seems worst

**Comment by JeremyWuuuuu** [comment] 2020-12-03 01:16
> Hello,
> is this fixed? I download beta.2 it seems worst

nope the one I asked for the fix did not fix it, I will fix it today and will be released with beta.3

**Comment by JeremyWuuuuu** [comment] 2020-12-05 13:29
This shall be fixed in #808, you shall have no problem with version higher than `beta.4`

**Comment by ntgraph** [comment] 2020-12-05 14:37
Hi Jeremy, I have updated to beta.4
I have this error below
Cannot read property '0' of nul

**Comment by JeremyWuuuuu** [comment] 2020-12-05 14:39
Could you give me a screenshot or something?

**Comment by JeremyWuuuuu** [comment] 2020-12-05 14:40
Maybe detailed error massage with call stack would be very helpful

**Comment by ntgraph** [comment] 2020-12-05 14:43
![image](https://user-images.githubusercontent.com/7518854/101245908-00dc2880-36de-11eb-8a11-0aee98e994a8.png)
the select actually display placeholder text, and the options are empty

**Comment by JeremyWuuuuu** [comment] 2020-12-05 14:46
So these are the same code as you pasted here before right?

**Comment by JeremyWuuuuu** [comment] 2020-12-05 14:48
So I am going to take a look on what is really going on with this, and so sorry that this bug has been staled for so long, I will fix this ASAP

**Comment by JeremyWuuuuu** [comment] 2020-12-05 14:50
https://codesandbox.io/s/sad-dream-qmwws?file=/src/App.vue I reproduced this issue here, so it must be a bug, and this definitely had something to do with the bug fix in #808

**Comment by ntgraph** [comment] 2020-12-05 14:50
it is ok for the delay considering we are at the beginning of both Vue 3 and Element Plus, is it a problem of reactivity?  I hope one day Element Plus will become better and filled with interesting component.

**Comment by JeremyWuuuuu** [comment] 2020-12-05 14:52
> it is ok for the delay considering we are at the beginning of both Vue 3 and Element Plus, is it a problem of reactivity? I hope one day Element Plus will become better and filled with interesting component.

Thank you for being soooooo supportive, I am so glad that we have you as one of our users!

**Comment by ntgraph** [comment] 2020-12-05 15:09
Hi Jeremy,I have develop a project with Vue 2.6 and Element UI for 1 yr, still working on it, but in the meantime, I create a the same project in Vue 3 and Element Plus and hope to move view by view, but so far I am stumble on lots of bug.  I am and I can report bug for you in the future in Element Plus,  I wish I can ask or request new feature or component to make the library more rich.  
So far, I have seen Prime Vue 3 on primefaces.org which is a serious library as well, I don't know if you know them, if not, please have a look and see what Element plus can improve or add some new component.  I am still looking for mask in input, schedule in calendar, ripple effect in button and more in Element plus, so far I still can not localize since I use vue-i18n-next, awaiting development....  
I am glad you can help me.  I wish one day my project will hit the market based on more collaboration with you... 
Lap

    On Saturday, December 5, 2020, 09:52:13 AM EST, jeremywu <notifications@github.com> wrote:  
 
 



it is ok for the delay considering we are at the beginning of both Vue 3 and Element Plus, is it a problem of reactivity? I hope one day Element Plus will become better and filled with interesting component.


Thank you for being soooooo supportive, I am so glad that we have you as one of our users!

**Comment by JeremyWuuuuu** [comment] 2020-12-05 15:20
Sure, agreed, we as developers also wants this project to thrive, and I will have a look on the website you left here. 
Also for i18n issues I am going to ask @zazzaz to follow this up, you might need to open another issue for tracking that.

**Comment by zazzaz** [comment] 2020-12-05 16:14
Yes, we will support vue-i18n-next soon after it's first rc release I hope

**Comment by SimonaliaChen** [comment] 2020-12-05 17:07
> https://codesandbox.io/s/sad-dream-qmwws?file=/src/App.vue I reproduced this issue here, so it must be a bug, and this definitely had something to do with the bug fix in #808

@ntgraph Hi, I found that this broken might be related to vue version. Check [this](https://codesandbox.io/s/holy-snowflake-3pjyu?file=/src/App.vue) out, vue@3.0.3 works all fine, but vue@3.0.4 doesn't. Could you check the vue version in your project and try again? I will continue to investigate the error.

**Comment by JeremyWuuuuu** [comment] 2020-12-06 03:49
We just found out this is a bug of `Vue` its own. Check this out: 
https://github.com/vuejs/vue-next/issues/2737
And they've had a fix for that, so that we will have to wait until the next release gets published.
FYI: https://github.com/vuejs/vue-next/commit/c59897c7b0dbd82b5bbf3fbca945c0639ac37fb8

**Comment by JeremyWuuuuu** [comment] 2020-12-06 03:51
Closing since its a bug related to `Vue`

**Closed by JeremyWuuuuu** 2020-12-06 03:51 UTC
