### ISSUE TITLE
[Bug Report] Pagination "total" element display error

### ISSUE THREAD

**Issue by Sourgrapes42** [element-plus/element-plus#4764] opened 2021-12-10 07:32 UTC
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Windows 10/Chrome 96

### Vue version
3.2.24

### Reproduction Link
https://jsfiddle.net/5c9g8Lab/3/

### Steps to reproduce
Any pagination use "total".

It also happens in [Element homepage](https://element-plus.gitee.io/en-US/component/pagination.html#more-elements)

### What is Expected?
show total number like "Total 100"

### What is actually happening?
show "Total {total}"

**Comment by bytrix** [comment] 2021-12-10 07:47
same problem!!

**Comment by emojiiii** [comment] 2021-12-10 08:04
Duplicate of #4617. Fix in #4619

**Closed by emojiiii** 2021-12-10 08:04 UTC
