### ISSUE TITLE
[Bug Report] [el-pagination] {total} was not replaced

### ISSUE THREAD

**Issue by namepain** [element-plus/element-plus#4673] opened 2021-12-05 13:16 UTC
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
win / chrome 94.0.4606.54

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/namepain/pen/PoJPMwE

### Steps to reproduce
1. use el-pagination
2. {total} was not replaced by real value

### What is Expected?
{total} was not replaced by real value

### What is actually happening?
The 1.2.0-beta.5 version foget to replace /\{(\w )\}/g in use-locale hook, see
 https://github.com/element-plus/element-plus/blob/1.2.0-beta.4/packages/hooks/use-locale/index.ts#L80 
and
 https://github.com/element-plus/element-plus/blob/1.2.0-beta.5/packages/hooks/use-locale/index.ts#L64

**Comment by emojiiii** [comment] 2021-12-05 14:41
Duplicate of #4617. Fix in #4619

**Comment by lefengpiaoling** [comment] 2021-12-06 16:26
I can`t show total, it is real english, I want it is Number. why? I` am chinese, can you tell me why in chinese?

**Comment by emojiiii** [comment] 2021-12-07 00:23
简单描述，在调用国际化函数时，没有对`total`内的`{total}`进行替换，导致出现这种情况

**Comment by lefengpiaoling** [comment] 2021-12-07 01:00
你能告诉我解决方案吗

---Original---
From: ***@***.***&gt;
Date: Tue, Dec 7, 2021 08:24 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [element-plus/element-plus] [Bug Report] [el-pagination] {total}was not replaced (Issue #4673)




 
简单描述，在调用国际化函数时，没有对total内的{total}进行替换，导致出现这种情况

**Comment by emojiiii** [comment] 2021-12-07 01:01
等下一个版本更新，这个问题会被修复的

**Closed** 2021-12-09 14:54 UTC
