### ISSUE TITLE
[Bug Report] El-tooltip and Vue-fontawesome use are not correctly

### ISSUE THREAD

**Issue by mknightoy** [element-plus/element-plus#5465] opened 2022-01-18 09:21 UTC
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
Microsoft Edge Version 97.0.1072.62

### Vue version
3.2.27

### Reproduction Link
https://codesandbox.io/s/element-plus-issue-3ey4l

### Steps to reproduce
When only 'vue-fontawesome' is used, the tooltip cannot be triggered.
But version in 1.3.0-beta.1 is correctly.

### What is Expected?
Display correctly

### What is actually happening?
Not displayed

**Comment by emojiiii** [comment] 2022-02-16 08:04
Duplicate of #6086

**Closed** 2022-02-16 08:04 UTC
Labels: bug, has workaround, Component: Tooltip
