### ISSUE TITLE
[Component] [icon] 如果服务器返回的是el-icon-xxx形式的类图标,而<el-icon><xxx /></el-icon>该如何渲染服务器返回的el-icon-xxx

### ISSUE THREAD

**Issue by raochongmou** [element-plus/element-plus#11386] opened 2023-02-01 15:09 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Chrome  108.0.5359.125`
- Build Tool: `Vite`

### Related Component

- `el-icon`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/issues)

**Comment by btea** [comment] 2023-02-03 05:48
Duplicate of #11399

**Closed** 2023-02-03 05:48 UTC

**Comment by acyza** [comment] 2023-02-03 06:40
一个不太靠谱的方案[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaWNvbj5cbiAgXHQ8Y29tcG9uZW50IDppcz1cImljb25cIi8+XG4gIDwvZWwtaWNvbj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuICBpbXBvcnQgeyBzaGFsbG93UmVmIH0gZnJvbSAndnVlJ1xuXHRpbXBvcnQgKiBhcyBpY29ucyBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbiAgY29uc3QgaWNvbiA9IHNoYWxsb3dSZWYoKVxuICBmdW5jdGlvbiBzZXRJY29uKGNsYXNzTmFtZTpzdHJpbmcpe1xuICAgIGxldCBuYW1lID0gY2xhc3NOYW1lLm1hdGNoKC8oPzw9XmVsLWljb24tKS4qLylbMF1cbiAgIFx0bmFtZSA9IG5hbWUucmVwbGFjZSgvXi4vLG5hbWVbMF0udG9VcHBlckNhc2UoKSlcbiAgICBjb25zb2xlLmxvZyhuYW1lKVxuICBcdGljb24udmFsdWU9aWNvbnNbbmFtZV1cbiAgfVxuICBcbiAgXG4gIHNldEljb24oXCJlbC1pY29uLWRlbGV0ZVwiKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
