### ISSUE TITLE
[bug report] tree table with fixed columns causes inconsistency between mouse row and highlighted row

### ISSUE THREAD

**Issue by AdolphLv** [element-plus/element-plus#2427] opened 2021-07-02 17:26 UTC
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
Google Chrome 92.0.4512.6

### Vue version
3.1.4

### Reproduction Link
jsfiddle/codepen/codesandbox

### Steps to reproduce
按照以下示例，鼠标移至第第二行，但是实际高亮的是第一行

### What is Expected?
在树形表格中，也能实现固定行功能操作

### What is actually happening?
按照以下示例，鼠标移至第第二行，但是实际高亮的是第一行。关键在于 “操作”列中的fixed="right"属性，去除时鼠标移动和高亮行一致，加上就会出现这个问题

```VUE
<template>
  <div>
    <el-table
        :data="tableData"
        style="width: 100%;margin-bottom: 20px;"
        row-key="id"
        border
        default-expand-all
        :tree-props="{children: 'children', hasChildren: 'hasChildren'}">
      <el-table-column
          prop="date"
          label="日期"
          sortable
          width="180">
      </el-table-column>
      <el-table-column
          prop="name"
          label="姓名"
          sortable
          width="180">
      </el-table-column>
      <el-table-column
          prop="address"
          label="地址">
      </el-table-column>
      <el-table-column
          fixed="right"
          label="操作">
        <template #default="scope">
          <el-button
              size="mini"
              @click="handleEdit(scope.$index, scope.row)">编辑</el-button>
          <el-button
              size="mini"
              type="danger"
              @click="handleDelete(scope.$index, scope.row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      tableData: [{
        id: 1,
        date: '2016-05-02',
        name: '王小虎',
        address: '上海市普陀区金沙江路 1518 弄'
      }, {
        id: 2,
        date: '2016-05-04',
        name: '王小虎',
        address: '上海市普陀区金沙江路 1517 弄'
      }, {
        id: 3,
        date: '2016-05-01',
        name: '王小虎',
        address: '上海市普陀区金沙江路 1519 弄',
        children: [{
          id: 31,
          date: '2016-05-01',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1519 弄'
        }, {
          id: 32,
          date: '2016-05-01',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1519 弄'
        }]
      }, {
        id: 4,
        date: '2016-05-03',
        name: '王小虎',
        address: '上海市普陀区金沙江路 1516 弄'
      }]
    }
  }
}
</script>
```

### image
![图片20210703012513](https://user-images.githubusercontent.com/35337924/124309668-aa649900-db9d-11eb-8725-73bf811b019f.png)

**Comment by msidolphin** [comment] 2021-07-03 01:50
https://user-images.githubusercontent.com/26672484/124339891-fcc8a880-dbe3-11eb-9e47-7c5e18877a88.mp4

cannot reproduce.

**Comment by msidolphin** [comment] 2021-07-15 11:09
I'll close the issue and you can open it again or reopen an issue if you can reproduce it.

**Closed by msidolphin** 2021-07-15 11:09 UTC
Labels: 🤔 need reproduce
