### ISSUE TITLE
[bug report] the slider lacks index.d.ts, resulting in import failure

### ISSUE THREAD

**Issue by SmallSample** [element-plus/element-plus#4313] opened 2021-11-09 03:18 UTC
### Element Plus version
1.2.0-beta.2

### OS/Browsers version
window/chrome95

### Vue version
3.2.21

### Reproduction Link
https://github.com/SmallSample/demo

### Steps to reproduce
1.导入el-slider组件

### What is Expected?
引用正常

### What is actually happening?
引用失败

**Comment by sxzz** [comment] 2021-11-30 22:53
Duplicate of #4531

**Comment by sxzz** [comment] 2021-11-30 22:53
Waiting for vuejs/vue-next#5026

**Closed by sxzz** 2021-11-30 22:53 UTC
Labels: type related
