### ISSUE TITLE
"export 'popScopeId' (imported as 'te') was not found in 'vue'

### ISSUE THREAD

**Issue by CloudWoR** [element-plus/element-plus#1700] opened 2021-03-27 09:20 UTC
https://elementui.github.io/issue-generator/#/zh-CN?repo=element-plus
使用vue3引入element-plus后出现警告
 WARNING  Compiled with 3 warnings                              17:09:47
 warning  in ./node_modules/element-plus/lib/index.esm.js

"export 'popScopeId' (imported as 'te') was not found in 'vue'

 warning  in ./node_modules/element-plus/lib/index.esm.js

"export 'pushScopeId' (imported as 'ee') was not found in 'vue'

 warning  in ./node_modules/element-plus/lib/index.esm.js

"export 'withScopeId' (imported as 'le') was not found in 'vue'

同时报错:
Uncaught TypeError: Object(...) is not a function
    at eval (webpack-internal:///./node_modules/element-plus/lib/index.esm.js:142)
    at Module../node_modules/element-plus/lib/index.esm.js (chunk-vendors.js:2004)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (webpack-internal:///./src/main.ts:13)
    at Module../src/main.ts (app.js:1217)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at Object.1 (app.js:1278)
    at __webpack_require__ (app.js:854)

**Comment by AubSs** [comment] 2021-03-27 09:32
Same here
(vite & vue-cli are affected)

**Comment by zyxm5** [comment] 2021-03-27 09:37
Me too

**Comment by AubSs** [comment] 2021-03-27 09:38
If you need 'reproductible exemple'
=> https://github.com/element-plus/element-plus-starter
Then follow guide and watch.

**Comment by CloudWoR** [comment] 2021-03-27 09:41
sorry, I don't quite understand... @AubSs

**Comment by 1024-div** [comment] 2021-03-27 09:44
出现同样错误

**Comment by CloudWoR** [comment] 2021-03-27 09:46
There may be a problem with the latest version

**Comment by AubSs** [comment] 2021-03-27 09:55
@CloudWoR If you need to reproduce the bug, create a new project from
Vue-cli - https://github.com/element-plus/element-plus-starter
or
Vite - https://github.com/element-plus/element-plus-vite-starter

and you will get the error

**Comment by AubSs** [comment] 2021-03-27 10:01
And if that helps, I've been investigating since our CI failed and my team surprisingly hangs on it. It looks like the latest @vue/compiler-sfc pushed last night, remove / disrupt these 3 methods popScopeId / pushScopeId / withScopeId

**Comment by CloudWoR** [comment] 2021-03-27 10:04
@AubSs Yes, I just found that element plus references vue3.0.7, but 12 hours ago, Vue pushed version 3.0.8. After I reduced the Vue version to 3.0.7, two warnings disappeared, and this one was left: "export 'setscopeid' (imported as')_ setScopeId') was not found in 'vue'"

**Comment by AubSs** [comment] 2021-03-27 10:09
@CloudWoR downgrade vue and @vue/compiler-sfc to 3.0.7
then it should work

**Comment by JeremyWuuuuu** [comment] 2021-03-27 10:12
Sorry guys, you need to downgrade to vue `3.0.7` to make it work since vue has changed their internal implementation on `scoped` feature, we will release a new version to cope with that.

**Comment by CloudWoR** [comment] 2021-03-27 10:13
It's solved!
First, fix the version of Vue and @vue/compiler-sfc to 3.0.7, and move @ Vue / compiler-sfc to dependencies.
`  "dependencies": {
    "@types/vue": "^2.0.0",
    "core-js": "^3.6.5",
    "element-plus": "1.0.2-beta.35",
    "vue": "3.0.7",
    "@vue/compiler-sfc": "3.0.7",
    "vue-router": "^4.0.0-0"
  },`

**Comment by CloudWoR** [comment] 2021-03-27 10:14
@JeremyWuuuuu thanks

**Comment by JeremyWuuuuu** [comment] 2021-03-27 10:14
Since we will not be notified every time they change something internally we can only 

> It's solved!
> First, fix the version of Vue and @vue/compiler-sfc to 3.0.7, and move @ Vue / compiler-sfc to dependencies.
> ` "dependencies": { "@types/vue": "^2.0.0", "core-js": "^3.6.5", "element-plus": "1.0.2-beta.35", "vue": "3.0.7", "@vue/compiler-sfc": "3.0.7", "vue-router": "^4.0.0-0" },`

It seems not a good solution since they must have changed the logic with `vue` itself, so it is not suggested to do it this way you might encounter other bugs.

**Comment by AubSs** [comment] 2021-03-27 10:16
@JeremyWuuuuu thanks you.
It's unbelievable to have Breaking changes like that on a minor version.

**Comment by JeremyWuuuuu** [comment] 2021-03-27 10:17
> @JeremyWuuuuu thanks you.
> It's unbelievable to have Breaking changes like that on a minor version.

They have done this like several times with `event emit` in `3.0.3`, and `3.0.6` we constantly getting bug reports because of their breaking changes, anyway, we will make sure this is fixed in the next release, please stick with `3.0.7` for now. Sorry for the inconvenience.

**Comment by CloudWoR** [comment] 2021-03-27 10:18
@JeremyWuuuuu I fix the version of @vue/compiler-sfc to 3.0.7，Because when installing this module, there is a warning. You need to move to dependencies...

**Comment by JeremyWuuuuu** [comment] 2021-03-27 10:23
> @JeremyWuuuuu I fix the version of @vue/compiler-sfc to 3.0.7，Because when installing this module, there is a warning. You need to move to dependencies...

Downgrade `vue` back to `v3.0.7` will also downgrade the compilers to version `3.0.7`, if you do define their versions independently you might encounter some weird bug.
We will make sure the release rolled out before 29th March 00:00 GMT+8.

**Comment by CloudWoR** [comment] 2021-03-27 10:26
OK, I can Wait...

**Comment by CloudWoR** [comment] 2021-03-27 10:26
@JeremyWuuuuu  thanks

**Closed** 2021-03-27 10:47 UTC
Labels: enhancement, 🔨 Vue bug

**Comment by JeremyWuuuuu** [comment] 2021-03-27 10:50
@CloudWoR I will fix it ASAP.

**Comment by linqian02** [comment] 2021-03-27 15:02
me to ！！！ 
This warning came out of a reload today！

**Comment by JeremyWuuuuu** [comment] 2021-03-28 05:05
cc @linqian02  @AubSs @CloudWoR 
New release process has begun, refer to the links below to get updated.
Again, thank you for reporting the issue.
BTW, you can upgrade to Vue 3.0.9 to fix this issue.
https://github.com/element-plus/element-plus/actions/runs/694362910
https://github.com/element-plus/element-plus/releases/tag/1.0.2-beta.36

**Comment by JeremyWuuuuu** [comment] 2021-03-28 05:06
loop @1024-div @zyxm5 in
