### ISSUE TITLE
[Bug Report] ElSilder and ElAffix cannot import components on demand

### ISSUE THREAD

**Issue by shiwuhao** [element-plus/element-plus#4560] opened 2021-11-28 13:19 UTC
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
any

### Vue version
3.2.23

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
import {ElSlider, ELAffix} from 'element-plus'
按需导入无法导入组件， Cannot resolve symbol 'ElSlider' ,'ElAffix' 

### What is Expected?
按需导入能正常导入组件

### What is actually happening?
node_modules/element-plus/es/components/afix/,node_modules/element-plus/es/components/slider/
目录下没有index.d.ts

**Comment by autodocking** [comment] 2021-11-28 13:44
typescript 提示 '"element-plus"' has no exported member named 'ElSlider'和  'ElAffix'，build 时会失败。

另外当 tsconfig.json 中  "skipLibCheck": false 时，报错比1.2.0-beta.3版又多了不少。

**Comment by shiwuhao** [comment] 2021-11-29 06:47
当使用unplugin-vue-components按需加载时，使用<component>动态渲染组件，ElSilder无法正常渲染
app.vue
`
<template>
  <div>
    <component :is="ElInput" v-model="slider"></component>
    <component :is="ElSlider" v-model="slider"></component>
  </div>
</template>

<script setup lang="ts">
import {ref} from "vue";
import {ElSlider, ElInput} from 'element-plus'

const slider = ref();

</script>
</script>

`
vite.config.ts
`
import path from "path";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

import Components from "unplugin-vue-components/vite";
import { ElementPlusResolver } from "unplugin-vue-components/resolvers";


// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      "~/": `${path.resolve(__dirname, "src")}/`,
    },
  },
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: `@use "~/styles/element/index.scss" as *;`,
      },
    },
  },
  plugins: [
    vue(),
    Components({
      resolvers: [
        ElementPlusResolver({
          importStyle: "sass",
        }),
      ],
    }),
  ],
});

`

**Comment by emojiiii** [comment] 2021-11-29 08:17
@sxzz cc

**Comment by emojiiii** [comment] 2021-11-29 09:24
there is a temporary solution, please add a global type file
```typescript
export declare type SFCWithInstall<T> = T & import("vue").Plugin;

declare module 'element-plus' {
  export const ElAffix: SFCWithInstall<import("vue").DefineComponent<{
    readonly zIndex: import("element-plus/es/utils/props").BuildPropReturn<import("element-plus/es/utils/props").PropWrapper<import("csstype").ZIndexProperty>, 100, unknown, unknown, unknown>;
    readonly target: import("element-plus/es/utils/props").BuildPropReturn<StringConstructor, "", unknown, unknown, unknown>;
    readonly offset: import("element-plus/es/utils/props").BuildPropReturn<NumberConstructor, 0, unknown, unknown, unknown>;
    readonly position: import("element-plus/es/utils/props").BuildPropReturn<StringConstructor, "top", unknown, "top" | "bottom", unknown>;
  }, {
    root: import("@vue/reactivity").ShallowRef<HTMLDivElement | undefined>;
    state: {
        fixed: boolean;
        height: number;
        width: number;
        scrollTop: number;
        clientHeight: number;
        transform: number;
    };
    rootStyle: import("vue").ComputedRef<CSSProperties>;
    affixStyle: import("vue").ComputedRef<CSSProperties | undefined>;
    update: () => void;
  }, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
    scroll: ({ scrollTop, fixed }: {
        scrollTop: number;
        fixed: boolean;
    }) => boolean;
    change: (fixed: boolean) => boolean;
  }, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<{
    readonly zIndex?: unknown;
    readonly target?: unknown;
    readonly offset?: unknown;
    readonly position?: unknown;
  } & {
    zIndex: import("element-plus/es/utils/props").BuildPropType<import("element-plus/es/utils/props").PropWrapper<number>, unknown, unknown>;
    target: string;
    offset: number;
    position: import("element-plus/es/utils/props").BuildPropType<StringConstructor, "top" | "bottom", unknown>;
  } & {}> & {
    onChange?: ((fixed: boolean) => any) | undefined;
    onScroll?: ((args_0: {
        scrollTop: number;
        fixed: boolean;
    }) => any) | undefined;
  }, {
    zIndex: import("element-plus/es/utils/props").BuildPropType<import("element-plus/es/utils/props").PropWrapper<number>, unknown, unknown>;
    target: string;
    offset: number;
    position: import("element-plus/es/utils/props").BuildPropType<StringConstructor, "top" | "bottom", unknown>;
  }>>
}
```

**Comment by sxzz** [comment] 2021-11-30 22:49
Waiting for https://github.com/vuejs/vue-next/pull/5026

**Comment by sxzz** [comment] 2021-11-30 22:52
Duplicate of #4531

**Closed by sxzz** 2021-11-30 22:52 UTC
Labels: type related, 🔨 Vue issue
