### ISSUE TITLE
The value of the data column in the table component cannot be displayed when it is of bool type

### ISSUE THREAD

**Issue by wzohxia** [element-plus/element-plus#1036] opened 2020-12-18 03:17 UTC
```
<template>
  <el-table :data="tableData" style="width: 100%">
    <el-table-column prop="date" label="日期" width="180"> </el-table-column>
    <el-table-column prop="name" label="姓名" width="180"> </el-table-column>
    <el-table-column prop="address" label="地址"> </el-table-column>
  </el-table>
</template>
<script lang="ts">
import { computed, defineComponent, reactive, toRef, toRefs } from 'vue'
export default defineComponent({
  setup() {
    const info = reactive({
      tableData: [
        { date: '2016-05-02', name: '王小虎', address: true },
        { date: '2016-05-02', name: '王小虎', address: true },
        { date: '2016-05-02', name: '王小虎', address: true }
      ]
    })

    return {
      ...toRefs(info)
    }
  }
})
</script>
```
![image](https://user-images.githubusercontent.com/22089141/102570564-976b0980-4122-11eb-8166-4a109444e22a.png)

**Comment by JeremyWuuuuu** [comment] 2020-12-18 03:20
Why should we display bool type? I think the data in the table is essentially `string` or `img` sometimes.

**Comment by JeremyWuuuuu** [comment] 2020-12-18 03:21
If you need a bool type, you might need to cast it into `string` type.

**Comment by wzohxia** [comment] 2020-12-18 03:22
> Why should we display bool type? I think the data in the table is essentially `string` or `img` sometimes.

只是测试发现有这个问题，实际使用影响不大

**Comment by JeremyWuuuuu** [comment] 2020-12-21 02:47
Closing since this is expected behavior. Update the document later.

**Closed by JeremyWuuuuu** 2020-12-21 02:47 UTC
