### ISSUE TITLE
[Component] "[Vue warn] Write operation failed: computed value is readonly" in packages/hooks/use-empty-values/index.ts:31

### ISSUE THREAD

**Issue by MonkeyMaster** [element-plus/element-plus#16580] opened 2024-04-19 04:24 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.23`
- Element Plus Version: `2.7.0`
- Browser / OS: `any`
- Build Tool: `Webpack`

### Related Component

- `el-select`
- `el-time-picker`
- `el-date-picker`
- `el-tree-select`
- `el-select-v2`

### Reproduction Link

[Link]()

### Steps to reproduce

This happens only with Vue DEV build - vue.global.js, so I can't reproduce it at https://element-plus.run/

Any component affected in https://github.com/element-plus/element-plus/pull/16361 outputs in browser console:
```
[Vue warn] Write operation failed: computed value is readonly
```
in packages/hooks/use-empty-values/index.ts:31
```
  const config = useGlobalConfig()
  config.value = config.value || {}
```
![изображение](https://github.com/element-plus/element-plus/assets/1491688/82eecb25-ce50-4d67-b8b9-841e02f1ca41)

### What is Expected?

no console warnings

### What is actually happening?

console warnings

### Additional comments

_(empty)_

**Comment by btea** [comment] 2024-04-19 06:30
Duplicate of #16571

**Closed** 2024-04-19 06:30 UTC
