### ISSUE TITLE
Vite 安装 element-plus新建一个组件使用Rende渲染 el-button失败

### ISSUE THREAD

**Issue by huoyuhao** [element-plus/element-plus#1599] opened 2021-03-09 08:52 UTC
全局引入：
```
import { createApp } from 'vue';
import ElementPlus from 'element-plus';
import '@/assets/css/element-variables.scss';
import App from './App.vue';
const app = createApp(App);
app.use(ElementPlus, { size: 'small', zIndex: 3000 });
app.mount('#app');
```
父组件
```
<template>
  <d-expand :render="render"/>
</template>
<script lang="js">
import DExpand from '@/components/expand.jsx';
export default {
  components: {
    DExpand,  },
  setup () {
    return {
       render: (h) => {
         h('el-button', 'test');
       }
    }
}
```
子组件
```
import { defineComponent, h } from 'vue'
export default defineComponent({
  name: 'DExpand',
  functional: true,
  props: {
    render: Function,
  },
  setup(props, { slots, attrs, emit }) {
    return () => {
      return props.render(h)
    }
  },
});
```

**Comment by JeremyWuuuuu** [comment] 2021-03-11 12:55
`h` function cannot render `el-button` as string, you either use it with [`Vue.resolveComponent`](https://v3.vuejs.org/api/global-api.html#resolvecomponent) checkout the documentation, or you can do something like this:
```ts
import { h } from 'vue'
import { ElButton } from 'element-plus'

// ... omit code

h(Elbutton, ...props);

```

**Comment by JeremyWuuuuu** [comment] 2021-03-11 12:57
Even though you think that you have registered your component globally but you have to tell `Vue` what the actual rendering component is, `h` method **WILL NOT LOOK UP FOR COMPONENTS**, make sure the components was passed in `object` instead of `string`, it only recognize html tag string like `span` `div`.

**Comment by JeremyWuuuuu** [comment] 2021-03-11 12:59
Closing this issue since this is not an issue caused by component itself.

**Closed** 2021-03-11 12:58 UTC

**Comment by huoyuhao** [comment] 2021-03-19 08:12
thanks very much
