### ISSUE TITLE
[Bug Report] [Component] [dropdown] 点击下拉菜单项, 当弹出输入框时, 下拉菜单出现反复的隐藏和显示

### ISSUE THREAD

**Issue by 11039850** [element-plus/element-plus#7042] opened 2022-04-07 10:01 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome 99.0.4844.84`
- Build Tool: `Webpack`

### Related Component

- `el-dropdown`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZHJvcGRvd24gcGxhY2VtZW50PVwiYm90dG9tLWVuZFwiIDpoaWRlLW9uLWNsaWNrPVwidHJ1ZVwiICA6b2Zmc2V0PVwiMTVcIiBAY29tbWFuZD1cImhhbmRsZUFkZENvbW1hbmRcIj5cblx0XHRcdFx0XHRcdFx0XHRcdDxlbC1idXR0b24gcGxhaW4gaWNvbj1cInBsdXNcIj5hZGQ8L2VsLWJ1dHRvbj5cblxuXHRcdFx0XHRcdFx0XHRcdFx0PHRlbXBsYXRlICNkcm9wZG93bj5cblx0XHRcdFx0XHRcdFx0XHRcdFx0PGVsLWRyb3Bkb3duLW1lbnU+XG5cdFx0XHRcdFx0XHRcdFx0XHRcdFx0PGVsLWRyb3Bkb3duLWl0ZW0gaWNvbj1cImZvbGRlclwiICAgY29tbWFuZD1cImNyZWF0ZUZvbGRlclwiPiBGb2xkZXI8L2VsLWRyb3Bkb3duLWl0ZW0+XG5cdFx0XHRcdFx0XHRcdFx0XHRcdFx0PGVsLWRyb3Bkb3duLWl0ZW0gaWNvbj1cImRvY3VtZW50XCIgY29tbWFuZD1cImNyZWF0ZUZpbGVcIiAgPiBGaWxlPC9lbC1kcm9wZG93bi1pdGVtPlxuXHRcdFx0XHRcdFx0XHRcdFx0XHQ8L2VsLWRyb3Bkb3duLW1lbnU+XG5cdFx0XHRcdFx0XHRcdFx0XHQ8L3RlbXBsYXRlPlxuXHQ8L2VsLWRyb3Bkb3duPlx0XHRcdFx0XHRcdCBcblx0XHRcdFx0XHRcdFx0XHQgXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZSwgRWxNZXNzYWdlQm94LCBFbERyb3Bkb3duLCBFbEJ1dHRvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmNvbnN0IGhhbmRsZUFkZENvbW1hbmQgPSAoY21kKSA9PiB7XG4gIEVsTWVzc2FnZUJveCh7XG4gICAgdGl0bGU6ICdNZXNzYWdlJyxcbiAgICBtZXNzYWdlOiBoKCdwJywgbnVsbCwgW1xuICAgICAgaCgnc3BhbicsIG51bGwsICdNZXNzYWdlIGNhbiBiZSAnKSxcbiAgICAgIGgoJ2knLCB7IHN0eWxlOiAnY29sb3I6IHRlYWwnIH0sICdWTm9kZScpLFxuICAgIF0pLFxuICAgIHNob3dDYW5jZWxCdXR0b246IHRydWUsXG4gICAgY29uZmlybUJ1dHRvblRleHQ6ICdPSycsXG4gICAgY2FuY2VsQnV0dG9uVGV4dDogJ0NhbmNlbCcsXG4gICAgYmVmb3JlQ2xvc2U6IChhY3Rpb24sIGluc3RhbmNlLCBkb25lKSA9PiB7XG4gICAgICBpZiAoYWN0aW9uID09PSAnY29uZmlybScpIHtcbiAgICAgICAgaW5zdGFuY2UuY29uZmlybUJ1dHRvbkxvYWRpbmcgPSB0cnVlXG4gICAgICAgIGluc3RhbmNlLmNvbmZpcm1CdXR0b25UZXh0ID0gJ0xvYWRpbmcuLi4nXG4gICAgICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgICAgIGRvbmUoKVxuICAgICAgICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgICAgICAgaW5zdGFuY2UuY29uZmlybUJ1dHRvbkxvYWRpbmcgPSBmYWxzZVxuICAgICAgICAgIH0sIDMwMClcbiAgICAgICAgfSwgMzAwMClcbiAgICAgIH0gZWxzZSB7XG4gICAgICAgIGRvbmUoKVxuICAgICAgfVxuICAgIH0sXG4gIH0pLnRoZW4oKGFjdGlvbikgPT4ge1xuICAgIEVsTWVzc2FnZSh7XG4gICAgICB0eXBlOiAnaW5mbycsXG4gICAgICBtZXNzYWdlOiBgYWN0aW9uOiAke2FjdGlvbn1gLFxuICAgIH0pXG4gIH0pXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1. 点击"add"按钮, 出现下拉菜单[Folder, File]
2. 点击"Folder", 弹出输入对话框.

### What is Expected?

点击"Folder"按钮后, 弹出输入对话框, 此时下拉菜单应该立即隐藏.

### What is actually happening?

下拉菜单出现反复显示和隐藏, 鼠标移出下拉菜单的显示区域后, 下拉菜单正常隐藏. 

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/12879617/162174540-7e53f6a7-86a9-438c-859c-b6d038b1b94e.png)

**Comment by btea** [comment] 2022-04-07 12:21
Duplicate of #7006

**Closed** 2022-04-07 12:21 UTC
