### ISSUE TITLE
[Component] [input] input输入框输入的东西不能选中

### ISSUE THREAD

**Issue by zkc-China** [element-plus/element-plus#10551] opened 2022-11-10 03:24 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.44`
- Element Plus Version: `2.2.20`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input.html)

### Steps to reproduce

在输入框输入后一段文字后，ctrl+A，或者鼠标拖拽编辑的问题

### What is Expected?

能够选中

### What is actually happening?

不能选中

### Additional comments

_(empty)_

**Comment by init-qy** [comment] 2022-11-10 03:59
Duplicate of #10486

**Comment by chenxch** [comment] 2022-11-10 04:59
Try to search first before asking questions.

**Closed by chenxch** 2022-11-10 04:59 UTC
