### ISSUE TITLE
[Feature Request] The container can support changing the width or height by dragging

### ISSUE THREAD

**Issue by jayconscious** [element-plus/element-plus#3104] opened 2021-08-27 08:25 UTC
### Existing Component
Yes

### Component Name
Container or Other menthod

### Description
The container can support changing the width or height by dragging, Just like this example.
https://www.zhangxinxu.com/study/201903/css-idea/behavior-stretch.php?aside=0

**Comment by xiaoxian521** [comment] 2021-09-13 05:25
this is same: https://github.com/element-plus/element-plus/issues/3272

**Comment by sxzz** [comment] 2021-09-13 05:27
Duplicate of https://github.com/element-plus/element-plus/issues/3272

**Closed by sxzz** 2021-09-13 05:27 UTC
Labels: enhancement, pr welcomed
