### ISSUE TITLE
[Bug Report] Cascader can not add class attribute(Cascader添加class失败)

### ISSUE THREAD

**Issue by GuoJikun** [element-plus/element-plus#5367] opened 2022-01-13 07:43 UTC
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
win11 21H2（22000.434） Microsoft Edge 97.0.1072.55

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/jikunguo/project/details/XWzWmK

### Steps to reproduce
<el-cascader :options="options" class="test1" /> insert  test1 to class of Cascader（向组件Cascader增加class属性）

### What is Expected?
Cascader class includes test1(可以把test添加到组件Cascader的class属性中)

### What is actually happening?
class added failed(组件Cascader的class属性添加失败)

**Comment by emojiiii** [comment] 2022-01-13 07:47
Duplicate of #5331

**Closed** 2022-01-13 07:47 UTC
Labels: bug, Component: Cascader
