### ISSUE TITLE
element-plus/packages/table Vite ssr no rendering

### ISSUE THREAD

**Issue by vok123** [element-plus/element-plus#576] opened 2020-11-11 06:03 UTC
version: `element-plus@^1.0.1-alpha.14`;
description: Vite ssr `td` `th` tag no rendering;

**Comment by JeremyWuuuuu** [comment] 2020-11-11 06:06
cc @justwiner

**Comment by justwiner** [comment] 2020-11-11 07:28
Can you provide a git repository demo?pls. @vok123

**Comment by vok123** [comment] 2020-11-11 08:31
https://github.com/vok123/vue3-ts-vite-ssr-starter

**Comment by justwiner** [comment] 2020-11-13 10:51
sry, the latest is delayed because of something. 
I ran your demo just now, I found that this is not a problem with `element-plus`.The problem is that the interface for obtaining table data is not working properly.
![image](https://user-images.githubusercontent.com/30335393/99064335-bdd6db80-259d-11eb-9129-8077f9f1df6a.png)
I have provided mock data for your table, and the table component can work normally.
```
computed: {
    fruitList() {
      // return this.$store.state.market.fruitList;
      return [
        {
          id: 1,
          name:"111",
          price: 20
        }
      ];
    }
  }
```
![image](https://user-images.githubusercontent.com/30335393/99064513-f24a9780-259d-11eb-868c-93cddf1f48d0.png)


I think my answer has solved your problem, so I will close this issue, and any follow-up discussions can be discussed under this issue. 

Thanks.

**Comment by justwiner** [comment] 2020-11-13 11:52
You can close this issue, it is not caused by `element-plus`
@JeremyWuuuuu

**Comment by vok123** [comment] 2020-11-14 06:53
还是有问题的, 你上面写的不是异步的数据, 当数据异步的时候就有问题了, el-table依旧不渲染数据, 原生的table确是可以的
`
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Market',
  data() {
    return {
      fruitList: [] as any[]
    };
  },
  serverPrefetch() {
    return new Promise(resolve => {
      setTimeout(() => {
        this.fruitList = [{
          id: 1,
          name:"111",
          price: 20
        }];
        resolve();
      }, 2000);
    });
  }
});
`

**Comment by justwiner** [comment] 2020-11-14 07:31
@vok123 
Your `serverPrefetch` is not called, i think `fruitList` is still `[]`
and this is my code:
```
<script lang="ts">
import { ref } from 'vue';
import { defineComponent } from 'vue';

function serverPrefetch(): Promise<any[]> {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve([{
        id: 1,
        name:"111",
        price: 20
      }]);
    }, 2000);
  });
}

export default defineComponent({
  name: 'Market',
  setup() {
    const fruitList = ref<any[]>([]);
    serverPrefetch().then(data => {
      fruitList.value = data;
    });
    return {
      fruitList
    };
  }
});
</script>
```
This code is a normal asynchronous request for data, and it runs as expected.

**Comment by vok123** [comment] 2020-11-14 08:45
有运行的, 在server端. 在我的demo里面你把我上面的代码copy进去, 然后 `npm run test`.  启动服务之后右键查看网页源码, 你可以看到服务器端对`el-table`渲染的结果. 貌似你上面这个dome在server端应该是不适应的...

**Comment by justwiner** [comment] 2020-11-14 09:52
> 有运行的, 在server端. 在我的demo里面你把我上面的代码copy进去, 然后 `npm run test`. 启动服务之后右键查看网页源码, 你可以看到服务器端对`el-table`渲染的结果. 貌似你上面这个dome在server端应该是不适应的...
@vok123 
oh~,i get it.

Including `Input` components, etc. 
provide values for `Input`, and they will not be rendered into html tags on the `server-side`
like this:
```js
<template>
    <el-input v-model="inputValue" />
    <input :value="inputValue" type="text">
</template>
<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'User',
  data() {
    return {
        inputValue: 'some default'
    };
  }
});
</script>
```
Actually in `server-side`:
```
<head>
  <script type="module" src="bundle.js"></script>
</head>
<body>
  <input class="el-input__inner" tabindex aria-label data-v-5ef48958>
  <input value="some default" type="text"></div>
</body>
```

`element-plus` does not support `server-side` rendering for the time being. 
At present, the rendering code is build in js files.
If you want to support `server-side` rendering, you can mention `feature issue` or `PR`.

And you can `@JeremyWuuuuu` for this.

**Comment by vok123** [comment] 2020-11-14 10:00
o(╥﹏╥)o

**Comment by zazzaz** [comment] 2020-11-14 16:03
Element Plus support SSR from the very beginning the same as Element UI. If there a render error we will fix it for sure.

**Closed** 2020-12-07 07:24 UTC

**Comment by develar** [comment] 2021-06-26 10:18
SSR doesn't work for any component that uses `teleport`. So, el-input works, but el-select doesn't. I cannot find solution for now (https://stackoverflow.com/questions/67118665/how-to-make-teleport-work-in-ssr-in-vue3).

**Comment by develar** [comment] 2021-06-26 10:27
https://github.com/vuejs/vue-next/issues/2711#issuecomment-739790963
