### ISSUE TITLE
[Feature Request] When to add a large data volume virtual table

### ISSUE THREAD

**Issue by xinlinhua** [element-plus/element-plus#4445] opened 2021-11-18 07:45 UTC
### Existing Component
Yes

### Component Name
el-table

### Description
When to add a large data volume virtual table

**Comment by emojiiii** [comment] 2021-11-18 12:45
#3067

**Comment by sxzz** [comment] 2021-11-20 02:11
Duplicate of #3067

**Closed by sxzz** 2021-11-20 02:11 UTC
