### ISSUE TITLE
TSX 相关问题

### ISSUE THREAD

**Issue by Ttou** [element-plus/element-plus#787] opened 2020-12-02 09:31 UTC
版本：1.0.1-beta.14
说明：记录遇到的类型问题，**有些组件没有用 defineComponent 构建，引用时就会报错**
- [x] ElInput 的 placeholder 属性缺失
- [x] ElSubmenu 使用报错：JSX element type 'ElSubmenu' does not have any construct or call signatures
- [ ] ElForm 的 size 属性当前是 any，应该是 medium / small / mini
- [x] ElMenuItem 使用报错：JSX element type 'ElMenuItem' does not have any construct or call signatures

**Comment by Liiked** [comment] 2020-12-02 11:40
you may leave some **code** or **reproduction** method here to help us identify your question

**Comment by JeremyWuuuuu** [comment] 2020-12-03 01:22
Well, the placeholder thing is indeed some type mistaken that we have added yet, this will be fixed soon

**Comment by wangguanl** [comment] 2020-12-24 02:55
el-select 使用 jsx 根据数据动态渲染 el-option 时会报错，   有 jsx 版 el-select 的操作案例吗？ 难道我的打开方式不正确？

**Comment by JeremyWuuuuu** [comment] 2020-12-24 03:00
> el-select 使用 jsx 根据数据动态渲染 el-option 时会报错， 有 jsx 版 el-select 的操作案例吗？ 难道我的打开方式不正确？

No, it's bug from `Vue`, use v3.0.3 to avoid getting the error.

**Comment by JeremyWuuuuu** [comment] 2020-12-24 03:01
For more info see https://github.com/vuejs/vue-next/issues/2737

**Comment by JeremyWuuuuu** [comment] 2020-12-24 03:01
Also see #1041

**Comment by JeremyWuuuuu** [comment] 2020-12-24 03:04
I believe that these issue are fixed or at least partially fixed, can you verify that? @Ttou

**Comment by wangguanl** [comment] 2020-12-25 06:43
@JeremyWuuuuu 切换到指定版本确实解决了问题， 但是出现了警告： [Vue warn]: Extraneous non-emits event listeners (beforeEnter) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option.

**Comment by wangguanl** [comment] 2020-12-25 06:45
我仔细检查过上下文代码，确定使用 emits 注册了事件集。

**Comment by Ttou** [comment] 2020-12-25 09:20
> 我仔细检查过上下文代码，确定使用 emits 注册了事件集。

我试了下，没问题，用的是vite
```tsx
import { defineComponent, ref } from 'vue';
import { ElSelect, ElOption } from 'element-plus';

export default defineComponent({
    name: 'App',
    setup() {
        const options = ref([
            { label: 'a', value: '1' },
            { label: 'b', value: '2' }
        ])

        return () => (
            <div>
                <ElSelect>
                    {{
                        default: () => options.value.map(item => <ElOption label={item.label} value={item.value}></ElOption>)
                    }}
                </ElSelect>
            </div>
        )
    }
})
```

**Closed** 2021-01-05 01:12 UTC
Labels: bug, type related
