### ISSUE TITLE
[Feature Request] element-plus的源码下载下来如何打包为离线文档？

### ISSUE THREAD

**Issue by itboy7** [element-plus/element-plus#6308] opened 2022-02-27 01:39 UTC
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `N/A`

## Description

如何将下载下来的element-plus-dev打包为离线官网文档？

### Additional comments

_(empty)_

**Comment by sxzz** [comment] 2022-02-28 09:40
Duplicate of #6182 
Please refer to https://github.com/element-plus/element-plus/issues/6182#issuecomment-1046256082

**Closed by sxzz** 2022-02-28 09:40 UTC
