### ISSUE TITLE
[feature request] date selector V-model binding value formatting method

### ISSUE THREAD

**Issue by guagezuishuai** [element-plus/element-plus#1091] opened 2020-12-23 05:47 UTC
### Existing Component
Yes

### Component Name
DatePicker

### Description
现在返回值是个date格式，我希望能像element一样有个value-formatter来格式化返回值的格式

**Comment by zazzaz** [comment] 2020-12-23 05:50
Duplicate of #1068

https://github.com/element-plus/element-plus/issues/1068#issuecomment-748966501

**Closed by zazzaz** 2020-12-23 05:50 UTC

**Comment by iamkun** [comment] 2021-06-03 12:45
fixed in #2120
