### ISSUE TITLE
Checkbox value-key hope.

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#460] opened 2020-10-23 09:16 UTC
Doc has this sentence.
_If the binding value of Select is an object, make sure to assign value-key as its unique identity key name._
_如果 Select 的绑定值为对象类型，请务必指定 value-key 作为它的唯一性标识。_

When Checkbox bind object, it won't show back the value. So hope that checkbox also has value-key attribute.

**Comment by zazzaz** [comment] 2020-10-23 09:32
As far as I could see on the doc, `value-key` is used in `Select` component, not `Checkbox`, right?

**Comment by kooriookami** [comment] 2020-10-25 10:56
> As far as I could see on the doc, `value-key` is used in `Select` component, not `Checkbox`, right?

Yes. That's the problem.

**Comment by zazzaz** [comment] 2020-10-25 13:14
Then, what's the problem is? Do you mean you want to have this feature is Checkbox as well?

**Comment by kooriookami** [comment] 2020-10-25 13:58
> Then, what's the problem is? Do you mean you want to have this feature is Checkbox as well?

Yes. The checkboxes don't show back when type is object.
Look at this demo. https://okvhc.csb.app/
Click the button, and you will see the deep cloned object has not show back. So I hope checkbox can bind a value-key to make sure the show back value correctly.

**Comment by zazzaz** [comment] 2020-10-26 02:10
This comes to a new feature request then.

**Comment by JeremyWuuuuu** [comment] 2020-12-09 05:23
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new

**Closed by JeremyWuuuuu** 2020-12-09 05:23 UTC
Labels: enhancement
