### ISSUE TITLE
[bug report] the pagination component total will not be updated and will always be displayed as {total}

### ISSUE THREAD

**Issue by qq929323125** [element-plus/element-plus#4769] opened 2021-12-10 09:31 UTC
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
win10

### Vue version
3.2.24

### Reproduction Link
https://codepen.io/qq929323125/pen/YzrGWqO

### Steps to reproduce
引入 el-pagination 组件

### What is Expected?
显示正确的值

### What is actually happening?
显示的是 {total}

**Comment by emojiiii** [comment] 2021-12-10 09:32
Duplicate of #4617. Fix in #4619

**Closed** 2021-12-10 11:40 UTC
