### ISSUE TITLE
[Style] [input] el-input配置clearable后，清除图标的显示和隐藏会影响input框的宽度

### ISSUE THREAD

**Issue by qianxing123** [element-plus/element-plus#11436] opened 2023-02-07 03:21 UTC
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.29`
- Browser / OS: `Chrome 版本 109.0.5414.120（正式版本） （64 位）`
- Build Tool: `Webpack`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSBpbmxpbmU+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cImlucHV0XCI+ICAgICAgICAgIFxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiBjbGVhcmFibGU+PC9lbC1pbnB1dD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

<el-form inline>
    <el-form-item label="input">          
      <el-input v-model="msg" clearable></el-input>
    </el-form-item>
  </el-form>
1.el-form 配置inline属性
2.el-input配置clearable
3.给input输入文本
4.input聚焦失焦切换

### What is Expected?

鼠标移入input框，icon显示，输入框宽度不变

### What is actually happening?

鼠标移入input框，icon显示，输入框宽度变长

### Additional comments

_(empty)_

**Comment by acyza** [comment] 2023-02-07 04:27
duplicate #11370

**Comment by tolking** [comment] 2023-02-07 07:57
Duplicate of #7287

It is recommended to set the default width for Input component

**Closed by tolking** 2023-02-07 07:57 UTC
