### ISSUE TITLE
[Bug Report] When the table merges rows or columns in the zoom state, the header and content are misaligned

### ISSUE THREAD

**Issue by zeweilin1993** [element-plus/element-plus#1741] opened 2021-04-02 03:21 UTC
### Element Plus version
1.0.2-beta.31

### OS/Browsers version
Window10/Google Chrome 版本 89.0.4389.114（正式版本） （64 位）

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/linzw/pen/zYNZRGe

### Steps to reproduce
Set the zoom 125% under window10, the header display of the merged row or column will be misaligned with the content, and the display will be normal under 100%.

### What is Expected?
Any change of the zoom factor, the table display is normal.

### What is actually happening?
The table header and the content display misaligned.

**Comment by zeweilin1993** [comment] 2021-04-02 03:28
90%
![image](https://user-images.githubusercontent.com/39040618/113377292-7c0ccd00-93a6-11eb-91a3-051a01ae85ee.png)  

100%
![image](https://user-images.githubusercontent.com/39040618/113377240-541d6980-93a6-11eb-906a-09d6d3297fd5.png)  

110%  
![image](https://user-images.githubusercontent.com/39040618/113377283-74e5bf00-93a6-11eb-8baf-7cb64ea89f4f.png)

**Comment by justwiner** [comment] 2021-04-02 07:10
Duplicate of #1691

**Closed** 2021-04-12 02:56 UTC
Labels: duplicate
