### ISSUE TITLE
[TypeScript] [All] Error while requiring module @element-plus/nuxt: TypeError: _dayjs.default.extend is not a function

### ISSUE THREAD

**Issue by houko** [element-plus/element-plus#16543] opened 2024-04-17 02:41 UTC
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.0`
- Browser / OS: `macOS 14.0.1`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

install 
   "@element-plus/nuxt": "^1.0.8",
    "element-plus": "^2.7.0",

### What is Expected?

no error 

### What is actually happening?

Error while requiring module @element-plus/nuxt: TypeError: _dayjs.default.extend is not a function

### Additional comments

https://github.com/element-plus/element-plus/pull/8144

maybe 2.2.5 will be resolved, but still error now.

**Comment by btea** [comment] 2024-04-17 05:56
It is duplicated with #16512.

**Comment by houko** [comment] 2024-04-17 05:58
so it is a new bug for 2.7.0?

**Comment by btea** [comment] 2024-04-17 06:01
I haven't determined where the problem is yet. In a windows environment, 2.7.0 is also normal, but an error will occur when using wsl. 2.6.3 seems to be OK in all environments.

**Comment by houko** [comment] 2024-04-18 02:24
but `@element-plus/nuxt` default set element-plus to 2.7.0

![image](https://github.com/element-plus/element-plus/assets/12625278/b7eeb9db-82d3-4f5a-9672-0aa95c79b0a4)

**Comment by btea** [comment] 2024-04-18 02:29
You can refer to https://github.com/element-plus/element-plus-nuxt/issues/95#issuecomment-2060202765

**Comment by tolking** [comment] 2024-04-20 07:39
Fixed with @element-plus/nuxt to v1.0.9.

**Closed by tolking** 2024-04-20 07:39 UTC
