### ISSUE TITLE
[Bug Report] [Component] [input] 同时设置 后缀图标 和 显示清空按钮，文字溢出

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#6484] opened 2022-03-08 08:58 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `Edge Version 99.0.1150.30`
- Build Tool: `CDN`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEgSGVsbG8gV29ybGQhIEhlbGxvIFdvcmxkISBIZWxsbyBXb3JsZCEgSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuICA8ZWwtaWNvbj48VXNlciAvPjwvZWwtaWNvbj5cbiAgPGRpdiBzdHlsZT1cIndpZHRoOjMwMHB4O1wiPlxuICBcdDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgOnN1ZmZpeC1pY29uPVwiVXNlclwiIDpjbGVhcmFibGU9XCJ0cnVlXCIvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

让input获取焦点

### What is Expected?

字体不超出

### What is actually happening?

字体超出了

### Additional comments

![image](https://user-images.githubusercontent.com/50992790/157202780-5e79027a-06db-4f57-ad9b-99a753ee0e6a.png)

**Comment by Edric-Li** [comment] 2022-03-21 09:32
请问官方 这个bug会修么？

**Comment by sxzz** [comment] 2022-03-22 09:42
Duplicate of #6464

**Closed by sxzz** 2022-03-22 09:42 UTC
