### ISSUE TITLE
[Bug Report] [Style] [date-picker] Datepicker height different than DateRange

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#7622] opened 2022-05-10 12:39 UTC
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome (latest)`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/date-picker.html#enter-date)

### Steps to reproduce

you can see it in the documentation page as well

### What is Expected?

elements should have the same height

### What is actually happening?

different height

### Additional comments

_(empty)_

**Comment by plainheart** [comment] 2022-05-11 00:30
Duplicate of #7613. Fixed in #7608.

**Closed by plainheart** 2022-05-11 00:30 UTC
