### ISSUE TITLE
[Component] [input] InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('checkbox') does not support selection.

### ISSUE THREAD

**Issue by MonkeyMaster** [element-plus/element-plus#10601] opened 2022-11-14 11:29 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `Firefox 106 / Chrome 107`
- Build Tool: `Webpack`

### Related Component

- `el-input`

### Reproduction Link

[Link]()

### Steps to reproduce

After upgrade to 2.2.21 we started getting these errors from clients - a dozen today already on random pages:
```
InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('checkbox') does not support selection.
or
"InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('radio') does not support selection.
```
Stack points to ElFocusTrap. At the moment I'm trying to figure out how to reproduce it. Maybe someone can help

It's definitely related to https://github.com/element-plus/element-plus/commit/d72fd34b58632dc011749b9393d93e12a5e160d5 :
```
      if (element.tagName === 'INPUT') {
        element.setSelectionRange(element.value.length, element.value.length)
        return
      }
```

### What is Expected?

no js errors

### What is actually happening?

js error

### Additional comments

_(empty)_

**Comment by MonkeyMaster** [comment] 2022-11-15 03:41
```'select' in element``` is true for checkbox, please add check for setSelectionRange:
```
 if (element.tagName === 'INPUT' && 'setSelectionRange' in element) {
```

**Comment by asdjgfr** [comment] 2022-11-18 10:03
@tolking It's really a bug.

[Reproduction demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8YmxvY2txdW90ZT5cbiAgICA8c3Ryb25nPlxuICAgICAgU2VsZWN0IGFsbCBpdGVtcywgdGhlbiBtb3ZlIHRoZSBtb3VzZSBvdmVyIGRyb3Bkcm93biBsaXN0IHRvcCB0byBib3R0b20uXG4gICAgICBUaGVuIHlvdSBjYW4gc2VlIHRoZSBlcnJvciBpbiBjb25zb2xlLlxuICAgIDwvc3Ryb25nPlxuICA8L2Jsb2NrcXVvdGU+XG5cbiAgPGVsLWRyb3Bkb3duPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiA6ZGlzYWJsZWQ9XCJkaXNhYmxlZFwiPlxuICAgICAgRHJvcGRvd24gTGlzdDxlbC1pY29uIGNsYXNzPVwiZWwtaWNvbi0tcmlnaHRcIj48YXJyb3ctZG93biAvPjwvZWwtaWNvbj5cbiAgICA8L2VsLWJ1dHRvbj5cbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAxPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMjwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDM8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbiAgPGVsLXRhYmxlXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgIEBzZWxlY3Rpb24tY2hhbmdlPVwiaGFuZGxlU2VsZWN0aW9uQ2hhbmdlXCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIHdpZHRoPVwiNTVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBjb21wdXRlZCwgcmVhY3RpdmUgfSBmcm9tIFwidnVlXCI7XG5pbXBvcnQgeyBBcnJvd0Rvd24gfSBmcm9tIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjtcblxuY29uc3QgYXJyID0gcmVhY3RpdmUoW10pO1xuY29uc3QgZGlzYWJsZWQgPSBjb21wdXRlZCgoKSA9PiAhYXJyLmxlbmd0aCk7XG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiBcIjIwMTYtMDUtMDNcIixcbiAgICBuYW1lOiBcIlRvbVwiLFxuICAgIGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCIsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiBcIjIwMTYtMDUtMDJcIixcbiAgICBuYW1lOiBcIlRvbVwiLFxuICAgIGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCIsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiBcIjIwMTYtMDUtMDRcIixcbiAgICBuYW1lOiBcIlRvbVwiLFxuICAgIGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCIsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiBcIjIwMTYtMDUtMDFcIixcbiAgICBuYW1lOiBcIlRvbVwiLFxuICAgIGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCIsXG4gIH0sXG5dO1xuXG5mdW5jdGlvbiBoYW5kbGVTZWxlY3Rpb25DaGFuZ2UodmFsKSB7XG4gIGFyci5zcGxpY2UoMCwgYXJyLmxlbmd0aCwgLi4udmFsKTtcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by MonkeyMaster** [comment] 2022-11-18 11:04
reproduction link: https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgZGF0YSgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgZGF0ZTogbnVsbCxcbiAgICAgIGNoZWNrOiBmYWxzZVxuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG4gIDxlbC1jaGVja2JveCB2LW1vZGVsPVwiZGF0ZVwiIC8+XG4gIDxlbC1kYXRlLXBpY2tlciB2LW1vZGVsPVwiY2hlY2tcIiAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==
steps:
1. click on checkbox to set it
2. click on datepicker ***icon*** (not it's input) to open picker and select date
3. that error occurs!
Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('checkbox') does not support selection.
✕

**Comment by iamkun** [comment] 2022-11-30 12:51
@MonkeyMaster I can't reproduce the issue. Can you please if I am doing it correctly?

https://user-images.githubusercontent.com/17680888/204800766-359df40c-cd27-469f-ab02-4e9a5d3e456f.mp4

**Comment by tolking** [comment] 2022-12-01 06:32
The PR #10674 Fixed Input component focus issue

Now you can also trigger bugs through [Reproduction demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8YmxvY2txdW90ZT5cbiAgICA8c3Ryb25nPlxuICAgICAgU2VsZWN0IGFsbCBpdGVtcywgdGhlbiBtb3ZlIHRoZSBtb3VzZSBvdmVyIGRyb3Bkcm93biBsaXN0IHRvcCB0byBib3R0b20uXG4gICAgICBUaGVuIHlvdSBjYW4gc2VlIHRoZSBlcnJvciBpbiBjb25zb2xlLlxuICAgIDwvc3Ryb25nPlxuICA8L2Jsb2NrcXVvdGU+XG5cbiAgPGVsLWRyb3Bkb3duPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiA6ZGlzYWJsZWQ9XCJkaXNhYmxlZFwiPlxuICAgICAgRHJvcGRvd24gTGlzdDxlbC1pY29uIGNsYXNzPVwiZWwtaWNvbi0tcmlnaHRcIj48YXJyb3ctZG93biAvPjwvZWwtaWNvbj5cbiAgICA8L2VsLWJ1dHRvbj5cbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAxPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMjwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDM8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbiAgPGVsLXRhYmxlXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgIEBzZWxlY3Rpb24tY2hhbmdlPVwiaGFuZGxlU2VsZWN0aW9uQ2hhbmdlXCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIHdpZHRoPVwiNTVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBjb21wdXRlZCwgcmVhY3RpdmUgfSBmcm9tIFwidnVlXCI7XG5pbXBvcnQgeyBBcnJvd0Rvd24gfSBmcm9tIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjtcblxuY29uc3QgYXJyID0gcmVhY3RpdmUoW10pO1xuY29uc3QgZGlzYWJsZWQgPSBjb21wdXRlZCgoKSA9PiAhYXJyLmxlbmd0aCk7XG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiBcIjIwMTYtMDUtMDNcIixcbiAgICBuYW1lOiBcIlRvbVwiLFxuICAgIGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCIsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiBcIjIwMTYtMDUtMDJcIixcbiAgICBuYW1lOiBcIlRvbVwiLFxuICAgIGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCIsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiBcIjIwMTYtMDUtMDRcIixcbiAgICBuYW1lOiBcIlRvbVwiLFxuICAgIGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCIsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiBcIjIwMTYtMDUtMDFcIixcbiAgICBuYW1lOiBcIlRvbVwiLFxuICAgIGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCIsXG4gIH0sXG5dO1xuXG5mdW5jdGlvbiBoYW5kbGVTZWxlY3Rpb25DaGFuZ2UodmFsKSB7XG4gIGFyci5zcGxpY2UoMCwgYXJyLmxlbmd0aCwgLi4udmFsKTtcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by MonkeyMaster** [comment] 2022-12-01 10:51
Yes, I can't reproduce the case described here on 2.2.25.
The number of these errors logged per day has dropped sharply but not to zero.
At the moment I do not know how to reproduce the remaining ones.

**Comment by MonkeyMaster** [comment] 2022-12-02 02:55
[new demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2hlY2tib3g+PC9lbC1jaGVja2JveD5cbiAgPGVsLXBvcG92ZXIgdGl0bGU9XCJUaXRsZVwiIHRyaWdnZXI9XCJob3ZlclwiIGNvbnRlbnQ9XCJ0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50XCI+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uPkhvdmVyIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wb3BvdmVyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
steps to reproduce:
1. check checkbox
2. hover on button to open popover
3. click on popover content
4. move mouse off popover

there's definitely a problem with the code:
```js
      if (element.tagName === 'INPUT') {
        element.setSelectionRange(element.value.length, element.value.length)
        return
      }
```
how many conflicting components are needed to have a fix?)

**Comment by iamkun** [comment] 2022-12-02 06:52
https://user-images.githubusercontent.com/17680888/205233244-64fde78e-1ab3-4a54-b8c2-946755218e7f.mp4

seem ok 🤔

**Comment by MonkeyMaster** [comment] 2022-12-02 07:26
![2022-12-02 14-17-56 (online-video-cutter com)(1)](https://user-images.githubusercontent.com/1491688/205238393-df8f175d-9213-47a9-82fc-80c79e01040a.gif)

**Comment by Yee1014** [comment] 2022-12-02 07:54
I have a similar question. Only on the first click.

test on [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEVsQ2hlY2tib3g+Y2hlY2sgbWU8L0VsQ2hlY2tib3g+XG4gIDxFbERyb3Bkb3duPlxuICAgIDxFbEJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPkhvdmVyIGJ1dHRvbjwvRWxCdXR0b24+XG4gICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgIDxFbERyb3Bkb3duTWVudT5cbiAgICAgICAgPEVsRHJvcGRvd25JdGVtIEBjbGljaz1cInZpc2libGUgPSAhdmlzaWJsZVwiPlxuICAgICAgICAgIE9wZW4gRGlhbG9nXG4gICAgICAgIDwvRWxEcm9wZG93bkl0ZW0+XG4gICAgICA8L0VsRHJvcGRvd25NZW51PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvRWxEcm9wZG93bj5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIFxuICA8RWxEaWFsb2cgdGl0bGU9XCJNeSBkaWFsb2dcIiB2LW1vZGVsPVwidmlzaWJsZVwiIGFwcGVuZC10by1ib2R5PlxuICBcdGhlbGxvIGJveXN+XG4gIDwvRWxEaWFsb2c+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
Element Plus 2.2.25 + Vue 3.2.45

1. check checkbox
2. hover on button to open popover
3. click on text "open dialog"

```
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const msg = ref('Hello World!')
const visible = ref(false)
</script>

<template>
  <ElCheckbox>check me</ElCheckbox>
  <ElDropdown>
    <ElButton type="primary">Hover button</ElButton>
    <template #dropdown>
      <ElDropdownMenu>
        <ElDropdownItem @click="visible = !visible">
          Open Dialog
        </ElDropdownItem>
      </ElDropdownMenu>
    </template>
  </ElDropdown>

  <p>
    <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
    Element Plus {{ EpVersion }} + Vue {{ vueVersion }}
  </p>
  
  <ElDialog title="My dialog" v-model="visible" append-to-body>
  	hello boys~
  </ElDialog>
</template>

```

**Comment by init-qy** [comment] 2022-12-02 08:00
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange
>Note that according to the [WHATWG forms spec](https://html.spec.whatwg.org/multipage/forms.html#concept-input-apply) selectionStart, selectionEnd properties and setSelectionRange method apply  **only to inputs of types text, search, URL, tel and password.** Chrome, starting from version 33, throws an exception while accessing those properties and method on the rest of input types. For example, on input of type number: "Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection".

So I think add judgement of type `/^(text|search|password|tel|url)$/` will resolve it

**Closed** 2022-12-10 12:15 UTC
Labels: Component::Input, Community::Bug Report

**Comment by mahaoh** [comment] 2022-12-12 08:45
这个问题解决了吗？我也遇到了

**Comment by wei-py** [comment] 2023-01-04 09:43
Did you solve it? urgent!!!
