### ISSUE TITLE
能否新加个treeselect组件

### ISSUE THREAD

**Issue by lht931942788** [element-plus/element-plus#544] opened 2020-11-04 09:28 UTC

**Comment by JeremyWuuuuu** [comment] 2020-11-04 09:30
Could you be more specific about this component?
In the current stage our first priority is to migrate and optimize existing components, we will consider the effort of making a component you wanted, if you could be more specific about the component, maybe a link would be very helpful.

**Comment by lht931942788** [comment] 2020-11-04 09:40
![image](https://user-images.githubusercontent.com/44287981/98094804-bbe98a00-1ec4-11eb-8296-e43d9311566c.png)
就像这样一个树形结构的下拉选

**Comment by lht931942788** [comment] 2020-11-04 09:40
https://www.vue-treeselect.cn/

**Comment by JeremyWuuuuu** [comment] 2020-11-04 09:44
Though we did not provide this feature out of the box, but with the current tree component I think users can implement there own tree-select themselves, but I do think we can make this happen, but not in a short time.

**Comment by lht931942788** [comment] 2020-11-04 09:45
自己写的哪有你们写的好的，要做么，我可以等

**Comment by kooriookami** [comment] 2020-11-05 03:01
Duplicate of #462

**Closed** 2020-11-09 07:30 UTC
Labels: feature request
