### ISSUE TITLE
[Bug Report] 对话框里放表单,表单里有时间选择器(或日期选择器),el-date-picker下拉框出现的位置有问题,经常会有部分区域出现在屏幕下方导致无法使用

### ISSUE THREAD

**Issue by sinkxy** [element-plus/element-plus#5142] opened 2022-01-05 06:10 UTC
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
chrome 96.0.4664.110

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/

### Steps to reproduce
aa

### What is Expected?
aa

### What is actually happening?
aa

**Comment by sinkxy** [comment] 2022-01-05 06:10
![image](https://user-images.githubusercontent.com/20507980/148168931-59eb48fd-8160-421b-8f82-830c5a6809c6.png)

**Comment by emojiiii** [comment] 2022-01-05 06:22
Duplicate of #5044

**Closed** 2022-01-05 06:22 UTC
Labels: bug, duplicate, Component: Popper
