### ISSUE TITLE
[Bug Report] [Component] [collapse] 级联选择器, 添加collapse-tags-tooltip后, 展示出来的信息被覆盖

### ISSUE THREAD

**Issue by a15218378694** [element-plus/element-plus#6861] opened 2022-03-28 03:45 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.1.5`
- Browser / OS: `Chrome93`
- Build Tool: `Vue CLI`

### Related Component

- `el-collapse`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/eku7j4g0/4/)

### Steps to reproduce

1. 打开, 第一个选择器选中多个
2. 鼠标放到数字那里显示tooltip

### What is Expected?

不被覆盖

### What is actually happening?

tooltip内容被覆盖

### Additional comments

_(empty)_

**Comment by btea** [comment] 2022-03-28 10:11
Duplicate of #6642

**Closed** 2022-03-28 10:11 UTC
