### ISSUE TITLE
[Feature Request] Tree V2 - Draggable/Droppable

### ISSUE THREAD

**Issue by nhatimme** [element-plus/element-plus#5502] opened 2022-01-19 14:20 UTC
### Existing Component
Yes

### Component Name
Tree V2

### Description
I would like to see the draggable/droppable functionality like the Tree V1 inside V2.

**Comment by emojiiii** [comment] 2022-01-20 06:03
Duplicate of #5457

**Closed** 2022-01-20 06:05 UTC
Labels: duplicate, feature request, Component: Tree-V2
