### ISSUE TITLE
[Style] [All] Deprecation warnings in sass

### ISSUE THREAD

**Issue by 1Map** [element-plus/element-plus#18318] opened 2024-09-20 07:13 UTC
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.6`
- Element Plus Version: `2.8.3`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link](N/A)

### Steps to reproduce

Run code in VS Code and see SASS warning

### What is Expected?

No Warnings

### What is actually happening?

Getting warnings like:

Deprecation Warning: red() is deprecated. Suggestion:

color.channel($color, red)

More info: https://sass-lang.com/d/color-functions

   ╷
52 │     #{red($color),
   │       ^^^^^^^^^^^
   ╵
    node_modules\element-plus\theme-chalk\src\mixins\_var.scss 52:7  set-css-color-rgb()
    node_modules\element-plus\theme-chalk\src\var.scss 17:5          @use
    node_modules\element-plus\theme-chalk\src\base.scss 1:1          root stylesheet

Deprecation Warning: green() is deprecated. Suggestion:

color.channel($color, green)

More info: https://sass-lang.com/d/color-functions

   ╷
53 │     green($color),
   │     ^^^^^^^^^^^^^
   ╵
    node_modules\element-plus\theme-chalk\src\mixins\_var.scss 53:5  set-css-color-rgb()
    node_modules\element-plus\theme-chalk\src\var.scss 17:5          @use
    node_modules\element-plus\theme-chalk\src\base.scss 1:1          root stylesheet

Deprecation Warning: blue() is deprecated. Suggestion:

color.channel($color, blue)

More info: https://sass-lang.com/d/color-functions

   ╷
54 │     blue($color)}
   │     ^^^^^^^^^^^^
   ╵
    node_modules\element-plus\theme-chalk\src\mixins\_var.scss 54:5  set-css-color-rgb()
    node_modules\element-plus\theme-chalk\src\var.scss 17:5          @use
    node_modules\element-plus\theme-chalk\src\base.scss 1:1          root stylesheet

### Additional comments

_(empty)_

**Comment by linktime-koalaYuan** [comment] 2024-09-20 14:02
This can be resolved by configuring the `vite.config.js` parameter:
```
export default defineConfig({
 ...
  css: {
    preprocessorOptions: {
      scss: {
        api: 'modern'
      }
    }
  }
})

```

The default configuration of vite is legacy, hence this warning

reference document：
* https://sass-lang.com/documentation/breaking-changes/legacy-js-api/
* https://vitejs.dev/config/shared-options.html#css-preprocessoroptions

**Comment by btea** [comment] 2024-09-21 09:01
Duplicate of #18306

**Closed** 2024-09-21 09:01 UTC
