### ISSUE TITLE
[Bug Report] [Style] [image, tab-pane] 图片预览previewSrcList时遮罩层的层级问题

### ISSUE THREAD

**Issue by WishMelz** [element-plus/element-plus#6712] opened 2022-03-18 14:08 UTC
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.1.4`
- Browser / OS: `Chrome/98.0.4758.109 / Mac 10.14.6`
- Build Tool: `Vue CLI`

### Related Component

- `el-image`
- `el-tab-pane`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICBcdDxlbC10YWJzXG4gICAgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIlxuICAgIHR5cGU9XCJjYXJkXCJcbiAgICBjbGFzcz1cImRlbW8tdGFic1wiXG5cbiAgPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIuagh+mimDFcIiBuYW1lPVwiZmlyc3RcIj5cbiAgICAgICAgIFx0PENvbXA+PC9Db21wPlxuICAgIDwvZWwtdGFiLXBhbmU+XG4gICAgICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwi5qCH6aKYMlwiIG5hbWU9XCJmaXJzdHNcIj5cbiAgICAgICAgXG4gICAgPC9lbC10YWItcGFuZT5cbiAgICAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCLmoIfpopgzXCIgbmFtZT1cImZpcnN0c3NcIj5cbiAgICAgICBcbiAgICA8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG4gIFxuIDwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG4gIGltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIjtcbiAgaW1wb3J0IENvbXAgZnJvbSAnLi9Db21wLnZ1ZSdcbiBjb21wb25lbnRzOiB7XG4gICBDb21wXG4gIH1cbiAgY29uc3QgYWN0aXZlTmFtZSA9IHJlZihcImZpcnN0XCIpO1xuICA8L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319IiwiQ29tcC52dWUiOiI8dGVtcGxhdGU+XG4gIFx0XG4gIFxuICAgIDxlbC10YWJsZSA6ZGF0YT1cImxpc3RcIiBib3JkZXIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cImluZGV4XCIgd2lkdGg9XCI1MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwidFwiIGxhYmVsPVwi5YiG57G7XCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICA8c3BhbiB2LWlmPVwic2NvcGUucm93LnQgPT0gMVwiPuacjeWKoeWZqDwvc3Bhbj5cbiAgICAgICAgPHNwYW4gdi1lbHNlLWlmPVwic2NvcGUucm93LnQgPT0gMlwiPk9TUzwvc3Bhbj5cbiAgICAgICAgPHNwYW4gdi1lbHNlPuiBmuWQiDwvc3Bhbj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwidGltZXNcIiBsYWJlbD1cIuaXtumXtFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICBcbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwidXJsXCIgbGFiZWw9XCLlm77niYdcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgICAgPGVsLWltYWdlXG4gICAgICAgXG4gICAgICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwcHg7IGhlaWdodDogMTAwcHhcIlxuICAgICAgICAgIHNyYz1cImh0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnXCJcbiAgICAgICAgICA6cHJldmlldy1zcmMtbGlzdD1cIlsnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2EvM2YvMzMwMmU1OGY5YTE4MWQyNTA5ZjNkYzBmYTY4YjBqcGVnLmpwZWcnXVwiXG4gICAgICAgICAgOmluaXRpYWwtaW5kZXg9XCIwXCJcbiAgICAgICAgICBmaXQ9XCJjb3ZlclwiXG4gICAgICAgIC8+XG4gICAgICBcbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG4gIFxuICBcbiAgXG4gIFx0IDxlbC1pbWFnZVxuICAgICAgIFxuICAgICAgICAgIHN0eWxlPVwid2lkdGg6IDEwMHB4OyBoZWlnaHQ6IDEwMHB4XCJcbiAgICAgICAgICBzcmM9XCJodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vYS8zZi8zMzAyZTU4ZjlhMTgxZDI1MDlmM2RjMGZhNjhiMGpwZWcuanBlZ1wiXG4gICAgICAgICAgOnByZXZpZXctc3JjLWxpc3Q9XCJbJ2h0dHBzOi8vcGljLnJtYi5iZHN0YXRpYy5jb20vYmpoL2ZmNmMxZDZlMzA1NDEyZjEyZTdmYjM5YTc3YTZmZWVmLmpwZWcnXVwiXG4gICAgICAgICAgOmluaXRpYWwtaW5kZXg9XCIwXCJcbiAgICAgICAgICBmaXQ9XCJjb3ZlclwiXG4gICAgICAgIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuICBcbiAgY29uc3QgbGlzdCA9IFtcbiAgIHtcbiAgICAgdDoxLFxuICAgICB0aW1lczpcIjEyMzEyMzEyM1wiLFxudXJsOlwiaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2EvM2YvMzMwMmU1OGY5YTE4MWQyNTA5ZjNkYzBmYTY4YjBqcGVnLmpwZWdcIlxuICAgfSBcbiAgXVxuXG48L3NjcmlwdD5cblxuPHN0eWxlPlxuXG48L3N0eWxlPiJ9)

### Steps to reproduce

点击表格的图片预览,遮罩层的层级问题

### What is Expected?

遮罩层层级在最高层

### What is actually happening?

el-tabs的标签在遮罩层的上面

### Additional comments

打开复现链接, 点击表格的图片预览可以很直观的看到问题

**Comment by CN-FH** [comment] 2022-03-19 05:54
我也出现了类似这样的问题

**Comment by nieyuyao** [comment] 2022-03-19 06:17
可以给`el-image`组件设置`append-to-body`来解决层级问题

```jsx
<el-image append-to-body />
```

**Comment by nieyuyao** [comment] 2022-03-19 06:30
可以给`el-image`组件设置`preview-teleported`来解决层级问题

<el-image preview-teleported />

**Comment by buqiyuan** [comment] 2022-03-19 06:39
Duplicate of #6335

**Closed by buqiyuan** 2022-03-19 06:39 UTC
