### ISSUE TITLE
[Bug Report] ElForm status-icon BUG

### ISSUE THREAD

**Issue by kailong321200875** [element-plus/element-plus#5141] opened 2022-01-05 05:57 UTC
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
版本 96.0.4664.110（正式版本） （64 位）

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/ah4q0tfL/3/

### Steps to reproduce
When the clearable attribute of El input is set, the stauts-icon in El form displays an exception

### What is Expected?
stauts-icon should not appear

### What is actually happening?
stauts-icon appears

**Comment by kailong321200875** [comment] 2022-01-05 06:00
![image](https://user-images.githubusercontent.com/32283845/148167975-1923e9ec-6187-492a-a595-b35a0156777c.png)

like this

**Comment by emojiiii** [comment] 2022-01-05 06:34
Duplicate of #5006

**Closed** 2022-01-05 06:34 UTC
Labels: bug, duplicate, Component: Input
