### ISSUE TITLE
Custom theme?

### ISSUE THREAD

**Issue by merrylmr** [element-plus/element-plus#411] opened 2020-10-14 09:11 UTC
I am using `element-plus` in my project,And i don't  found  the feature that is  "custom theme".
Dose this repository have  this feature so far?

**Comment by zazzaz** [comment] 2020-10-14 09:24
Is this what ur looking for? 
https://element-plus.org/#/en-US/component/custom-theme

**Comment by merrylmr** [comment] 2020-10-14 10:07
@zazzaz  Support   "Update SCSS variables in your project"?

element-variables.scss:
```
/* theme color */
$--color-primary: teal;

/* icon font path, required */
$--font-path: '~element-ui/lib/theme-chalk/fonts';

@import "~element-ui/packages/theme-chalk/src/index";
```
main.ts:
```
import Vue from 'vue'
import Element from 'element-ui'
import './element-variables.scss'

Vue.use(Element)
```

**Comment by zazzaz** [comment] 2020-10-14 10:19
The doc has not updated yet, simply replace it with element-plus

**Comment by merrylmr** [comment] 2020-10-14 10:28
@zazzaz This file"~element-plus/packages/theme-chalk/src/index" don,t exist!

**Comment by zazzaz** [comment] 2020-10-15 02:38
@merrylmr Sorry for the inconvenience caused by the packaging error, please use `element-plus@1.0.1-alpha.5` instead.

https://unpkg.com/element-plus@1.0.1-alpha.5/packages/theme-chalk/src/index.scss

**Comment by merrylmr** [comment] 2020-10-15 06:41
@zazzaz I can't run this project  after update to `1.0.1-alpha.5`. this error as below:

```
 ERROR  Failed to compile with 1 errors                                                                                                                              2:22:31 PM

This dependency was not found:

* Vue in ./node_modules/element-plus/lib/index.js

To install it, you can run: npm install --save Vue

```
![image](https://user-images.githubusercontent.com/21325085/96085139-ef9f4880-0ef2-11eb-94c4-06e64aef8c34.png)

**Comment by zazzaz** [comment] 2020-10-15 08:00
This file is exist as below.
https://unpkg.com/element-plus@1.0.1-alpha.5/lib/index.js

**Comment by zazzaz** [comment] 2020-10-16 06:41
@merrylmr  sorry for the build error.

This should be fixed in 1.0.1-alpha.6, and docs updated accordingly.

**Comment by zazzaz** [comment] 2020-10-22 06:22
fixed

**Closed by zazzaz** 2020-10-22 06:22 UTC

**Comment by catch6** [comment] 2020-12-30 04:33
> @zazzaz I can't run this project after update to `1.0.1-alpha.5`. this error as below:
> 
> ```
>  ERROR  Failed to compile with 1 errors                                                                                                                              2:22:31 PM
> 
> This dependency was not found:
> 
> * Vue in ./node_modules/element-plus/lib/index.js
> 
> To install it, you can run: npm install --save Vue
> ```
> 
> ![image](https://user-images.githubusercontent.com/21325085/96085139-ef9f4880-0ef2-11eb-94c4-06e64aef8c34.png)

what is the font

**Comment by zazzaz** [comment] 2020-12-30 05:15
@catch6 Hi, a reproduction demo, please?

Also, it is better to use the latest version element-plus@1.0.1-beta.17
