### ISSUE TITLE
[Bug Report] Cannot find module 'D:\project\nuxt3-battery\node_modules\lodash\isEqual'

### ISSUE THREAD

**Issue by xuwei5616** [element-plus/element-plus#4923] opened 2021-12-22 05:05 UTC
### Element Plus version
1.2.0-beta.6

### Steps to reproduce
nuxt 引入 访问页面控制台报错， lodash npm 包是没有isEqual的

### What is actually happening?
Cannot find module 'D:\project\nuxt3-battery\node_modules\lodash\isEqual' imported from D:\project\nuxt3-battery\node_modules\element-plus\es\components\time-picker\src\common\picker.vue_vue_type_script_lang.mjs

**Comment by charles-allen** [comment] 2021-12-28 03:32
Looks like https://github.com/element-plus/element-plus-nuxt-starter/issues/5

FYI - I think this is not Nuxt-specific. You seem to be missing `lodash` in `peerDependencies`. I think you were getting lucky that most projects installed `lodash` separately, and this issue arises when either the they don't install `lodash` or they install `lodash-es` instead (which I believe is the correct approach for ESM projects).

**Comment by charles-allen** [comment] 2021-12-28 07:07
**Firstly... lots of appreciation for supporting ESM!**

Personally I'm seeing this error in a Vue 3 project (not Nuxt) while trying to configure my tests to use `vitest` (which is still beta). **I was able to locally fix my errors by adding `.js` to the end of the ES build's imports**. Strictly, I think ESM builds are supposed to include the file extension in imports.

Examples:

_/es/components/autocomplete/src/index.vue_vue_type_script_lang.mjs_
```diff
- import debounce from 'lodash/debounce';
+ import debounce from 'lodash/debounce.js';
```

_/es/components/date-picker/src/data-picker.mjs_
```diff
- import customParseFormat from 'dayjs/plugin/customParseFormat';
- import advancedFormat from 'dayjs/plugin/advancedFormat';
- import localeData from 'dayjs/plugin/localeData';
- import weekOfYear from 'dayjs/plugin/weekOfYear';
- import weekYear from 'dayjs/plugin/weekYear';
- import dayOfYear from 'dayjs/plugin/dayOfYear';
- import isSameOrAfter from 'dayjs/plugin/isSameOrAfter';
- import isSameOrBefore from 'dayjs/plugin/isSameOrBefore';
+ import customParseFormat from 'dayjs/plugin/customParseFormat.js';
+ import advancedFormat from 'dayjs/plugin/advancedFormat.js';
+ import localeData from 'dayjs/plugin/localeData.js';
+ import weekOfYear from 'dayjs/plugin/weekOfYear.js';
+ import weekYear from 'dayjs/plugin/weekYear.js';
+ import dayOfYear from 'dayjs/plugin/dayOfYear.js';
+ import isSameOrAfter from 'dayjs/plugin/isSameOrAfter.js';
+ import isSameOrBefore from 'dayjs/plugin/isSameOrBefore.js';
```

`vite` and `vite build` are working for me; I think `vite` is tolerant to missing extensions. I'm assuming given the OP that `nuxt` is/was not tolerant. Given this is a vue-specific library you might find this gets fixed elsewhere.

If you determine that this should be fixed here, you probably just need to grep for `lodash/` and `dayjs/`

...unfortunately now I get this error instead:

> TypeError: Unknown file extension ".scss" for /Users/USER_NAME/Dev/REPO_NAME/node_modules/.pnpm/element-plus@1.2.0-beta.6_vue@3.2.21/node_modules/element-plus/theme-chalk/src/tag.scss

**Comment by dyardy** [comment] 2021-12-31 19:59
Same issue

**Comment by yuchailam** [comment] 2022-01-18 02:35
you have to install typescript to your global env using `npm install -g typescript` or to your project `npm install typescript`

**Comment by charles-allen** [comment] 2022-01-18 05:38
> you have to install typescript to your global env using `npm install -g typescript` or to your project `npm install typescript`. It works to me

I already have typescript installed both globally & locally in the project

**Comment by Eiryyy** [comment] 2022-01-18 12:45
Same Issue

**Comment by jagoncalves14** [comment] 2022-01-25 10:50
I'm currently facing this issue. I'm trying to add Vitest to my application and I get the same error.
I'm using Element-Plus, version `1.3.0-beta.7`

I made a Stackblitz replicating this:
https://stackblitz.com/edit/github-64cnue

**Comment by jagoncalves14** [comment] 2022-01-26 21:50
I opened a PR for fixing the imports:
https://github.com/element-plus/element-plus/pull/5662/files

**Comment by jagoncalves14** [comment] 2022-01-27 18:20
@charles-allen, in order to fix this issue, we need to add `deps.inline = ['element-plus']` to Vitest's config.

**Example:**
```
export default defineConfig({
  [...],
  test: {
    [...],
    deps: {
      inline: ['element-plus'],
    },
  },
})
```

I updated the StackBlitz repo above with this solution:
https://stackblitz.com/edit/github-64cnue?file=vite.config.ts

Considering this, I think we can close this issue and probably add this information to ElementPlus' documentation for how to use the library with Vitest.

**Comment by PascalAOMS** [comment] 2022-02-08 12:43
I have the same issue but with the latest Element Plus version while using Vite.

```
Cannot find module '...\node_modules\lodash\isEqual' imported from ...\node_modules\element-plus\es\components\time-picker\src\common\picker.mjs

Did you mean to import lodash/isEqual.js?
```

**Comment by Jackliu007888** [comment] 2022-02-14 08:03
没人解决吗

**Comment by estudiooka** [comment] 2022-02-20 14:57
get to work but still not SSR support.

styles are not inject to the component when on SSR with Nuxt so a plain button works but not a primary ...

**Comment by xiaoxian521** [comment] 2022-02-22 07:14
Hey, can this problem be reproduced?
If you can trouble to provide an example, let's fix it asap

**Comment by sxzz** [comment] 2022-02-22 07:28
I switched to `lodash-unified`. It seems be fixed.

**Closed** 2022-02-25 08:49 UTC
Labels: Component: DatePicker, nuxt related

**Comment by PascalAOMS** [comment] 2022-02-25 09:37
How is this solved?
The recent patch does not mention any Lodash package changes.
Am I missing something?

**Comment by sxzz** [comment] 2022-02-25 09:38
It may be fixed by https://github.com/element-plus/element-plus/pull/5734

**Comment by geewhizbang** [comment] 2022-03-28 17:06
When I try to paste in the config in https://stackblitz.com/edit/github-64cnue?file=tsconfig.json, all it does is break tests completely.

We aren't using .spec to mark tests, for one thing. and the setup for vitest is in a separate file: tsconfig.vitest.json:

{
  "extends": "@vue/tsconfig/tsconfig.node.json",
  "include": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "types": ["node", "jsdom"],
  }
}

**Comment by zhengzhigang** [comment] 2022-06-06 03:24
这个问题nuxt3的issue有解决方案的吧

**Comment by CherishTheYouth** [comment] 2022-08-29 11:10
@jagoncalves14 thank you，your solution works for my error, thanks a lot! @

**Comment by YuanDaoDao001** [comment] 2022-09-14 03:56
> TypeError: Unknown file extension ".scss" for

Hot to fix this error? I have the same error

Before the error is  [https://github.com/element-plus/element-plus-nuxt-starter/issues/5#issuecomment-1027745575](url)

then update element-plus's version, it's resolved.  but got a new error like above
