### ISSUE TITLE
[Docs] [All] 镜像站总是报404/503

### ISSUE THREAD

**Issue by cnLiuMing** [element-plus/element-plus#10605] opened 2022-11-15 02:17 UTC
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/cascader.html)

### Steps to reproduce

访问 https://element-plus.gitee.io/zh-CN/component/cascader.html

### What is Expected?

正常访问

### What is actually happening?

无法访问

### Additional comments

_(empty)_

**Comment by holazz** [comment] 2022-11-15 02:46
Duplicate of #9196

**Closed by holazz** 2022-11-15 02:46 UTC
