### ISSUE TITLE
[Component] [date-picker] 选择下一个月灰色的日期,返回日期与所选的不一样

### ISSUE THREAD

**Issue by esr-haode** [element-plus/element-plus#8489] opened 2022-06-27 08:12 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblxuICA8cD5cbiAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgICAgdHlwZT1cImRhdGVcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBkYXlcIiAgICAgXG4gICAgICAvPlxuICA8L3A+XG4gICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1. Today is 2022-06-27, directly select the date 07-02 (just select the gray date)
2. will be return 2022-07-30 ,console error: Maximum call stack size exceeded will be reported.

### What is Expected?

Return the correct date selected

### What is actually happening?

return wrong date

### Additional comments

It will only appear if the initialized value is empty

**Comment by KimYangOfCat** [comment] 2022-06-28 02:10
duplicate of #8494

**Closed** 2022-07-21 04:12 UTC
Labels: Project::Bug, Component::DatePicker
