### ISSUE TITLE
[feature request] paged title display error

### ISSUE THREAD

**Issue by lxygebilaoyanggg** [element-plus/element-plus#4765] opened 2021-12-10 07:49 UTC
### Existing Component
Yes

### Component Name
el-pagination

### Description
el-pagination

**Comment by lxygebilaoyanggg** [comment] 2021-12-10 07:49
是total

**Comment by emojiiii** [comment] 2021-12-10 08:56
Duplicate of #4617. Fix in #4619

**Closed** 2021-12-10 08:56 UTC
Labels: 🤔 need reproduce
