### ISSUE TITLE
el-table can't reduce in display:flex

### ISSUE THREAD

**Issue by XingXiaoWu** [element-plus/element-plus#914] opened 2020-12-09 06:42 UTC
```
<div style="display:flex">
 <el-table
      :data="tableData"
      style="width: 100%">
      <el-table-column
        prop="date"
        label="日期"
        width="180"/>
      <el-table-column
        prop="name"
        label="姓名"
        width="180"/>
      <el-table-column
        prop="address"
        label="地址"/>
    </el-table>
</div>
```
el-table can get longer when browser elongated,but it can’t adapt when browser is shrunk

**Comment by JeremyWuuuuu** [comment] 2020-12-09 07:37
@justwiner will follow this up

**Comment by justwiner** [comment] 2020-12-11 08:28
Duplicate of #922

**Closed** 2020-12-14 06:21 UTC
Labels: duplicate

**Comment by XingXiaoWu** [comment] 2021-01-06 05:29
"element-plus": "^1.0.1-beta.20"
It hasn't been fixed.
It's also can't adapt when browser is shrunk.
没有修复，在flex布局下，横向收缩依旧无法自适应
