### ISSUE TITLE
Autocomplete input resize

### ISSUE THREAD

**Issue by AubSs** [element-plus/element-plus#525] opened 2020-10-31 19:04 UTC
autocomplete input can't be resized (using flex properties or other)
I don't understand why it has an arbitrary fixed size.

**Comment by JeremyWuuuuu** [comment] 2020-11-02 07:29
cc @Caaalabash

**Comment by Caaalabash** [comment] 2020-11-02 09:34
I only can provide you limited help because of you didn't provide a minimal reproducible code.

maybe you only set css rules on `.el-autocomplete`, you can try set css rules on `.el-input`, `.el-input__inner`.

````
::v-deep(.el-input) {
 
}
::v-deep(.el-input__inner) {
  
}
````

**Comment by AubSs** [comment] 2020-11-02 12:34
--- Code Sample
```
<el-form v-loading="contracts.form.loading" :model="contracts.form.data">
            <el-form-item label="Fournisseur">
                <el-select v-model="contracts.form.data.supplier" clearable placeholder="Select">
                    <el-option v-for="item in suppliers.data" :key="item.id" :label="item.headquarters.name" :value="item.id" />
                </el-select>
            </el-form-item>
            <el-select v-model="contracts.form.data.supplier" clearable placeholder="Select">
                <el-option v-for="item in suppliers.data" :key="item.id" :label="item.headquarters.name" :value="item.id" />
            </el-select>
            <el-form-item label="Label"><el-input v-model="contracts.form.data.label" /></el-form-item>
            <el-form-item label="Référence"><el-input v-model="contracts.form.data.ref" /></el-form-item>
            <el-form-item label="Period"><el-date-picker v-model="contracts.form.data.period" :unlink-panels="true" type="daterange" :shortcuts="contratPeriodShortcuts" /></el-form-item>
            <el-button type="primary" @click="contracts.form.create(CondoID)">Primary</el-button>
        </el-form>
```

Give : 
<img width="823" alt="Screenshot 2020-11-02 at 13 31 16" src="https://user-images.githubusercontent.com/10529080/97868508-18577880-1d10-11eb-8adb-d76bd51921fd.png">

**Comment by Caaalabash** [comment] 2020-11-02 13:06
So this is a usage problem. Please [check the document](https://element.eleme.cn/#/en-US/component/form#alignment) and set css rules if you needed :)

**Comment by AubSs** [comment] 2020-11-02 17:43
Maybe,
So it's assumed that input number / date picker / select do not follow CSS form rules like any others input type?
For example, in my form, it's not convenient that I have to hack these specific fields to be completely integrated.
Why label 'Period' should not be positioned like the label "Reference" by default?

**Comment by Caaalabash** [comment] 2020-11-02 19:02
Please [check the document](https://element.eleme.cn/#/en-US/component/form#alignment), you can find the `label-position="top"` attribute easily. For your other questions, I only can say this is by design.

**Comment by AubSs** [comment] 2020-11-02 19:20
Ok, 
@Caaalabash Thank you for your time !

**Comment by Caaalabash** [comment] 2020-11-02 20:04
There this a problem with `el-autocomplete` indeed. `<el-autocomplete style="width: 100%"/>`'s behavior will be fixed

**Comment by JeremyWuuuuu** [comment] 2020-11-03 03:43
So is this issue fixed? @Caaalabash

**Closed** 2020-11-03 03:44 UTC

**Comment by Caaalabash** [comment] 2020-11-03 04:47
Yes, I think. @JeremyWuuuuu
