### ISSUE TITLE
el-select多选显示有问题（版本1.0.1-beta.4)

### ISSUE THREAD

**Issue by chengaohe45** [element-plus/element-plus#874] opened 2020-12-07 08:15 UTC
el-select多选显示有问题：选择第一个值界面显示为空

**Comment by JeremyWuuuuu** [comment] 2020-12-07 08:16
Seems like the bug I mentioned the other day @SimonaliaChen, got time on this?

**Comment by JeremyWuuuuu** [comment] 2020-12-07 08:17
Also we need demo code to reproduce the bug.

**Comment by porcelainHeart** [comment] 2020-12-07 08:42
demo：
https://element-plus.gitee.io/#/ji-chu-duo-xuan

**Comment by JeremyWuuuuu** [comment] 2020-12-07 08:44
> demo：
> https://element-plus.gitee.io/#/ji-chu-duo-xuan

Wrong link [ElementPlus Select](https://element-plus.gitee.io/#/zh-CN/component/select)

**Comment by porcelainHeart** [comment] 2020-12-07 08:47
> > demo：
> > https://element-plus.gitee.io/#/ji-chu-duo-xuan
> 
> Wrong link [ElementPlus Select](https://element-plus.gitee.io/#/zh-CN/component/select)

And in this case，
When selecting two or more options, the options cannot clear。

**Comment by JeremyWuuuuu** [comment] 2020-12-07 12:11
This is the exact bug that I found myself, @Liiked is going to take care of this.

**Comment by JeremyWuuuuu** [comment] 2020-12-08 06:12
This bug might have existed since `beta.0` or even `alpha`, nobody seems to notice it, it might have something to do with `el-popper` I am going to investigate it.

**Comment by LuoRiWuSheng** [comment] 2020-12-09 11:34
在 vue 中添加  class 类

`<el-select  multiple  clearable class='fix-text-overflow'>`
      
`</el-select>`

使用的全局样式

`<style lang="less">`
`.fix-text-overflow {`
`  .el-tag {`
`    position: relative;`
`    max-width: 99%;`
`    overflow: hidden;`

`    & > span {`
`      margin-right: 14px;`
`      overflow: hidden;`
`      text-overflow: ellipsis;`
`      white-space: nowrap;`
`      display: block;`
 `   }`

`    & > i {`
`      display: block;`
`      position: absolute;`
`      right: 4px !important;`
`      top: 4px !important;`
`    }`
`  }`
`}`
`</style>`

可以修复 select 中文本溢出的问题

@JeremyWuuuuu 

![carbon](https://user-images.githubusercontent.com/23192097/101624834-813fb800-3a55-11eb-84ae-60c7084a6ea4.png)

**Comment by JeremyWuuuuu** [comment] 2020-12-10 03:32
@LuoRiWuSheng Would you like to give it a shot? I mean make a PR for this fix

**Comment by JeremyWuuuuu** [comment] 2020-12-18 03:18
Fixed in #967

**Closed by JeremyWuuuuu** 2020-12-18 03:18 UTC
Labels: bug
