### ISSUE TITLE
[Feature Request] Introduce components on demand, ElNotification css is lost after page jumping through vue-router@4

### ISSUE THREAD

**Issue by asasugar** [element-plus/element-plus#5527] opened 2022-01-21 06:57 UTC
### Existing Component
Yes

### Component Name
ElNotification

### Description
Introduce components on demand, ElNotification css is lost after page jumping through vue-router@4

**Comment by asasugar** [comment] 2022-01-21 07:01
when in Login.vue
![image](https://user-images.githubusercontent.com/27256120/150481189-a9383968-8916-4664-8438-330ea3303d6f.png)
![image](https://user-images.githubusercontent.com/27256120/150481485-1d4bd84a-ff24-4ea3-a613-db762cc5e6e1.png)

**Comment by asasugar** [comment] 2022-01-21 07:02
when in Home.vue
![image](https://user-images.githubusercontent.com/27256120/150481587-221d9c52-2a08-4d3c-9836-fcd23b63fe34.png)

**Comment by asasugar** [comment] 2022-01-21 07:27
I found the reason because ‘el-icon’

**Comment by asasugar** [comment] 2022-01-21 07:28
It is recommended to put the description of the icon in the quick start

**Comment by asasugar** [comment] 2022-01-21 07:59
@emojiiii how to solve conflict between 'el-icon' and 'ElNotification' style.

**Comment by emojiiii** [comment] 2022-01-21 08:06
can you provide a mini repo ? @asasugar

**Comment by momtboy** [comment] 2022-01-24 04:45
1.3.0-beta.7版本遇到同样问题；

`plugins: [
    [
      'import',
      {
        libraryName: 'element-plus',
        customName: (name) => {
          name = name.slice(3)
          return `element-plus/lib/components/${name}`
        },
        customStyleName: (name) => {
          name = name.slice(3)
          return `element-plus/lib/components/${name}/style`
        }
      }
    ]
  ]`

vue-cli打包

**Comment by mxp131011** [comment] 2022-01-27 02:11
请看：5632

**Comment by sxzz** [comment] 2022-01-27 15:55
Duplicate of #5165

**Closed** 2022-01-27 15:55 UTC
Labels: documentation, feature request, need reproduction

**Comment by zhangchenna** [comment] 2022-02-07 10:33
这个问题还是存在啊

**Comment by asasugar** [comment] 2022-02-08 01:55
> el-icon



> 

如果页面中同时存在el-icon的话 会影响样式，使用@element-plus/icons-vue

**Comment by zhangchenna** [comment] 2022-02-08 05:45
我也发现了。。。这个太坑了
