### ISSUE TITLE
[Component] [input-number]  input  '+‘ or  'e'，value is null

### ISSUE THREAD

**Issue by yumanjiang17** [element-plus/element-plus#17038] opened 2024-05-31 08:50 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.7.3`
- Browser / OS: `Microsoft Edge 版本 125.0.2535.67 (正式版本) (64 位)`
- Build Tool: `Webpack`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWlucHV0LW51bWJlciB2LW1vZGVsPVwibnVtXCIgOm1pbj1cIjFcIiA6bWF4PVwiMTBcIiBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IG51bSA9IHJlZigxKVxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKHZhbHVlOiBudW1iZXIpID0+IHtcbiAgY29uc29sZS5sb2codmFsdWUpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

在输入框输入+或e，console value

### What is Expected?

1.不能输入+或e
2.输入+或e，value值正确

### What is actually happening?

可以输入+或e，且输入后实际获得的value是null

### Additional comments

_(empty)_

**Comment by yumanjiang17** [comment] 2024-05-31 08:52
![image](https://github.com/element-plus/element-plus/assets/96509227/8744866f-9c3b-4ab5-818d-0ded9320b4d4)

**Comment by JiuRanYa** [comment] 2024-05-31 10:11
e or + is not a number actually.`+1` or `1e+6` is valid.

**Comment by btea** [comment] 2024-06-01 01:11
Duplicate of #16267

**Closed** 2024-06-01 01:11 UTC
