### ISSUE TITLE
Men导航切换路由的时候，把数据存储在 Vuex中页面会卡死 .....

### ISSUE THREAD

**Issue by Bo-LiangD** [element-plus/element-plus#972] opened 2020-12-11 09:06 UTC
使用 Vue3.0.4 + Element-plus 1.0.1-beta.6 + vuex4.0.0-0 
![企业微信截图_16076774031769](https://user-images.githubusercontent.com/29296518/101883847-cb9a7380-3bd2-11eb-9b1f-a2700cdbcbc1.png)
如图 所示  功能类似 导航面包屑
![image](https://user-images.githubusercontent.com/29296518/101883984-fb497b80-3bd2-11eb-91df-b358961b0373.png)
这是我写的方法

警告出现后  后续 继续路由切换 流畅无误

**Comment by JeremyWuuuuu** [comment] 2020-12-11 09:18
Hey can you provide us the minimal reproducible code for us to investigate? We haven't had solid tests with Vuex, I guess that was our mistake

**Comment by JeremyWuuuuu** [comment] 2020-12-11 09:18
repo or online editor are both acceptable, thx

**Comment by Bo-LiangD** [comment] 2020-12-11 09:20
em.em.em.. 稍等片刻

**Comment by Bo-LiangD** [comment] 2020-12-13 07:12
哈喽    
https://gitee.com/boliangd/demo.git  
我把代码上传了  您跑一下

**Comment by Bo-LiangD** [comment] 2020-12-14 02:47
> 回购或在线编辑器都可以接受

哈喽  在的嘛

**Comment by JeremyWuuuuu** [comment] 2020-12-14 03:02
We'll investigate it soon.

**Comment by JeremyWuuuuu** [comment] 2020-12-15 07:05
I did a simple investigation, refer to here: https://github.com/vuejs/vue-next/issues/2027, 
watching `route` is essentially `deep: true` case, in this case, because route is a rather large object which causes the traverse over route costly.

**Comment by JeremyWuuuuu** [comment] 2020-12-15 07:13
The simplest way to modify the code, per Evan's suggestion:
![image](https://user-images.githubusercontent.com/15975785/102182754-c21d4e00-3ee7-11eb-991d-bff9e44d5c10.png)

But this modification will cause other issue:
![image](https://user-images.githubusercontent.com/15975785/102182800-d6614b00-3ee7-11eb-96db-07e5cc69414c.png)

This is what you need to fix. The warning and the lagging were no longer existing.

**Comment by JeremyWuuuuu** [comment] 2020-12-15 07:15
Note that you **MUST** use `watchEffect` instead of `watch` to do the job, or you can use `computed` to do the work.

**Comment by JeremyWuuuuu** [comment] 2020-12-15 07:16
Feel free to ping me on this. Thank you. Since this isn't issue from `ElementPlus`, I am closing this issue, feel free to reopen it if you feel to.

**Closed by JeremyWuuuuu** 2020-12-15 07:16 UTC
