### ISSUE TITLE
[Bug Report] Cannot find name "Nullable"

### ISSUE THREAD

**Issue by Oleksii14** [element-plus/element-plus#2725] opened 2021-07-27 12:52 UTC
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
MacOS Big Sur 11.5 

### Vue version
3.1.5

### Reproduction Link
https://github.com/Oleksii14/element-plus-ts-bug

### Steps to reproduce
Sorry for the fake repro link!

I am not sure I can reproduce it locally in a new project.

The issue description:
There is a Vue 3 and TypeScript project set up via Vue CLI. We're using Element Plus v1.0.2-beta.63

We have started to get the TS error recently from the file: node_modules/element-plus/lib/utils/types.ts

`export type RefElement = Nullable<HTMLElement>` - for this line. I think TS does not see the types from declaration files. Can you advice something?

P.S. `skipLibCheck` property in `tsconfig.json` is set to `true`

### What is Expected?
No TS error

### What is actually happening?
TS throws an error from the library

**UPD**: repro link added

**Comment by Oleksii14** [comment] 2021-07-27 12:55
FYI: version 1.0.2-beta.55 works without a problem

**Comment by JBtje** [comment] 2021-07-27 16:09
Both beta.55 and beta.63 have this problem, but only in combination with ts-loader 9.0.0 or higher.
Using ts-loader 8.3.0, there is no error.

```
ts-loader 9.0.0 release notes:
Breaking changes:

minimum webpack version: 5
minimum node version: 12
```
so the cause should be there somehow?

**Comment by damiankoper** [comment] 2021-07-27 16:14
Where does type Nullable<T> originate from?

**Comment by mitjans** [comment] 2021-07-27 17:09
I am facing the same issue. Tried beta.55 and it doesn't work either.

**Comment by Oleksii14** [comment] 2021-07-27 18:26
> I am facing the same issue. Tried beta.55 and it doesn't work either.

version beta.55 does not have a `types.ts` file so the error does not appear.

beta.55 structure:

![image](https://user-images.githubusercontent.com/36737084/127207663-48509147-e125-4e18-b482-34adb4ecd837.png)


beta.63 structure:

![image](https://user-images.githubusercontent.com/36737084/127207778-d3b0d011-9db7-4cac-aee4-f8eec7375905.png)


So as I can see, the error in higher versions comes from `element-plus/lib/utils/types.ts`

**Comment by Oleksii14** [comment] 2021-07-27 18:27
I think in your package.json you have something like `"element-plus": "^1.0.2-beta.55"` - which installs the newest compatible version. Try changing it to `"element-plus": "1.0.2-beta.55"` - should help

**Comment by mitjans** [comment] 2021-07-27 22:16
I removed `yarn.lock` and `node_modules` folder and installed version `1.0.2-beta.55`. Still having the same problem.
In fact, this problem is introduced in version `1.0.2-beta.28`. Before that release, the file `types.ts` is not present.

**Comment by tolking** [comment] 2021-07-28 01:51
Come from [vue-shim](https://github.com/element-plus/element-plus/blob/dev/typings/vue-shim.d.ts), You need to introduce a separate type file in `element-plus/lib/element-plus.d.ts`. 

@JeremyWuuuuu Maybe this types should be move to `utils/types`

**Comment by JeremyWuuuuu** [comment] 2021-07-28 01:55
Sorry guys, we made huge change during the weekend which introduces all typing files into the package, this was broken but without the typing files it was ok, we intend to fix that ASAP!

**Comment by JeremyWuuuuu** [comment] 2021-07-28 01:57
I saw @PxlBuzzard have given a solution. And the code seems legit, after this gets merged, we will release a new version which would contain this type.

**Closed** 2021-07-28 02:16 UTC
Labels: bug, type related

**Comment by JeremyWuuuuu** [comment] 2021-07-28 02:18
New version is about to be released, please let me know if you have any other issues :pray: Let's make this project perfect!
