### ISSUE TITLE
[Bug Report] el-dropdown disabled 属性无效

### ISSUE THREAD

**Issue by cxj-github** [element-plus/element-plus#5599] opened 2022-01-24 10:19 UTC
### Element Plus version
1.3.0-beta.7

### OS/Browsers version
chrome latest

### Vue version
3.2.29

### Reproduction Link
https://codesandbox.io

### 复现链接：
https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LXdyYXAgaXRlbXMtY2VudGVyXCI+XG4gICAgPGVsLWRyb3Bkb3duIGRpc2FibGVkPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPlxuICAgICAgICBEcm9wZG93biBMaXN0PGVsLWljb24gY2xhc3M9XCJlbC1pY29uLS1yaWdodFwiPjxhcnJvdy1kb3duIC8+PC9lbC1pY29uPlxuICAgICAgPC9lbC1idXR0b24+XG4gICAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMjwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMzwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gNDwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gNTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPC9lbC1kcm9wZG93bi1tZW51PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWRyb3Bkb3duPlxuICAgIDxlbC1kcm9wZG93biBkaXNhYmxlZCBzcGxpdC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJoYW5kbGVDbGlja1wiPlxuICAgICAgRHJvcGRvd24gTGlzdFxuICAgICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDE8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDI8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDM8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDQ8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDU8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC1kcm9wZG93bj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG5cbmltcG9ydCB7IEFycm93RG93biB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBoYW5kbGVDbGljayA9ICgpID0+IHtcbiAgYWxlcnQoJ2J1dHRvbiBjbGljaycpXG59XG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9

### What is Expected?
不能弹出下拉菜单

### What is actually happening?
没有任何效果

**Comment by emojiiii** [comment] 2022-01-25 01:42
Duplicate of #4319

**Closed** 2022-01-25 01:42 UTC
Labels: bug, duplicate, Component: Dropdown
