### ISSUE TITLE
[Bug Report] dropdown divided item ::before missing style 'position:absolute'

### ISSUE THREAD

**Issue by jackjtr** [element-plus/element-plus#4699] opened 2021-12-07 01:38 UTC
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Windows 10, Chrome

### Vue version
3.2.24

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
https://element-plus.org/zh-CN/component/dropdown.html
#Basic usage

### What is Expected?
add position:absolute to .el-dropdown-menu__item--divided:before

### What is actually happening?
style error

**Comment by emojiiii** [comment] 2021-12-07 03:22
Duplicate of #4686

**Closed** 2021-12-09 03:23 UTC
