### ISSUE TITLE
[Component] [input-number] 数字框数字中间可以出现负号并且出现负号之后值变更时间获取到的新值与旧值是undefined

### ISSUE THREAD

**Issue by Mr-Run-Joker** [element-plus/element-plus#19249] opened 2024-12-12 09:39 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.10`
- Element Plus Version: `2.9.0`
- Browser / OS: `Chrome96.0.4664.45/mac0S12.0.1`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc3BhY2UgZGlyZWN0aW9uPVwidmVydGljYWxcIj5cbiAgICA8ZWwtc3BhY2U+XG4gICAgICA8ZWwtaW5wdXQtbnVtYmVyIHYtbW9kZWw9XCJudW1cIiAvPlxuICAgICAgPGVsLWlucHV0LW51bWJlciB2LW1vZGVsPVwibnVtXCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjZGVjcmVhc2UtaWNvbj5cbiAgICAgICAgICA8ZWwtaWNvbj5cbiAgICAgICAgICAgIDxBcnJvd0Rvd24gLz5cbiAgICAgICAgICA8L2VsLWljb24+XG4gICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgIDx0ZW1wbGF0ZSAjaW5jcmVhc2UtaWNvbj5cbiAgICAgICAgICA8ZWwtaWNvbj5cbiAgICAgICAgICAgIDxBcnJvd1VwIC8+XG4gICAgICAgICAgPC9lbC1pY29uPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgPC9lbC1pbnB1dC1udW1iZXI+XG4gICAgPC9lbC1zcGFjZT5cbiAgICA8ZWwtc3BhY2U+XG4gICAgICA8ZWwtaW5wdXQtbnVtYmVyIHYtbW9kZWw9XCJudW1cIiBjb250cm9scy1wb3NpdGlvbj1cInJpZ2h0XCIgLz5cbiAgICAgIDxlbC1pbnB1dC1udW1iZXIgdi1tb2RlbD1cIm51bVwiIGNvbnRyb2xzLXBvc2l0aW9uPVwicmlnaHRcIj5cbiAgICAgICAgPHRlbXBsYXRlICNkZWNyZWFzZS1pY29uPlxuICAgICAgICAgIDxlbC1pY29uPlxuICAgICAgICAgICAgPE1pbnVzIC8+XG4gICAgICAgICAgPC9lbC1pY29uPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8dGVtcGxhdGUgI2luY3JlYXNlLWljb24+XG4gICAgICAgICAgPGVsLWljb24+XG4gICAgICAgICAgICA8UGx1cyAvPlxuICAgICAgICAgIDwvZWwtaWNvbj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvZWwtaW5wdXQtbnVtYmVyPlxuICAgIDwvZWwtc3BhY2U+XG4gIDwvZWwtc3BhY2U+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgQXJyb3dEb3duLCBBcnJvd1VwLCBNaW51cywgUGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBudW0gPSByZWYoMSlcbjwvc2NyaXB0PiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

数字框中间输入-号和+号发现不会被清空
并且其他的框值不见了

### What is Expected?

中间的-+不能不输入或者通过change事件获取到的新旧跟旧值能有值

### What is actually happening?

数字中间的-+允许输入并且change事件获取到的值是undefined

### Additional comments

_(empty)_
![image](https://github.com/user-attachments/assets/c01b3365-5c99-4c05-b6a7-5837dc6cfbd9)

**Comment by hanchao-c0ldwave** [comment] 2024-12-12 10:11
设置value-on-clear属性可实现你想要的效果
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/5329e905-c687-461f-8f5f-4bbb66e5503d" />

**Comment by DDDDD12138** [comment] 2024-12-13 09:26
#16267

**Comment by btea** [comment] 2024-12-14 01:59
Duplicate of #16267

**Closed** 2024-12-14 02:00 UTC
