### ISSUE TITLE
[Style] [pagination] ElPagination组件的布局layout出问题，无法正常显示“->”之后的子组件

### ISSUE THREAD

**Issue by uestcNaldo** [element-plus/element-plus#10720] opened 2022-11-22 11:52 UTC
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8RWxQYWdpbmF0aW9uXG4gICAgYmFja2dyb3VuZFxuICAgIHYtbW9kZWw6Y3VycmVudC1wYWdlPVwiY3VycmVudFBhZ2VcIlxuICAgIHYtbW9kZWw6cGFnZS1zaXplPVwicGFnZVNpemVcIlxuICAgIDp0b3RhbD1cInRhYmxlRGF0YS5sZW5ndGhcIlxuICAgIDpwYWdlLXNpemVzPVwiWzEwLCAyMCwgNTBdXCJcbiAgICBsYXlvdXQ9XCJ0b3RhbCwgc2l6ZXMsIC0+LCBwcmV2LCBwYWdlciwgbmV4dCwganVtcGVyXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtyZWZ9IGZyb20gJ3Z1ZSdcbmNvbnN0IGN1cnJlbnRQYWdlID0gcmVmPG51bWJlcj4oMSlcbmNvbnN0IHBhZ2VTaXplID0gcmVmPG51bWJlcj4oMTApXG5jb25zdCB0YWJsZURhdGEgPSByZWYoW10pXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

ElPagination属性的layout中设置为"total, sizes, ->, prev, pager, next, jumper"

### What is Expected?

total、sizes在左边对齐，prev, pager, next, jumper在右边对齐

### What is actually happening?

->右边的子组件垂直排列

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/8793001/203307289-dbdaec41-7f7a-4009-9e54-173a4806132d.png)

**Comment by init-qy** [comment] 2022-11-23 01:54
Duplicate of #10664

**Closed** 2022-11-23 08:23 UTC
