### ISSUE TITLE
[Component] [table-column, table] 在el-table中使用show-overflow-tooltip属性时，文字被隐藏，但是popover浮框未触发

### ISSUE THREAD

**Issue by li-2021** [element-plus/element-plus#13234] opened 2023-06-15 11:51 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `谷歌最新版本浏览器/windows 10`
- Build Tool: `Vue CLI`

### Related Component

- `el-table-column`
- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGVcbiAgICByZWY9XCJtdWx0aXBsZVRhYmxlUmVmXCJcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgY2xhc3M9XCJ0YWJsZVwiXG4gID5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHR5cGU9XCJzZWxlY3Rpb25cIiB3aWR0aD1cIjU1XCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTIwXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPnt7IHNjb3BlLnJvdy5kYXRlIH19PC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIHNob3ctb3ZlcmZsb3ctdG9vbHRpcCB3aWR0aD1cIjIyMlwiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxUYWJsZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfVxuXVxuPC9zY3JpcHQ+XG48c3R5bGU+XG4gIC50YWJsZSB7XG4gICAgZm9udC1mYW1pbHk6IEhlbHZldGljYSBOZXVlLEhlbHZldGljYSxQaW5nRmFuZyBTQyxIaXJhZ2lubyBTYW5zIEdCLE1pY3Jvc29mdCBZYUhlaSxcXDVmYWVcXDhmNmZcXDk2YzVcXDllZDEsQXJpYWwsc2Fucy1zZXJpZjtcbiAgfVxuPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

将“Address”单元格宽度设置为222px，此时内部的 cell单元格元素为
<div class="cell el-tooltip" style="width: 220px;">No. 189, Grove St, Los Angeles</div>
此时单元格内容已被折叠，但是popover浮框无法出现。因为内部单元格cell宽度比el-table__cell小2px，不知道是不是el-tooltip宽度计算的问题

### What is Expected?

内容折叠时，正常出现popover浮框

### What is actually happening?

没有出现popover浮框

### Additional comments

极端情况就会触发（文字刚刚好比单元格多一点点的时候？），我觉得是内部cell计算得到的宽度比父元素table-cell小2px的原因

**Comment by btea** [comment] 2023-06-16 00:06
Duplicate of #12687

**Closed** 2023-06-16 00:06 UTC
