### ISSUE TITLE
[Component] [table, table-column] el-table内的show-overflow-tooltip属性,在windows的chrome浏览器内，会在文字没有溢出时，也会出现Tooltip 文字提示

### ISSUE THREAD

**Issue by xiaoxintiaoda** [element-plus/element-plus#16871] opened 2024-05-15 14:26 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.7.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlXG4gICAgcmVmPVwibXVsdGlwbGVUYWJsZVJlZlwiXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgIEBzZWxlY3Rpb24tY2hhbmdlPVwiaGFuZGxlU2VsZWN0aW9uQ2hhbmdlXCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIHdpZHRoPVwiNTVcIiBzaG93LW92ZXJmbG93LXRvb2x0aXAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxMjBcIiBzaG93LW92ZXJmbG93LXRvb2x0aXA+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPnt7IHNjb3BlLnJvdy5kYXRlIH19PC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTIwXCIgc2hvdy1vdmVyZmxvdy10b29sdGlwLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIHNob3ctb3ZlcmZsb3ctdG9vbHRpcCAvPlxuICA8L2VsLXRhYmxlPlxuICA8ZGl2IHN0eWxlPVwibWFyZ2luLXRvcDogMjBweFwiPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwidG9nZ2xlU2VsZWN0aW9uKFt0YWJsZURhdGFbMV0sIHRhYmxlRGF0YVsyXV0pXCI+XG4gICAgICBUb2dnbGUgc2VsZWN0aW9uIHN0YXR1cyBvZiBzZWNvbmQgYW5kIHRoaXJkIHJvd3NcbiAgICA8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInRvZ2dsZVNlbGVjdGlvbigpXCI+Q2xlYXIgc2VsZWN0aW9uPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsVGFibGUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmludGVyZmFjZSBVc2VyIHtcbiAgZGF0ZTogc3RyaW5nXG4gIG5hbWU6IHN0cmluZ1xuICBhZGRyZXNzOiBzdHJpbmdcbn1cblxuY29uc3QgbXVsdGlwbGVUYWJsZVJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsVGFibGU+PigpXG5jb25zdCBtdWx0aXBsZVNlbGVjdGlvbiA9IHJlZjxVc2VyW10+KFtdKVxuY29uc3QgdG9nZ2xlU2VsZWN0aW9uID0gKHJvd3M/OiBVc2VyW10pID0+IHtcbiAgaWYgKHJvd3MpIHtcbiAgICByb3dzLmZvckVhY2goKHJvdykgPT4ge1xuICAgICAgLy8gVE9ETzogaW1wcm92ZW1lbnQgdHlwaW5nIHdoZW4gcmVmYWN0b3IgdGFibGVcbiAgICAgIC8vIGVzbGludC1kaXNhYmxlLW5leHQtbGluZSBAdHlwZXNjcmlwdC1lc2xpbnQvYmFuLXRzLWNvbW1lbnRcbiAgICAgIC8vIEB0cy1leHBlY3QtZXJyb3JcbiAgICAgIG11bHRpcGxlVGFibGVSZWYudmFsdWUhLnRvZ2dsZVJvd1NlbGVjdGlvbihyb3csIHVuZGVmaW5lZClcbiAgICB9KVxuICB9IGVsc2Uge1xuICAgIG11bHRpcGxlVGFibGVSZWYudmFsdWUhLmNsZWFyU2VsZWN0aW9uKClcbiAgfVxufVxuY29uc3QgaGFuZGxlU2VsZWN0aW9uQ2hhbmdlID0gKHZhbDogVXNlcltdKSA9PiB7XG4gIG11bHRpcGxlU2VsZWN0aW9uLnZhbHVlID0gdmFsXG59XG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDgnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDYnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDcnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce
```
<template>
  <el-table
    ref="multipleTableRef"
    :data="tableData"
    style="width: 100%"
    @selection-change="handleSelectionChange"
  >
    <el-table-column type="selection" width="55" show-overflow-tooltip/>
    <el-table-column label="Date" width="120" show-overflow-tooltip>
      <template #default="scope">{{ scope.row.date }}</template>
    </el-table-column>
    <el-table-column property="name" label="Name" width="120" show-overflow-tooltip/>
    <el-table-column property="address" label="Address" show-overflow-tooltip />
  </el-table>
  <div style="margin-top: 20px">
    <el-button @click="toggleSelection([tableData[1], tableData[2]])">
      Toggle selection status of second and third rows
    </el-button>
    <el-button @click="toggleSelection()">Clear selection</el-button>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import { ElTable } from 'element-plus'

interface User {
  date: string
  name: string
  address: string
}

const multipleTableRef = ref<InstanceType<typeof ElTable>>()
const multipleSelection = ref<User[]>([])
const toggleSelection = (rows?: User[]) => {
  if (rows) {
    rows.forEach((row) => {
      // TODO: improvement typing when refactor table
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-expect-error
      multipleTableRef.value!.toggleRowSelection(row, undefined)
    })
  } else {
    multipleTableRef.value!.clearSelection()
  }
}
const handleSelectionChange = (val: User[]) => {
  multipleSelection.value = val
}

const tableData: User[] = [
  {
    date: '2016-05-03',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-02',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-04',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-01',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-08',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-06',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-07',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
]
</script>
```

### What is Expected?

文字没有溢出时，el-table-column设置show-overflow-tooltip为true时，不应该出现tool tip框，在windows10上的chrome会出现此问题，在macos的chrome是正常的

### What is actually happening?

在windows10上的chrome中，文字没有溢出时，el-table-column设置show-overflow-tooltip为true时，也出现了tool tip框

### Additional comments

_(empty)_

**Comment by xiaoxintiaoda** [comment] 2024-05-15 14:34
![Uploading 2024-05-15_223347.png…]()

**Comment by xiaoxintiaoda** [comment] 2024-05-15 14:35
![2024-05-15_223347](https://github.com/element-plus/element-plus/assets/11226606/cedb32f0-53c1-4ec4-af1b-e83832689cc7)

**Comment by btea** [comment] 2024-05-16 04:55
Duplicate of #16856

**Closed** 2024-05-16 04:55 UTC
