### ISSUE TITLE
[Bug Report] el-select multiple selection with object modelValue doesnt display correctly

### ISSUE THREAD

**Issue by Schewns** [element-plus/element-plus#7475] opened 2022-05-02 14:56 UTC
### Element Plus version
2.1.11

### OS/Browsers version
windows/Chrome

### Vue version
3.2.33

### Reproduction Link
https://tinyurl.com/3xukyfuk

### Steps to reproduce
create an el-select with multiple selection element that has an object list as model value
try to select

this is going on since version 2.1.7 (this is the last one that works properly)

### What is Expected?
expected tags with selected labels displayed

### What is actually happening?
actual: empty tags displayed

**Comment by btea** [comment] 2022-05-02 15:58
Duplicate of #7284

**Closed** 2022-05-02 15:59 UTC
