### ISSUE TITLE
[Bug Report] Pagination props 'total'

### ISSUE THREAD

**Issue by atpsoul** [element-plus/element-plus#4758] opened 2021-12-10 03:34 UTC
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
chorme 96.0.4664.93

### Vue version
3.2.24

### Reproduction Link
https://codepen.io/atpsoul/pen/WNZGbLJ

### Steps to reproduce
111

### What is Expected?
Total {total}

### What is actually happening?
Total 400

**Comment by emojiiii** [comment] 2021-12-10 03:58
Duplicate of #4617. Fix in #4619

**Closed by emojiiii** 2021-12-10 03:58 UTC
