### ISSUE TITLE
[Bug Report] select options 'v-for'; when the data(options) changes,  it will throw an error like "TypeError: Cannot read property '0' of null"

### ISSUE THREAD

**Issue by ChainsDW** [element-plus/element-plus#1074] opened 2020-12-22 03:34 UTC
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
macOS/chrome

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/chainsdw/pen/JjRyQjY

### Steps to reproduce
example in link, when the button is clicked, the options will change, but it will throw an error

### What is Expected?
.

### What is actually happening?
.

**Comment by BeADre** [comment] 2020-12-22 07:25
It seems working fine on my browser?

**Comment by ChainsDW** [comment] 2020-12-22 07:34
> It seems working fine on my browser?

sorry, the code of this link wasn't saved. now, the code was updated.

**Comment by BeADre** [comment] 2020-12-22 08:03
I saw this error, but I can't reproduce it locally. I think there may be other reasons that I haven't found

![image](https://user-images.githubusercontent.com/34639100/102863618-cd372780-446d-11eb-87b4-b42d894285b1.png)

**Comment by JeremyWuuuuu** [comment] 2020-12-22 08:14
This is cause by `Vue` itself, downgrade to 3.0.3, it will be fine. or upgrade to 3.0.5 (if they have released it).

**Comment by JeremyWuuuuu** [comment] 2020-12-22 08:15
Check this out https://github.com/vuejs/vue-next/issues/2737.
This is duplicate with #1061 So I am closing this.

**Closed by JeremyWuuuuu** 2020-12-22 08:15 UTC
