### ISSUE TITLE
v-loading not unwrap ref 

### ISSUE THREAD

**Issue by buaazs** [element-plus/element-plus#639] opened 2020-11-20 08:43 UTC
Template: <el-table  v-loading="loading" ...
loading is from inject:  inject: ['loading']
In parent component provide: 
 provide() {
      return {
        loading: computed(()=>this.loading)
      }
 }
The loading prop from provided is not working. Instead I have to create a new variable vloading to make it work:
<el-table  v-loading="vloading" ...
watch: {    
      ['loading.value'](val, old){
        this.vloading = val
      }
}

I'm not sure if it work as design, but it's kind of unconvenient

**Comment by JeremyWuuuuu** [comment] 2020-11-20 09:05
So, first thing of all, you **DO NOT MIX OPTIONS WITH COMPOSITION API**. This is the basic principle I think.
If you wish to get property from the upper layer. With `provide/inject` it should work fine.
in `parent.vue` you either do something like this:
```typescript
export default {
  setup() {
    provide() {
       loading: computed(() => loading)
    }
  }
}
```
or 

```typescript
export default {
  provide() {
    return {
      loading: this.loading,
    }
  }
}
```

**Comment by bastarder** [comment] 2020-11-20 09:09
agree with @JeremyWuuuuu ，
if you must use composition API in option mode, you shoud use `v-loading="loading.value"` not `v-loading="loading"` in child components, but i don't recommend it

**Comment by JeremyWuuuuu** [comment] 2020-11-20 09:15
NOTE that there are differences between Provide Option API and Provide Composition API

**Comment by JeremyWuuuuu** [comment] 2020-11-20 09:24
AS @bastarder mentioned. If you are using [provide option API](https://v3.vuejs.org/api/options-composition.html#provide-inject), and you have provided a `ComputedRef` down to the children, you will need to adding `.value` on the property in order to get it work. because you are actually providing a `ref`, instead of a `reactive`.

**Comment by JeremyWuuuuu** [comment] 2020-11-20 09:25
I am closing this issue due to it is not a bug of `ElementPlus`, feel free to reopen it.

**Closed by JeremyWuuuuu** 2020-11-20 09:25 UTC
Labels: wontfix

**Comment by buaazs** [comment] 2020-11-21 03:56
Thank you all. It's very kind of you all. Indeed I'm new to vue3 and not familiar with the reactive/ref/computeRef ...
