### ISSUE TITLE
Dialog show-close is invalid

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#771] opened 2020-12-02 05:00 UTC
Dialog show-close is invalid, when set `:show-close="false"`, still shows.

**Comment by JeremyWuuuuu** [comment] 2020-12-02 06:03
Thank you for being so actively giving us feedback, I personally am full of gratitude of that. This should be a bug that's caused by the previous change against dialog, and it will be fixed tonight. Thanks!

**Comment by Ther-su** [comment] 2020-12-02 06:12
Sorry, I did not see your self-assign before commited.

**Closed** 2020-12-02 09:14 UTC
Labels: bug
