### ISSUE TITLE
[Bug Report] Table column 's width in summary  will be averaged the total table width and not display with special value in attribute 'width'

### ISSUE THREAD

**Issue by runtop** [element-plus/element-plus#6151] opened 2022-02-18 08:50 UTC
### Element Plus version
2.0.2

### OS/Browsers version
win10 / chrome 98

### Vue version
3.2.31

### Reproduction Link
https://jsfiddle.net/dannyr/eudgpksm/5/

### Steps to reproduce
special some int value in [el-table-column] [width], but  column in summary bar will displayed by wrong width.

### What is Expected?
Table column 's width in summary  should be displayed with special value in attribute 'width'

### What is actually happening?
Table column 's width in summary  will be averaged the total table width and not display with special value in attribute 'width'

**Comment by msidolphin** [comment] 2022-02-18 09:05
Duplicate of https://github.com/element-plus/element-plus/issues/6059

**Closed by msidolphin** 2022-02-18 09:05 UTC
