### ISSUE TITLE
[Component] [dropdown] element-dropdown 内部包裹el-input，input无法触发键盘事件

### ISSUE THREAD

**Issue by Joey-Ren** [element-plus/element-plus#11260] opened 2023-01-12 09:54 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.19`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZHJvcGRvd24gOmhpZGUtb24tY2xpY2s9XCJmYWxzZVwiIHRyaWdnZXI9XCJjbGlja1wiPlxuICAgIDxzcGFuIGNsYXNzPVwiZWwtZHJvcGRvd24tbGlua1wiPlxuICAgICAgRHJvcGRvd24gTGlzdFxuICAgICAgPGVsLWljb24gY2xhc3M9XCJlbC1pY29uLS1yaWdodFwiPlxuICAgICAgICA8YXJyb3ctZG93biAvPlxuICAgICAgPC9lbC1pY29uPlxuICAgIDwvc3Bhbj5cbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICBcdDxlbC1pbnB1dCB2LW1vZGVsPVwiaW5wdXRWYWxcIj48L2VsLWlucHV0PlxuICAgICAgICA8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAyPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMzwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGlzYWJsZWQ+QWN0aW9uIDQ8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpdmlkZWQ+QWN0aW9uIDU8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgIHNldHVwPlxuICBpbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuICBpbXBvcnQgeyBBcnJvd0Rvd24gfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbiAgY29uc3QgaW5wdXRWYWwgPSByZWYoJycpXG4gXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZXhhbXBsZS1zaG93Y2FzZSAuZWwtZHJvcGRvd24tbGluayB7XG4gIGN1cnNvcjogcG9pbnRlcjtcbiAgY29sb3I6IHZhcigtLWVsLWNvbG9yLXByaW1hcnkpO1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1、点击el-dropdown
2、输入框输入英文等字符

### What is Expected?

双向数据绑定

### What is actually happening?

无法绑定数据

### Additional comments

_(empty)_

**Comment by Joey-Ren** [comment] 2023-01-12 09:54
比较着急，求值班大佬解决一下

**Comment by acyza** [comment] 2023-01-12 14:47
keydown事件到这被阻断了，连原生input都用不了
https://github.com/element-plus/element-plus/blob/dev/packages/components/dropdown/src/dropdown-menu.vue#L105

**Comment by btea** [comment] 2023-01-13 03:17
@Joey-Ren Perhaps you can use `el-popover` to achieve a similar effect. [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlciB0cmlnZ2VyPVwiY2xpY2tcIj5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICBcdDxzcGFuIGNsYXNzPVwiZWwtZHJvcGRvd24tbGlua1wiPlxuICAgICAgXHREcm9wZG93biBMaXN0XG4gICAgICBcdDxlbC1pY29uIGNsYXNzPVwiZWwtaWNvbi0tcmlnaHRcIj5cbiAgICAgICAgXHQ8YXJyb3ctZG93biAvPlxuICAgICAgXHQ8L2VsLWljb24+XG4gICAgXHQ8L3NwYW4+XHRcbiAgICA8L3RlbXBsYXRlPlxuICAgIDxkaXYgY2xhc3M9XCJjb250ZW50XCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0VmFsXCI+PC9lbC1pbnB1dD5cbiAgICAgIDxkaXYgY2xhc3M9XCJpdGVtXCI+QWN0aW9uMTwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIml0ZW1cIj5BY3Rpb24xPC9kaXY+XG4gICAgPC9kaXY+XG4gIDwvZWwtcG9wb3Zlcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgIHNldHVwPlxuICBpbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuICBpbXBvcnQgeyBBcnJvd0Rvd24gfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbiAgY29uc3QgaW5wdXRWYWwgPSByZWYoJycpXG4gXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZXhhbXBsZS1zaG93Y2FzZSAuZWwtZHJvcGRvd24tbGluayB7XG4gIGN1cnNvcjogcG9pbnRlcjtcbiAgY29sb3I6IHZhcigtLWVsLWNvbG9yLXByaW1hcnkpO1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by Joey-Ren** [comment] 2023-01-13 06:02
> 

Yes, that's what I'm doing right now，use el-popover to achieve a similar effect，Thank you very much

**Comment by Joey-Ren** [comment] 2023-01-13 06:05
> keydown事件到这被阻断了，连原生input都用不了 https://github.com/element-plus/element-plus/blob/dev/packages/components/dropdown/src/dropdown-menu.vue#L105

嗯嗯，还是希望看官方能不能修复一下这个问题，又或者是我们使用的场景跟官方当时设计组件的初衷有点背离，目前使用el-popover替换掉现在的el-dropdown先解决了线上问题

**Comment by ReWWeR** [comment] 2023-02-02 09:40
Same issue here. Is it expected in the future that it will be fixed?

**Comment by loosheng** [comment] 2023-02-05 08:44
@jw-foss Why do you do this and does removing it cause problems?
I deleted the line and ran the tests, and they all passed.

https://github.com/element-plus/element-plus/blob/6799618f79ad7c7bbc776094376ab2d830b1c86d/packages/components/dropdown/src/dropdown-menu.vue?rgh-link-date=2023-01-13T06%3A05%3A40Z#L105

**Comment by jw-foss** [comment] 2023-02-06 12:21
> @jw-foss Why do you do this and does removing it cause problems? I deleted the line and ran the tests, and they all passed.
> 
> https://github.com/element-plus/element-plus/blob/6799618f79ad7c7bbc776094376ab2d830b1c86d/packages/components/dropdown/src/dropdown-menu.vue?rgh-link-date=2023-01-13T06%3A05%3A40Z#L105

I'll look into the root cause and hopefully fix this for you, sorry for taking this long to reply. :bow:

**Comment by jw-foss** [comment] 2023-02-06 14:40
I think I know why this is happening, the original idea behind this was that I want to capture `keydown` event which occurs on the `ul` element, and I mistakenly forgot about adding a `self` modifier that captures propagated `keydown` events bubbling from the descendent nodes.

I just made a [patch](https://github.com/element-plus/element-plus/pull/11431) for fixing issue, sorry for all the troubles I caused. :bow:

**Comment by jw-foss** [comment] 2023-02-07 13:56
This will be released on 10th Feb , 2023 GMT+8

**Closed** 2023-02-07 13:56 UTC
