### ISSUE TITLE
Position of 'form-item-error'

### ISSUE THREAD

**Issue by Aohonze** [element-plus/element-plus#880] opened 2020-12-08 05:44 UTC
I found that currently our 'form-item-error' style is adsoluted. So, if our error message is long enough so that can't display by only one line, then it may occupy the space of form-item, or even overlapping with the label of next form item. But we really want is flex-grow the margin of each form item. So, I suggest that delete the position setting of 'form-item-error'. First time to open an issue, and hope for reply, thanks a lot!
```
 @include e(error) {
    color: $--color-danger;
    font-size: 12px;
    line-height: 1;
    padding-top: 4px;
    position: absolute;
    top: 100%;
    left: 0;
```
**Currently setting**
![image](https://user-images.githubusercontent.com/54461992/101444813-507b5800-395b-11eb-9aa0-fc87b55b4808.png)
 **What we need**
![image](https://user-images.githubusercontent.com/54461992/101444875-7274da80-395b-11eb-9d0a-520a9f6de1b8.png)

**Comment by Ryan2128** [comment] 2020-12-08 08:13
I think this demand is reasonable. It will be fixed in next version.

**Comment by bastarder** [comment] 2020-12-08 09:16
> I think this demand is reasonable. It will be fixed in next version.

i don't agree with this, because if error dom have height, when the input change from 'normal' to 'error', the page will 'flash'.

**Comment by JeremyWuuuuu** [comment] 2020-12-08 09:18
This was there and working fine in v2.x, but it looked weird in v3.x, then I think it could be a styling bug. But the solution is not removing the style rule,  instead of make it correct.

**Comment by Tyrone-Wu** [comment] 2020-12-08 09:26
> > I think this demand is reasonable. It will be fixed in next version.
> 
> i don't agree with this, because if error dom have height, when the input change from 'normal' to 'error', the page will 'flash'.
But just like we need a lot of dynamic form item, I think it could be ok?

**Comment by Ryan2128** [comment] 2020-12-08 09:28
I think the position change of the form item is acceptable compared to what it is now.

**Comment by JeremyWuuuuu** [comment] 2020-12-08 09:31
Well, the first thing that I wanted to say is that, the current implementation is clearly not `modern` enough to me, we still uses `float` in the stylesheets in which case `Vue` does not support `IE11` in the main version (except the compat one). Dynamic form item is a very common requirement in business view.

**Comment by JeremyWuuuuu** [comment] 2020-12-08 09:31
And in this case this is caused by `el-popper` instead of the `style rule` you have mentioned there. I will be taking responsibility on this.

**Comment by JeremyWuuuuu** [comment] 2020-12-08 09:32
This one will be fixed ASAP.

**Comment by Ryan2128** [comment] 2020-12-08 09:37
@JeremyWuuuuu Do you want to replace the current display mode with popper? In this case you can assign to you.

**Comment by bastarder** [comment] 2020-12-08 09:49
> > > I think this demand is reasonable. It will be fixed in next version.
> > 
> > 
> > i don't agree with this, because if error dom have height, when the input change from 'normal' to 'error', the page will 'flash'.
> 
> But just like we need a lot of dynamic form item, I think it could be ok?

in this case may be use your own style is better, such as 
```
.el-form.my-own-class{}
```

**Comment by Tyrone-Wu** [comment] 2020-12-08 09:56
> > > > I think this demand is reasonable. It will be fixed in next version.
> > > 
> > > 
> > > i don't agree with this, because if error dom have height, when the input change from 'normal' to 'error', the page will 'flash'.
> > 
> > 
> > But just like we need a lot of dynamic form item, I think it could be ok?
> 
> in this case may be use your own style is better, such as
> 
> ```
> .el-form.my-own-class{}
> ```


Yes, thanks! I just change the `.vi-form-item__error` position style 'absolute' to 'relative', and then I can make the error info more Customization.

**Comment by JeremyWuuuuu** [comment] 2020-12-10 03:19
After. we discussed with designers, the principle of the design here is, the shorter the error message the better, so the suggestion here is either you use style overriding technic to do so, or shorten the error message would be a good idea.

**Comment by JeremyWuuuuu** [comment] 2020-12-10 03:20
The original idea is that we keep error messages as simple as it can be.

**Closed** 2021-06-18 16:11 UTC
Labels: needs discussion
