### ISSUE TITLE
[Bug Report] When change the select's value and  select's options in the same time, the show is not work for expected

### ISSUE THREAD

**Issue by XingXiaoWu** [element-plus/element-plus#1207] opened 2021-01-06 06:19 UTC
### Element Plus version
1.0.1-beta.20

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/xingxiaowu/pen/jOMxJbb

### Steps to reproduce
1.change the select2's value
2.change the select1's value

### What is Expected?
select2's value is '', and show ''

### What is actually happening?
select2's value is '', but show old's value

**Comment by JeremyWuuuuu** [comment] 2021-01-06 06:27
I am assigning this issue to @Ryan2128 .

**Comment by Ryan2128** [comment] 2021-01-06 17:18
I can not reproduction it, either using `1.0.1-beta.1` or `1.0.1-beta.22`.

You can check this [reproduction](https://codesandbox.io/s/vibrant-neumann-iyjy0?file=/src/App.vue).

@XingXiaoWu

**Comment by XingXiaoWu** [comment] 2021-01-07 03:09
> I can not reproduction it both in `1.0.1-beta.1` and `1.0.1-beta.22`.
> 
> You can check this [reproduction](https://codesandbox.io/s/vibrant-neumann-iyjy0?file=/src/App.vue).
> 
> @XingXiaoWu

Sorry,I don't know why it's working in CodeSandBox.
But I try the same code from CodeSandBox in my local computer, it's not work.
Can you check this [reproduction](https://github.com/XingXiaoWu/element-test) in your local computer？

**Comment by JeremyWuuuuu** [comment] 2021-01-07 03:36
Confirmed as reproducible.

**Comment by JeremyWuuuuu** [comment] 2021-01-07 12:56
The issue is like caused by `Vue`, we need to wait for the fix from them. The current reasonable fix would all be temporary fix. Let's keep this on hold.

**Comment by Ryan2128** [comment] 2021-01-18 02:47
[vue 3 #2768](https://github.com/vuejs/vue-next/issues/2768)
[vue 3 #2829](https://github.com/vuejs/vue-next/issues/2829)

**Comment by duansheli** [comment] 2021-02-19 03:57
@JeremyWuuuuu 事件触发的bug 

## 说明
绑定事件时，vue格式的事件正常执行
tsx格式的 触发不正常

* Test1good.vue
* Test2bad.vue

vue: 输入框输入任意字符，失去焦点后，change blur 都能触发
tsx: 每输入一个字符，change blur 触发一次 

## good code
```vue
<template>
  <el-form label-width="80px">
    <el-form-item label="good-test">
      <el-input
        v-model="sname"
        @blur="onblur(sname)"
        @change="onchange(sname)"
      />
    </el-form-item>
  </el-form>
</template>
<script setup lang="ts">
/**
 * 失去焦点后才触发
 */
import { computed, getCurrentInstance, ref } from "vue";
const sname = ref("good");
function onchange(a) {
  console.log("onchange-", a);
}
function onblur(a) {
  console.log("onblur-", a);
}
</script>
 
```

## bad code

```tsx
import { defineComponent, ref } from "vue";

function onchange(a) {
  console.log("onchange-", a);
}
function onblur(a) {
  console.log("onblur-", a);
}

export default defineComponent({
  setup() {
    /**
     * 只要修改就会触发
     */
    const sname = ref("bad");

    return () => (<>
      <el-form label-width="80px">
        <el-form-item label="test-bad">
          <el-input v-model={sname.value}
            blur={onchange(sname.value)}
            change={onblur(sname.value)}
          />
        </el-form-item>
      </el-form>
    </>)
  }
})
```

**Comment by duansheli** [comment] 2021-02-19 05:46
@JeremyWuuuuu 
## bad code 

```vue
<script lang="tsx">
import { defineComponent, ref } from "vue";
const sname = ref("good");
function onchange(a) {
  console.log("onchange-", a);
}
function onblur(a) {
  console.log("onblur-", a);
}
export default defineComponent({
  setup() {
    /**
     * 只要修改就会触发
     */
    const sname = ref("bad2");

    return () => (
      <el-form>
        <el-form-item label="test-bad">
          <el-input
            v-model={sname.value}
            blur={onchange(sname.value)}
            change={onblur(sname.value)}
          />
        </el-form-item>
      </el-form>
    );
  },
});
</script>
 
```

**Comment by Ryan2128** [comment] 2021-03-02 01:24
Vue 3.0.7 has released. If still has problem, please reopen issue.

**Closed by Ryan2128** 2021-03-02 01:24 UTC
Labels: bug, 🔨 Vue bug
