### ISSUE TITLE
[Bug Report] Pagination中文情况下默认显示英文文字

### ISSUE THREAD

**Issue by filusilia** [element-plus/element-plus#5083] opened 2021-12-31 07:07 UTC
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
windows

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/9tx3fr65/

### Steps to reproduce
默认情况下

### What is Expected?
Works normally

### What is actually happening?
使用中文包默认应显示中文文字

**Comment by emojiiii** [comment] 2021-12-31 07:51
can you provide a mini repo ?

**Comment by filusilia** [comment] 2021-12-31 08:27
问题应该与
https://github.com/element-plus/element-plus/issues/5078
的原因相同

**Comment by emojiiii** [comment] 2021-12-31 08:29
Duplicate of #5078

**Closed** 2021-12-31 08:29 UTC
Labels: duplicate, Component: Pagination
