### ISSUE TITLE
[Component] [radio-group, radio-button] el-radio-button style is not controlled

### ISSUE THREAD

**Issue by joooooooojo** [element-plus/element-plus#17393] opened 2024-07-03 06:54 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.6`
- Browser / OS: `e.g. Edge 126.0.2592.81  / macOS 14.5`
- Build Tool: `Vite`

### Related Component

- `el-radio-group`
- `el-radio-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IGEgPSByZWYoMCk7XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICAgPGVsLXJhZGlvLWdyb3VwIDptb2RlbC12YWx1ZT1cImFcIj5cbiAgICAgIDxlbC1yYWRpby1idXR0b24gOmxhYmVsPVwiMVwiIDp2YWx1ZT1cIjBcIiAvPlxuICAgICAgPGVsLXJhZGlvLWJ1dHRvbiA6bGFiZWw9XCIyXCIgOnZhbHVlPVwiMVwiIC8+XG4gICAgICA8ZWwtcmFkaW8tYnV0dG9uIDpsYWJlbD1cIjNcIiA6dmFsdWU9XCIyXCIgLz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuICAgIDxici8+XG4gICAgPGVsLXJhZGlvLWdyb3VwIDptb2RlbC12YWx1ZT1cImFcIj5cbiAgICAgIDxlbC1yYWRpbyA6bGFiZWw9XCIxXCIgOnZhbHVlPVwiMFwiIC8+XG4gICAgICA8ZWwtcmFkaW8gOmxhYmVsPVwiMlwiIDp2YWx1ZT1cIjFcIiAvPlxuICAgICAgPGVsLXJhZGlvIDpsYWJlbD1cIjNcIiA6dmFsdWU9XCIyXCIgLz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

click any el-raido-button component

### What is Expected?

Without @update:modelValue the selected value of the component should remain unchanged and the style should not change, just like el-radio

### What is actually happening?

The value does not change, but the selected style disappears

### Additional comments

_(empty)_

**Comment by makedopamine** [comment] 2024-07-04 08:44
Duplicate of #16689

**Closed** 2024-07-04 12:22 UTC
Labels: duplicate
