### ISSUE TITLE
there  are error  in   el-pagination  of    Total {total}

### ISSUE THREAD

**Issue by jzfai** [element-plus/element-plus#4632] opened 2021-12-02 07:16 UTC
look for   https://element-plus.gitee.io/zh-CN/component/pagination.html#附加功能

![image](https://user-images.githubusercontent.com/35098590/144375554-50005d3e-01c9-406b-b6c6-7c940a8cb470.png)

**Comment by btea** [comment] 2021-12-02 07:29
Duplicate #4617

**Comment by sxzz** [comment] 2021-12-02 12:53
Duplicate of #4617. Fix in #4619

**Closed** 2021-12-02 12:53 UTC
