### ISSUE TITLE
[Feature Request] [New Component] [] 希望增加个treeSelect组件

### ISSUE THREAD

**Issue by github-ZH-cn** [element-plus/element-plus#6969] opened 2022-04-02 05:34 UTC
Feature type: **`New Component`**

## Details

- New component name: `treeSelect`

## Description

希望组件库增加treeSelect组件,这个组件需求真的很大啊

### Additional comments

_(empty)_

**Comment by Cheerwhy** [comment] 2022-04-02 12:05
强烈同意  其他组件库都有树选择了

**Comment by yandixuan** [comment] 2022-04-02 12:10
just look at this
https://github.com/element-plus/element-plus/pull/6843

**Comment by cjq02** [comment] 2022-04-04 06:50
> just look at this #6843

good!!!

**Comment by buqiyuan** [comment] 2022-04-04 16:33
Duplicate of #6887

**Closed by buqiyuan** 2022-04-04 16:33 UTC
Labels: duplicate
