### ISSUE TITLE
[Component] [radio-button, radio] 绑定 undefined或者 null 值，控制台报ElementPlusError 和 Vue warn 警告

### ISSUE THREAD

**Issue by elkon028** [element-plus/element-plus#18434] opened 2024-10-02 03:46 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.10`
- Element Plus Version: `2.8.4`
- Browser / OS: `System:     OS: macOS 14.6.1     CPU: (14) arm64 Apple M3 Max     Memory: 1.41 GB / 36.00 GB     Shell: 5.9 - /bin/zsh   Binaries:     Node: 20.16.0 - /usr/local/bin/node     npm: 10.8.2 - /usr/local/bin/npm     pnpm: 9.11.0 - /usr/local/bin/pnpm     Watchman: 2024.09.02.00 - /opt/homebrew/bin/watchman   Browsers:     Chrome: 129.0.6668.70     Safari: 17.6`
- Build Tool: `Vite`

### Related Component

- `el-radio-button`
- `el-radio`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsUmFkaW9Hcm91cCwgRWxSYWRpb0J1dHRvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7cmVmfSBmcm9tICd2dWUnXG5cbmNvbnN0IHBhcmFtID0gcmVmKHtzdGF0dXM6IHVuZGVmaW5lZCwgc3RhdGU6IG51bGx9KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJwYXJhbS5zdGF0dXNcIj5cbiAgICA8ZWwtcmFkaW8tYnV0dG9uPuS4jemZkDwvZWwtcmFkaW8tYnV0dG9uPlxuICAgIDxlbC1yYWRpby1idXR0b24gOnZhbHVlPVwidHJ1ZVwiPuaIkOWKnzwvZWwtcmFkaW8tYnV0dG9uPlxuICAgIDxlbC1yYWRpby1idXR0b24gOnZhbHVlPVwiZmFsc2VcIj7lpLHotKU8L2VsLXJhZGlvLWJ1dHRvbj5cbiAgPC9lbC1yYWRpby1ncm91cD5cbiAgPGJyPlxuICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInBhcmFtLnN0YXRlXCI+XG4gICAgPGVsLXJhZGlvLWJ1dHRvbiA6dmFsdWU9XCJudWxsXCI+5LiN6ZmQPC9lbC1yYWRpby1idXR0b24+XG4gICAgPGVsLXJhZGlvLWJ1dHRvbiA6dmFsdWU9XCJ0cnVlXCI+5oiQ5YqfPC9lbC1yYWRpby1idXR0b24+XG4gICAgPGVsLXJhZGlvLWJ1dHRvbiA6dmFsdWU9XCJmYWxzZVwiPuWksei0pTwvZWwtcmFkaW8tYnV0dG9uPlxuICA8L2VsLXJhZGlvLWdyb3VwPlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script setup>
function useFetchData() {
  const param = reactive({ status: undefined })

  const fetchData = async () => {
    // ...
  }

  return { fetchData, param }
}

const { fetchData, param } = useFetchData()

onMounted(() => {
  fetchData()
})
<template>
<el-radio-group v-model="param.status" @change="fetchData()">
  <el-radio-button :value="undefined">不限</el-radio-button>
  <el-radio-button :value="true">成功</el-radio-button>
  <el-radio-button :value="false">失败</el-radio-button>
</el-radio-group>
</template>
```

### What is Expected?

- 希望el-radio:value 允许 undefined 或者 null，且可以被选中状态
```vue
<el-radio-group v-model="param.status" @change="fetchData()">
  <el-radio-button :value="undefined">不限</el-radio-button>
  <el-radio-button :value="true">成功</el-radio-button>
  <el-radio-button :value="false">失败</el-radio-button>
</el-radio-group>
<el-radio-group v-model="param.status" @change="fetchData()">
  <el-radio-button :value="null">不限</el-radio-button>
  <el-radio-button :value="true">成功</el-radio-button>
  <el-radio-button :value="false">失败</el-radio-button>
</el-radio-group>

<el-radio-group v-model="param.status" @change="fetchData()">
  <el-radio-button>不限</el-radio-button>
  <el-radio-button :value="true">成功</el-radio-button>
  <el-radio-button :value="false">失败</el-radio-button>
</el-radio-group>
```

### What is actually happening?

```error
ElementPlusError: [el-radio] [API] label act as value is about to be deprecated in version 3.0.0, please use value instead.

[Vue warn]: Invalid event arguments: event validation failed for event "update:modelValue".

[Vue warn]: Invalid event arguments: event validation failed for event "change".
```

### Additional comments

_(empty)_

**Comment by zc-tired** [comment] 2024-10-11 07:26
#18504 参考这个解决一下就好了

**Comment by btea** [comment] 2024-10-13 01:36
This is a duplicate of #18504. I will close this issue so that everyone can discuss it in the same place.

**Closed by btea** 2024-10-13 01:36 UTC
