### ISSUE TITLE
[Component] [select] el-select 宽度丢失！！！

### ISSUE THREAD

**Issue by lxfljw** [element-plus/element-plus#16152] opened 2024-03-15 10:54 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.0`
- Browser / OS: `macos 12`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignZWwtc2VsZWN05a695bqm5Lii5aSxJylcbmNvbnN0IHZhbCA9IHJlZignMScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWZvcm0gIGlubGluZT5cbiAgPGVsLWZvcm0taXRlbT5cbiAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWxcIj5cbiAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiMVwiIHZhbHVlPVwiMVwiIC8+XG4gICAgPGVsLW9wdGlvbiBsYWJlbD1cIjJcIiB2YWx1ZT1cIjJcIiAvPlxuICA8L2VsLXNlbGVjdD5cbiAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cblxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

el-form inline 模式 el-select 默认宽度丢失，严重线上 bug！！！

### What is Expected?

恢复 2.3.8 版本的 el-select 默认宽度

### What is actually happening?

el-select 宽度缩减，破坏布局！

### Additional comments

建议这种破坏改动留到下一个 Major，否则真的打破大家对饿了么的好印象

**Comment by warmthsea** [comment] 2024-03-15 12:06
在前段时间项目升级中我也注意到了这个问题

**Comment by btea** [comment] 2024-03-15 13:30
Duplicate of #15510

**Closed** 2024-03-15 13:30 UTC
