### ISSUE TITLE
[Component] [input-number] 最新版element-plus v2.7.5，数字输入框火狐浏览器能输入数字意外的字符

### ISSUE THREAD

**Issue by ChenxiangCat** [element-plus/element-plus#17471] opened 2024-07-09 07:50 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.5`
- Browser / OS: `Firefox 127.0.2`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input-number.html)

### Steps to reproduce

用火狐浏览器打开官网，数字输入框输入数字以外的字符

### What is Expected?

不能输入数字以外的字符

### What is actually happening?

能输入数字以外的字符

### Additional comments

_(empty)_

**Comment by btea** [comment] 2024-07-09 14:17
Duplicate of #17038

**Closed** 2024-07-09 14:17 UTC
