### ISSUE TITLE
el-option 使用报错 

### ISSUE THREAD

**Issue by lebron112** [element-plus/element-plus#694] opened 2020-11-25 09:17 UTC
![image](https://user-images.githubusercontent.com/20268396/100207882-106faa80-2f43-11eb-8553-c76beda19f2f.png)
![image](https://user-images.githubusercontent.com/20268396/100207907-16658b80-2f43-11eb-8650-0edee93b4b8d.png)
当有数据时报的是 Cannot read property 'optionsCount' of undefined
点击选择时报的是 TypeError: Cannot read property 'emitsOptions' of null
![image](https://user-images.githubusercontent.com/20268396/100208309-8c69f280-2f43-11eb-89c5-73e4040d2583.png)

**Comment by JeremyWuuuuu** [comment] 2020-11-25 09:19
Could you run the command 
```shell
$ cat node_modules/vue/package.json | grep version
```
And paste the result here?

**Comment by lebron112** [comment] 2020-11-25 09:25
@JeremyWuuuuu  "version": "3.0.2"

**Comment by JeremyWuuuuu** [comment] 2020-11-25 09:44
Alright, before I can do the investigation, would you mind providing a demo code or link to us? Without a minimal reproducible mode I might not be able to debug.

**Comment by JeremyWuuuuu** [comment] 2020-11-25 10:01
This could be related to #693 , what env you were running then? Production (meaning compiled code) or dev (meaning with dev server)

**Comment by lebron112** [comment] 2020-11-25 10:02
@JeremyWuuuuu with dev

**Comment by JeremyWuuuuu** [comment] 2020-11-25 10:04
I had a peek on the code I saw this error was caused by:
![image](https://user-images.githubusercontent.com/15975785/100212606-8591ae80-2f48-11eb-8417-417deaaf091f.png)
The line of incrementing `optionsCount`, I will do the further investigation on my machine later. Thank you for being cooperative. I'll fix this ASAP

**Comment by lebron112** [comment] 2020-11-26 01:31
> I had a peek on the code I saw this error was caused by:
> ![image](https://user-images.githubusercontent.com/15975785/100212606-8591ae80-2f48-11eb-8417-417deaaf091f.png)
> The line of incrementing `optionsCount`, I will do the further investigation on my machine later. Thank you for being cooperative. I'll fix this ASAP

list changed: Cannot read property 'optionsCount' of undefined
click select: TypeError: Cannot read property 'emitsOptions' of null

**Comment by JeremyWuuuuu** [comment] 2020-11-26 02:04
Alright, I'm going to try to find the bug and fix it, should not take so long.

**Comment by lebron112** [comment] 2020-11-26 06:25
> Alright, I'm going to try to find the bug and fix it, should not take so long.

pagination user select that cannot be used to switch page sizes

**Comment by JeremyWuuuuu** [comment] 2020-11-27 04:06
Fixed in #709

**Closed by JeremyWuuuuu** 2020-11-27 04:06 UTC
Labels: bug

**Comment by zazzaz** [comment] 2020-11-27 05:09
fixed in 1.0.1-alpha.23
