### ISSUE TITLE
[Bug Report] The table format is incorrect when the end tag is not used

### ISSUE THREAD

**Issue by HMWCS** [element-plus/element-plus#4278] opened 2021-11-07 16:37 UTC
### Element Plus version
1.2.0-beta.2

### OS/Browsers version
95.0.4638.54

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/HMWCS/pen/oNeqrxr

### Steps to reproduce
1. Open the reproduction link
2. The table turned into a wrong format with 7 rows and 1 column
3. Add end tag to each HTML element (e.g. change "<el-table-column />" to "<el-table-column></el-table-column>")
4. The table turned into the correct format which has 5 rows and 3 columns

### What is Expected?
The table should have 5 rows and 3 columns as follows:

-------------------------------------------------------------------------------
Date               Name       Address
-------------------------------------------------------------------------------
2016-05-03    Tom          No. 189, Grove St, Los Angeles
-------------------------------------------------------------------------------
2016-05-02    Tom          No. 189, Grove St, Los Angeles
-------------------------------------------------------------------------------
2016-05-04    Tom          No. 189, Grove St, Los Angeles
-------------------------------------------------------------------------------
2016-05-01    Tom          No. 189, Grove St, Los Angeles

### What is actually happening?
The table wrongly turned into a table with 7 rows and 1 column table as follows:

------------------------------------------
Date
------------------------------------------
Name
------------------------------------------
Address
------------------------------------------
No. 189, Grove St, Los Angeles
------------------------------------------
No. 189, Grove St, Los Angeles
------------------------------------------
No. 189, Grove St, Los Angeles
------------------------------------------
No. 189, Grove St, Los Angeles
------------------------------------------

**Comment by HMWCS** [comment] 2021-11-07 16:48
Step 2 image: 
![image](https://user-images.githubusercontent.com/92188165/140653965-aab31e36-e54e-444b-bfdd-a01826da08bc.png)

Step 3: Add end tag to each HTML element (e.g. change `<el-table-column />` to `<el-table-column></el-table-column>`

**Comment by msidolphin** [comment] 2021-11-08 00:53
Can you reproduce this problem in platforms other than codepen, i think it's cause by codepen.

When I don't use the self-closing tag, it seems to behave normally
![image](https://user-images.githubusercontent.com/26672484/140668953-47ebb10c-1ad6-4ef3-ad10-3b904ca43682.png)

**Comment by HMWCS** [comment] 2021-11-08 01:25
> Can you reproduce this problem in platforms other than codepen, i think it's cause by codepen.

Hello, thank you for your reply, I have reproduced this problem on another platform which is JSFiddle, the link is https://jsfiddle.net/1zt3kfbq/

In addition, this problem occurs on my own computer as well, so I think this is probably a bug instead of some problems caused by CodePen. And yeah, I think this bug is caused by using the self-closing tag. As I mentioned in my reproduction steps, when I add the end tag, the table can display correctly.

**Comment by msidolphin** [comment] 2021-11-08 02:27
@element-plus/backers Is anyone can reproduce this issue?

**Comment by msidolphin** [comment] 2021-11-08 02:28
> > Can you reproduce this problem in platforms other than codepen, i think it's cause by codepen.
> 
> Hello, thank you for your reply, I have reproduced this problem on another platform which is JSFiddle, the link is https://jsfiddle.net/1zt3kfbq/
> 
> In addition, this problem occurs on my own computer as well, so I think this is probably a bug instead of some problems caused by CodePen. And yeah, I think this bug is caused by using the self-closing tag. As I mentioned in my reproduction steps, when I add the end tag, the table can display correctly.

Can you provide details of your environment?

**Comment by HMWCS** [comment] 2021-11-08 02:34
> > > Can you reproduce this problem in platforms other than codepen, i think it's cause by codepen.
> > 
> > 
> > Hello, thank you for your reply, I have reproduced this problem on another platform which is JSFiddle, the link is https://jsfiddle.net/1zt3kfbq/
> > In addition, this problem occurs on my own computer as well, so I think this is probably a bug instead of some problems caused by CodePen. And yeah, I think this bug is caused by using the self-closing tag. As I mentioned in my reproduction steps, when I add the end tag, the table can display correctly.
> 
> Can you provide details of your environment?

Hello, my environment is Chrome Version 95.0.4638.54 - Windows 10 Version 10.0.19042 Build 19042, Element Plus version 1.2.0-beta.2, and Vue version 3.2.21, thanks

**Comment by msidolphin** [comment] 2021-11-08 04:31
> > > > Can you reproduce this problem in platforms other than codepen, i think it's cause by codepen.
> > > 
> > > 
> > > Hello, thank you for your reply, I have reproduced this problem on another platform which is JSFiddle, the link is https://jsfiddle.net/1zt3kfbq/
> > > In addition, this problem occurs on my own computer as well, so I think this is probably a bug instead of some problems caused by CodePen. And yeah, I think this bug is caused by using the self-closing tag. As I mentioned in my reproduction steps, when I add the end tag, the table can display correctly.
> > 
> > 
> > Can you provide details of your environment?
> 
> Hello, my environment is Chrome Version 95.0.4638.54 - Windows 10 Version 10.0.19042 Build 19042, Element Plus version 1.2.0-beta.2, and Vue version 3.2.21, thanks

This seems to be an issue with vue, when I try to using self-close with a custom component, it triggers a similar problem
![image](https://user-images.githubusercontent.com/26672484/140684597-bef77006-7b5a-494c-a595-65a2ca131009.png)
```js
const Custom = {
  name: 'custom',
  render () {
    return Vue.h('div', 'custom')
  }
}
```

**Comment by msidolphin** [comment] 2021-11-08 04:40
This issue is mentioned in the documentation

https://vuejs.org/v2/style-guide/index.html#Self-closing-components-strongly-recommended

**Closed** 2021-11-08 05:04 UTC
