### ISSUE TITLE
Select - not displaying label, display id instead

### ISSUE THREAD

**Issue by ntgraph** [element-plus/element-plus#666] opened 2020-11-24 00:44 UTC
Select should display label, but it display value.  This happen where there are multiple select and multiple sources on the same page.

**Comment by JeremyWuuuuu** [comment] 2020-11-24 01:01
Could you give us a minimal reproducible code and a screenshot plz?

**Comment by Ryan2128** [comment] 2020-11-24 01:39
Do you mean this? #637

**Comment by JeremyWuuuuu** [comment] 2020-11-24 12:17
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Closed by JeremyWuuuuu** 2020-11-24 12:17 UTC

**Comment by ntgraph** [comment] 2020-11-25 13:51
Here is the code, provinces2 is the sort of data coming back for endpoint.
city.province_id with match the id coming provinces.
If I put provinces2 instead of province, the select display correctly,
but if the select wait for the data to come from the endpoint, there is the problem of display the city.province_id


``` <label
                for="countryName"
                class="block text-left pt-4 pb-2"
                :class="{required: countryNameRequired}"
            >
                {{ $t('city.countryName')}}
            </label>
            <div class="sm:w-full md:w-3/5 lg:w-2/5">
                <el-select
                    v-model="city.country_id"
                    :placeholder="$t('city.selectCountry')"
                    class="w-full administration"
                    @change="onCountryChange"
                >
                    <el-option
                        v-for="item in countries"
                        :key="`country-${item.id}`"
                        :label="item[getCountry]"
                        :value="item.id">
                        <span style="float: left" class="administration">{{ item[getCountry] }}</span>
                    </el-option>
                </el-select>
            </div>
            <label
                for="provinceName"
                class="block text-left pt-4 pb-2"
                :class="{required: provinceNameRequired}"
            >
                {{ $t('city.provinceName')}}
            </label>
            <div class="sm:w-full md:w-3/5 lg:w-2/5">
                <el-select v-model="city.province_id" :placeholder="$t('city.selectProvince')" class="w-full administration" :disabled="!city.country_id">
                    <el-option
                        v-for="item in provinces"
                        :key="`province-${item.id}`"
                        :label="item[getProvince]"
                        :value="item.id">
                        <span style="float: left" class="administration">{{ item[getProvince] }}</span>
                    </el-option>
                </el-select>
            </div>

```<script>
    import { mapGetters } from 'vuex';
    import City from '../../entities/City.js';
    import province from '../../api/province.js';
    import city from '../../api/city.js';

    export default {
        name: 'EditCity',

        data() {
            return {
                city: new City(),
                countries: [],
                provinces: [],
                errors: [],
                loading: false,
                provinces2: [
                    {id:1, provinceName_en: "Ontario"},
                    {id:2, provinceName_en: "Quebec"},
                    {id:3, provinceName_en: "Alberta"},
                    {id:4, provinceName_en: "Newfoundland"},
                    {id:5, provinceName_en: "Manitoba"},
                ]
            };
        },

        computed: {
            ...mapGetters([
                'getConfigs',
            ]),

            getCountry() {
                return `countryName_${this.$i18n.locale}`;
            },

            getProvince() {
                return `provinceName_${this.$i18n.locale}`;
            },

            disabled() {
                return this.countryNameRequired
                    || this.provinceNameRequired
                    || this.cityNameEnRequired
                    || this.cityNameFrRequired
                    || this.cityNameEsRequired;
            },


            countryNameRequired() {
                return !this.city.country_id;
            },

            provinceNameRequired() {
                return !this.city.province_id;
            },

            cityNameEnRequired() {
                return !this.city.cityName_en;
            },

            cityNameFrRequired() {
                return !this.city.cityName_fr;
            },

            cityNameEsRequired() {
                return !this.city.cityName_es;
            },
        },

        methods: {
            async fetchCity() {
                try {
                    this.city = await city.show(this.$route.params.id);

                    if (this.city.country_id) {
                        this.provinces = await province.listProvincePerCountry(this.city.country_id);
                        const provinceName = this.getProvince;
                        this.provinces.sort((a,b) => (a[provinceName] > b[provinceName]) ? 1: -1);
                    }

                } catch (error) {
                    if (!error.response)
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.contactSupport') + 'Code F0013',
                            duration: 0
                        });

                    if (error.response.status === 403) {
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.forbidden'),
                            duration: 0
                        });
                    }
                }
            },

            async onCountryChange(countryId) {
                this.city.province_id = null;
                this.provinces = await province.listProvincePerCountry(countryId);
                const provinceName = this.getProvince;
                this.provinces.sort((a,b) => (a[provinceName] > b[provinceName]) ? 1: -1);
            },

            async updateCity() {
                try {
                    this.loading = true;
                    await city.update(this.$route.params.id, this.city);
                    this.loading = false;
                    this.$notify.success({
                        title: this.$t('alert.success'),
                        message: this.$t('alert.successfullyUpdated'),
                    });
                    this.cancel();

                } catch (error) {
                    this.loading = false;
                    if (!error.response) {
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.contactSupport') + 'Code F0014',
                            duration: 0
                        });
                    }

                    if (error.response.status === 403) {
                        this.$notify.error({
                            title: this.$t('alert.error'),
                            message: this.$t('alert.forbidden'),
                            duration: 0
                        });
                    }

                    if (error.response.data.error) {
                        this.errors = [];
                        this.errors = Object.values(error.response.data.error.message);
                    }
                }
            },

            cancel() {
                this.$router.push({ name: 'city.index' });
            },

            translationKey(value) {
                return `validation.city.${value}`;
            },

            async init() {
                const countryName = this.getCountry;
                this.countries = this.getConfigs.countries.sort((a,b) => (a[countryName] > b[countryName]) ? 1: -1);

                await this.fetchCity();
            }
        },

        async mounted() {
            await this.init();
        }
    }
</script>
