### ISSUE TITLE
[Bug Report] ElPopover v-model:visible value not updating

### ISSUE THREAD

**Issue by natashatylee** [element-plus/element-plus#5771] opened 2022-02-03 02:01 UTC
### Element Plus version
1.3.0-beta.10

### OS/Browsers version
macOS Monterey

### Vue version
3.2.29

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-noeh2?file=/src/App.vue

### Steps to reproduce
Import the ElPopover component and use v-model:visible modifier with the initial visible value set to false.

### What is Expected?
On trigger, the visible value should update to true. 

### What is actually happening?
On trigger, the visible value does not update to true.

**Comment by emojiiii** [comment] 2022-02-03 02:31
Duplicate of #5424

**Closed** 2022-02-03 02:31 UTC
Labels: duplicate, Component：Popover
