### ISSUE TITLE
[Feature Request] [Enhancement] [table] 虚拟列表

### ISSUE THREAD

**Issue by hls-1992** [element-plus/element-plus#6483] opened 2022-03-08 08:55 UTC
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `table`

## Description

virtual-list已经应用于el-select-v2，有没有和el-table结合的计划呢

### Additional comments

_(empty)_

**Comment by sxzz** [comment] 2022-03-09 06:59
Duplicate of #3067

**Closed by sxzz** 2022-03-09 06:59 UTC
