### ISSUE TITLE
页头显示bug

### ISSUE THREAD

**Issue by ZLwangzhen** [element-plus/element-plus#737] opened 2020-12-01 02:24 UTC
![image](https://user-images.githubusercontent.com/67615285/100689403-5f906200-33bf-11eb-95fc-e1e8dade06f0.png)

**Comment by JeremyWuuuuu** [comment] 2020-12-01 03:14
This is not a bug from us, what you saw was an icon in `iconfont` format, this might be caused by incapable of loading iconfont resource.
Screenshots on my computer were attached. If you want to solve this problem, please provide your computer's platform and versions, also the browser that you are currently using to reproduce this bug.
FYI: I am using 
MacOS Big Sur version 11.0.1
with 
Brave browser in Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (x86_64)
I have also tested in Chrome Version 87.0.4280.67 (Official Build) (x86_64)
They all looked fine.
![image](https://user-images.githubusercontent.com/15975785/100692427-c7e24200-33c5-11eb-9862-834d43827bec.png)
![image](https://user-images.githubusercontent.com/15975785/100692442-cd3f8c80-33c5-11eb-9fe0-1a6ffcb11aad.png)
![image](https://user-images.githubusercontent.com/15975785/100692449-d3ce0400-33c5-11eb-8ef4-aa8962b517d6.png)
![image](https://user-images.githubusercontent.com/15975785/100692466-db8da880-33c5-11eb-9088-bb1171a81365.png)
![image](https://user-images.githubusercontent.com/15975785/100692480-e21c2000-33c5-11eb-96ce-c5ec5d31a5ef.png)

**Comment by JeremyWuuuuu** [comment] 2020-12-01 03:15
Please do clear your browser cache with hard reload, and try again.

**Comment by JeremyWuuuuu** [comment] 2020-12-01 13:24
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
This issue has nothing to do with `ElementPlus` website itself, it's caused by either the browser or the operation system.

**Closed by JeremyWuuuuu** 2020-12-01 13:24 UTC
Labels: wontfix
