### ISSUE TITLE
[Bug Report] Using the dynamic component reference date-picker,  the date panel is blank

### ISSUE THREAD

**Issue by cjq02** [element-plus/element-plus#5067] opened 2021-12-31 02:40 UTC
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Chrome 95.0.4638.54

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/cjq02/pen/MWEQMdJ

### Steps to reproduce
click el-date-picker input, then you can see an empty panel

### What is Expected?
Displays all the dates of the month

### What is actually happening?
the date panel is blank

![image](https://user-images.githubusercontent.com/16457309/147799913-7eeee1ec-e684-4a91-b5fe-79e8efa5d051.png)

**Comment by MssText** [comment] 2022-01-01 13:50
Has it been fixed in 1.0.1-alpha.10? This version can’t reproduce this problem, version 1.0.1-alpha.10 seems to work fine

**Comment by buqiyuan** [comment] 2022-01-06 09:52
The reason is probably that you used the default slot, but did not provide content

**Closed** 2022-01-08 11:41 UTC
Labels: bug, Component: DatePicker
