### ISSUE TITLE
[Feature Request] onPick callback for datepicker

### ISSUE THREAD

**Issue by YNWA** [element-plus/element-plus#2027] opened 2021-05-19 15:03 UTC
### Existing Component
Yes

### Component Name
ElDatePicker

### Description
Element UI supports `onPick` callback that triggers when the selected date is changed. 
https://element.eleme.io/#/en-US/component/date-picker#picker-options

Element Plus seems missing this feature. Would be nice to have it back. Is this possible?

**Comment by iamkun** [comment] 2021-08-09 07:19
Duplicate of #2627

**Closed by iamkun** 2021-08-09 07:19 UTC
