### ISSUE TITLE
[Component] [drawer, form-item] drawer中的表单点击label对应的input会获取到焦点，如点击label自动打开了select选项框

### ISSUE THREAD

**Issue by liumangafei** [element-plus/element-plus#14169] opened 2023-09-01 10:31 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-drawer`
- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGNvbHVtbk5hbWUgPSByZWYoJycpO1xuY29uc3QgY29sdW1uVHlwZSA9IHJlZignJyk7XG5jb25zdCBjb2x1bW5UeXBlRW51bSA9IHJlZihbXG57XG4gIHZhbHVlOiAnMScsXG59LHtcbiAgdmFsdWU6ICcyJyxcbn1cbl0pO1xuXG5jb25zdCBkcmF3ZXIgPSByZWYoZmFsc2UpXG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBzdHlsZT1cIm1hcmdpbi1sZWZ0OiAxNnB4XCIgQGNsaWNrPVwiZHJhd2VyID0gdHJ1ZVwiPlxuICAgIG9wZW5cbiAgPC9lbC1idXR0b24+XG5cbiAgPGVsLWRyYXdlciB2LW1vZGVsPVwiZHJhd2VyXCIgdGl0bGU9XCJJJ20gb3V0ZXIgRHJhd2VyXCIgc2l6ZT1cIjUwJVwiPlxuICAgIDxkaXY+XG4gICAgICA8cD7ngrnlh7tsYWJlbOS/oeaBrywgaW5wdXToh6rliqjojrflj5bnhKbngrksIHNlbGVjdOiHquWKqOaJk+W8gOmAiemhuTwvcD5cbiAgICAgIDxlbC1mb3JtXG4gICAgICAgIHJlZj1cInRhYmxlQ29sdW1uc0Zvcm1SZWZcIlxuICAgICAgICBsYWJlbC13aWR0aD1cIjEwMHB4XCJcbiAgICAgICAgbGFiZWwtc3VmZml4PVwiIDpcIlxuICAgICAgICA6aW5saW5lPVwidHJ1ZVwiXG4gICAgICA+XG4gICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCLlrZfmrrXlkI3np7BcIj5cbiAgICAgICAgICA8ZWwtaW5wdXRcbiAgICAgICAgICAgIHYtbW9kZWw9XCJjb2x1bW5OYW1lXCJcbiAgICAgICAgICAgIHBsYWNlaG9sZGVyPVwi6K+35aGr5YaZ5a2X5q615ZCN56ewXCJcbiAgICAgICAgICAgIGNsZWFyYWJsZVxuICAgICAgICAgID48L2VsLWlucHV0PlxuICAgICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuWtl+auteexu+Wei1wiPlxuICAgICAgICAgIDxlbC1zZWxlY3RcbiAgICAgICAgICAgIHYtbW9kZWw9XCJjb2x1bW5UeXBlXCJcbiAgICAgICAgICAgIHBsYWNlaG9sZGVyPVwi6K+36YCJ5oup5a2X5q6157G75Z6LXCJcbiAgICAgICAgICAgIGZpbHRlcmFibGVcbiAgICAgICAgICAgIGFsbG93LWNyZWF0ZVxuICAgICAgICAgICAgZGVmYXVsdC1maXJzdC1vcHRpb25cbiAgICAgICAgICAgIGNsZWFyYWJsZVxuICAgICAgICAgID5cbiAgICAgICAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIGNvbHVtblR5cGVFbnVtXCIgOmtleT1cIml0ZW0udmFsdWVcIiA6bGFiZWw9XCJpdGVtLnZhbHVlXCIgOnZhbHVlPVwiaXRlbS52YWx1ZVwiIC8+XG4gICAgICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgPC9lbC1mb3JtPlxuICAgIDwvZGl2PlxuICA8L2VsLWRyYXdlcj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1、点击open按钮，弹出Drawer层
2.1、点击label：字段名称，复现出input框获取焦点
2.2、点击label：字段类型，复现出select下拉框自动打开

### What is Expected?

1、点击label：字段名称，input框不获取焦点
2、点击label：字段类型，select下拉框不自动打开

### What is actually happening?

1、点击label：字段名称，input框获取焦点
2、点击label：字段类型，select拉框不自动打开

### Additional comments

_(empty)_

**Comment by btea** [comment] 2023-09-04 02:10
Duplicate of #9752

**Closed** 2023-09-04 02:10 UTC
