### ISSUE TITLE
[Component] [image] el-image在预览状态下点击遮罩层无法关闭

### ISSUE THREAD

**Issue by didoee** [element-plus/element-plus#10554] opened 2022-11-10 07:04 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.20`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35`
- Build Tool: `Vite`

### Related Component

- `el-image`

### Reproduction Link

[Github Repo](https://github.com/didoee/vue-project)

### Steps to reproduce

```
<el-image
		style="width: 30px; height: 30px"
		:src="'http://localhost:3000/s-vtEHOrokQ18LYVS8GWR.svg'"
		:preview-src-list="['http://localhost:3000/s-vtEHOrokQ18LYVS8GWR.svg']"
		:initial-index="0"
		:hide-on-click-modal="true"
	/>
```

### What is Expected?

el-image在预览状态下点击遮罩层能够关闭

### What is actually happening?

el-image在预览状态下点击遮罩层无法关闭

### Additional comments

_(empty)_

**Comment by Simon-He95** [comment] 2022-11-10 07:37
Does this image exist? `http://localhost:3000/s-vtEHOrokQ18LYVS8GWR.svg`

**Comment by ryuhangyeong** [comment] 2022-11-10 11:28
Is the example below correct what you are looking for?

[Elment Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1pbWFnZV9fcHJldmlld1wiPlxuICAgIDxlbC1pbWFnZVxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwcHg7IGhlaWdodDogMTAwcHhcIlxuICAgICAgOnNyYz1cInVybFwiXG4gICAgICA6cHJldmlldy1zcmMtbGlzdD1cInNyY0xpc3RcIlxuICAgICAgOmluaXRpYWwtaW5kZXg9XCI0XCJcbiAgICAgIGZpdD1cImNvdmVyXCJcbiAgICAgIDpoaWRlLW9uLWNsaWNrLW1vZGFsPVwidHJ1ZVwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3QgdXJsID1cbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnJ1xuY29uc3Qgc3JjTGlzdCA9IFtcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8xLzM0LzE5YWE5OGIxZmNiMjc4MWM0ZmJhMzNkODUwNTQ5anBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8wLzZmL2UzNWZmMzc1ODEyZTZiMDAyMGI2YjRlOGY5NTgzanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS85L2JiL2UyNzg1OGU5NzNmNWQ3ZDM5MDQ4MzVmNDZhYmJkanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9kL2U2L2M0ZDkzYTM4MDViM2NlM2YzMjNmNzk3NGU2Zjc4anBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8zLzI4L2JiZjg5M2Y3OTJmMDNhNTQ0MDhiM2I3YTdlYmYwanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8yLzExLzY1MzViY2ZiMjZlNGM3OWI0OGRkZGU0NGY0YjZmanBlZy5qcGVnJyxcbl1cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmRlbW8taW1hZ2VfX2Vycm9yIC5pbWFnZS1zbG90IHtcbiAgZm9udC1zaXplOiAzMHB4O1xufVxuLmRlbW8taW1hZ2VfX2Vycm9yIC5pbWFnZS1zbG90IC5lbC1pY29uIHtcbiAgZm9udC1zaXplOiAzMHB4O1xufVxuLmRlbW8taW1hZ2VfX2Vycm9yIC5lbC1pbWFnZSB7XG4gIHdpZHRoOiAxMDAlO1xuICBoZWlnaHQ6IDIwMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by didoee** [comment] 2022-11-10 12:51
已经更新image链接，全屏预览状态 点击遮罩层无法关闭，不是找例子，是bug

**Comment by didoee** [comment] 2022-11-10 12:52
> 下面的示例是否正确？
> 
> [埃尔门特普拉斯游乐场](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1pbWFnZV9fcHJldmlld1wiPlxuICAgIDxlbC1pbWFnZVxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwcHg7IGhlaWdodDogMTAwcHhcIlxuICAgICAgOnNyYz1cInVybFwiXG4gICAgICA6cHJldmlldy1zcmMtbGlzdD1cInNyY0xpc3RcIlxuICAgICAgOmluaXRpYWwtaW5kZXg9XCI0XCJcbiAgICAgIGZpdD1cImNvdmVyXCJcbiAgICAgIDpoaWRlLW9uLWNsaWNrLW1vZGFsPVwidHJ1ZVwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3QgdXJsID1cbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnJ1xuY29uc3Qgc3JjTGlzdCA9IFtcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8xLzM0LzE5YWE5OGIxZmNiMjc4MWM0ZmJhMzNkODUwNTQ5anBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8wLzZmL2UzNWZmMzc1ODEyZTZiMDAyMGI2YjRlOGY5NTgzanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS85L2JiL2UyNzg1OGU5NzNmNWQ3ZDM5MDQ4MzVmNDZhYmJkanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9kL2U2L2M0ZDkzYTM4MDViM2NlM2YzMjNmNzk3NGU2Zjc4anBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8zLzI4L2JiZjg5M2Y3OTJmMDNhNTQ0MDhiM2I3YTdlYmYwanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8yLzExLzY1MzViY2ZiMjZlNGM3OWI0OGRkZGU0NGY0YjZmanBlZy5qcGVnJyxcbl1cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmRlbW8taW1hZ2VfX2Vycm9yIC5pbWFnZS1zbG90IHtcbiAgZm9udC1zaXplOiAzMHB4O1xufVxuLmRlbW8taW1hZ2VfX2Vycm9yIC5pbWFnZS1zbG90IC5lbC1pY29uIHtcbiAgZm9udC1zaXplOiAzMHB4O1xufVxuLmRlbW8taW1hZ2VfX2Vycm9yIC5lbC1pbWFnZSB7XG4gIHdpZHRoOiAxMDAlO1xuICBoZWlnaHQ6IDIwMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

不是找案例，谢谢

**Comment by didoee** [comment] 2022-11-10 12:52
> 这个图像存在吗？`http://localhost:3000/s-vtEHOrokQ18LYVS8GWR.svg`

已经更新image链接，全屏预览状态 点击遮罩层无法关闭

**Comment by Simon-He95** [comment] 2022-11-10 13:54
I think it maybe has been fixed in dev, I can't reproduce this problem.

**Comment by holazz** [comment] 2022-11-10 13:56
Maybe it's caused by here
https://github.com/didoee/vue-project/blob/5cfeb53f86f1ad42fd1edf08a267044543d2cbbf/src/assets/base.css#L58

**Comment by Simon-He95** [comment] 2022-11-10 13:59
> Maybe it's caused by here https://github.com/didoee/vue-project/blob/5cfeb53f86f1ad42fd1edf08a267044543d2cbbf/src/assets/base.css#L58

 I can't reproduce this problem. Can you reproduce it?

**Comment by didoee** [comment] 2022-11-10 16:02
你启动项目没办法重现这个问题吗





Maybe it's caused by here https://github.com/didoee/vue-project/blob/5cfeb53f86f1ad42fd1edf08a267044543d2cbbf/src/assets/base.css#L58

I can't reproduce this problem. Can you reproduce it?

**Comment by holazz** [comment] 2022-11-11 02:48
> > Maybe it's caused by here [didoee/vue-project@`5cfeb53`/src/assets/base.css#L58](https://github.com/didoee/vue-project/blob/5cfeb53f86f1ad42fd1edf08a267044543d2cbbf/src/assets/base.css#L58)
> 
> I can't reproduce this problem. Can you reproduce it?

consider this [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1pbWFnZV9fcHJldmlld1wiPlxuICAgIDxlbC1pbWFnZVxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwcHg7IGhlaWdodDogMTAwcHhcIlxuICAgICAgOnNyYz1cInVybFwiXG4gICAgICA6cHJldmlldy1zcmMtbGlzdD1cInNyY0xpc3RcIlxuICAgICAgOmluaXRpYWwtaW5kZXg9XCI0XCJcbiAgICAgIGZpdD1cImNvdmVyXCJcbiAgICAgIDpoaWRlLW9uLWNsaWNrLW1vZGFsPVwidHJ1ZVwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3QgdXJsID1cbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnJ1xuY29uc3Qgc3JjTGlzdCA9IFtcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8xLzM0LzE5YWE5OGIxZmNiMjc4MWM0ZmJhMzNkODUwNTQ5anBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8wLzZmL2UzNWZmMzc1ODEyZTZiMDAyMGI2YjRlOGY5NTgzanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS85L2JiL2UyNzg1OGU5NzNmNWQ3ZDM5MDQ4MzVmNDZhYmJkanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9kL2U2L2M0ZDkzYTM4MDViM2NlM2YzMjNmNzk3NGU2Zjc4anBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8zLzI4L2JiZjg5M2Y3OTJmMDNhNTQ0MDhiM2I3YTdlYmYwanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8yLzExLzY1MzViY2ZiMjZlNGM3OWI0OGRkZGU0NGY0YjZmanBlZy5qcGVnJyxcbl1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4qIHtcbiAgcG9zaXRpb246IHJlbGF0aXZlO1xufVxuXG4uZGVtby1pbWFnZV9fZXJyb3IgLmltYWdlLXNsb3Qge1xuICBmb250LXNpemU6IDMwcHg7XG59XG4uZGVtby1pbWFnZV9fZXJyb3IgLmltYWdlLXNsb3QgLmVsLWljb24ge1xuICBmb250LXNpemU6IDMwcHg7XG59XG4uZGVtby1pbWFnZV9fZXJyb3IgLmVsLWltYWdlIHtcbiAgd2lkdGg6IDEwMCU7XG4gIGhlaWdodDogMjAwcHg7XG59XG48L3N0eWxlPiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by didoee** [comment] 2022-11-11 03:23
> > Maybe it's caused by here https://github.com/didoee/vue-project/blob/5cfeb53f86f1ad42fd1edf08a267044543d2cbbf/src/assets/base.css#L58
> 
> I can't reproduce this problem. Can you reproduce it?
https://github.com/didoee/vue-project

**Closed** 2022-11-11 05:08 UTC
