### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by Brooooooklyn** [element-plus/element-plus#266] opened 2020-09-07 03:20 UTC
https://app.dependabot.com/

Since I have added [dependabot.yml](https://github.com/element-plus/element-plus/blob/dev/.github/dependabot.yml) and [dependabot auto merge](https://github.com/element-plus/element-plus/blob/dev/.github/workflows/yarn.js.yml#L20) job, we can get the benefit of dependabot to auto update dependencies in this project. When testing passed, it will be merged automatically.

**Comment by JeremyWuuuuu** [comment] 2020-09-07 14:06
Thanks @Brooooooklyn , I have just enabled `dependabot` for `ElementPlus`, dunno if the settings are correct. I'll catch you up once I get updated

**Comment by JeremyWuuuuu** [comment] 2020-09-07 14:07
Seems everything is working fine. #269 so I'm closing this issue, thanks again!

**Closed by JeremyWuuuuu** 2020-09-07 14:07 UTC

**Comment by zazzaz** [comment] 2020-09-10 06:04
@Brooooooklyn 

Hi, this project is still under heavy development and updates daily. 

As we could see not all the packages have flowed semantic versioning,  and we have some unexpected behavior with the new (even patch) version installed and have to force a downgrade to the previous one. 

So it might be better to manage the dependencies ourselves manually to get better control during development.

**Comment by Brooooooklyn** [comment] 2020-09-10 06:27
> As we could see not all the packages have flowed semantic versioning, and we have some unexpected behavior with the new (even patch) version installed and have to force a downgrade to the previous one.

This is true but
IMO keep the dependencies fresh is a better way to keep a project health.
You can choose the old traditional way: `manage the dependencies ourselves manually to get better control during development`. But the problem is, `some unexpected behavior with the new (even patch) version` will not disappear whether you upgrade daily or monthly. One day sooner or later, you must fix them. And fix it early can prevent the `unexpected behavior` to be contagious to the whole project.

And of course, it's just an advice that ***keep project refresh via dependabot***. Feel free to remove it if you felt the **unexpected behavior in third part libraries** is too often and too bother.

**Comment by zazzaz** [comment] 2020-09-10 08:16
Thanks for the reply.

It is true that `keep the dependencies fresh is a better way to keep project health`. And we cloud re-enable it later after the project is released.

At this time, we are focusing on the full migration process and will lock the dependencies, and we may not have time dealing with unexpected bugs caused by dependencies upgrade.
