### ISSUE TITLE
[Help] picker.$emit is not a function

### ISSUE THREAD

**Issue by vadimt2** [element-plus/element-plus#1755] opened 2021-04-05 12:10 UTC
Hi, I have moved from vue 2 to vue 3
```
https://element-plus.org/#/en-US/component/date-picker
```

This is my code:
```
shortcuts: [
          {
            text: (this as any).$l("Today"),
            value: new Date(),
          },
          {
            text: (this as any).$l("LastInputDate"),
            onClick: (picker) => {
                let lastDate = GanttDataAnalizer.getLastInputDate();
                if (!lastDate)
                    lastDate = (this as any).$data.lastScheduleDate;
                picker.$emit('pick', DateHelper.getDateWithoutTime(lastDate as Date));
            },
          },
        ],
```

error:
```
Uncaught TypeError: picker.$emit is not a function
    at Proxy.onClick (webpack-internal:///./src/components/gantt-tab/gantt-tab.ts:69)
    at Proxy.handleShortcutClick (webpack-internal:///./node_modules/element-plus/lib/index.esm.js:128)
    at onClick (webpack-internal:///./node_modules/element-plus/lib/index.esm.js:128)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:276)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:285)
    at HTMLButtonElement.invoker (webpack-internal:///./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js:521)
```

How can i fix this error ?
* this code use to work on vue 2

**Comment by JeremyWuuuuu** [comment] 2021-04-06 08:14
Well, since we do not expose the `picker` instance to our users based on the change:
refer to: [Events API](https://v3.vuejs.org/guide/migration/events-api.html#_3-x-update). The detail should be explained by @zazzaz

**Comment by JeremyWuuuuu** [comment] 2021-04-06 08:46
I have read the source code, seems that we still exposed the `onClick` API but not on the documentation, you can follow the code below to fix your issue I suppose.
https://element-plus.org/#/en-US/component/date-picker#date-range.
BTW, you need to emit `Dayjs Object` since we have migrated to [Dayjs](https://day.js.org/)
```js
{
  // ... rest 
  shortcuts: [{
          text: 'Last week',
          // You only need to modify it here, by invoking a function immediately or you invoke it to conclude the result before this instance is instantiated, 
          onClick(ctx) { // ctx is essentially vue3 setup context, see the link below.
             ctx.emit('pick', dateObjects);
           }
        }],
}
```
FYI:
[Setup Context](https://v3.vuejs.org/guide/composition-api-setup.html#context)

Also the source code:
```js
handleShortcutClick() {
  if (shortcut.value) {
    emit(dayjs(shortcut.value))
    return
  }
  if (shortcut.onClick) {
   shortcut.onClick(ctx)
  }
}
```

**Comment by JeremyWuuuuu** [comment] 2021-04-06 08:47
Please let me know if you have further issue when you applied my solution, ping me here.

**Comment by 0song** [comment] 2021-04-06 08:47
First of all, we have updated this API to `{ text, value}`, you can check it via https://element-plus.org/#/en-US/component/date-picker.

If you still want to use the old syntax which is not recommended, you can check #1367

**Comment by vadimt2** [comment] 2021-04-06 14:18
I'm using optional API.
```
            text: (this as any).$l("LastInputDate"),
            onClick: (picker) => {
                picker.emit('pick', new Date());
            },
```

After using this code below i have this error:
And it's still not working.
```
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Unhandled error during execution of component event handler 
  at <PanelDatePick visible=true actualVisible=true parsedValue= d  ... > 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> onBeforeEnter=fn<onBeforeEnter>  ... > 
  at <Transition name="el-zoom-in-top" onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave>  ... > 
  at <ElPopper ref="refPopper" visible=true onUpdate:visible=fn  ... > 
  at <Picker format="DD/MM/YYYY" clearable=false modelValue= Tue Apr 06 2021 00:00:00 GMT+0300 (Moscow Standard Time)  ... > 
  at <ElDatePicker clearable=false modelValue= Tue Apr 06 2021 00:00:00 GMT+0300 (Moscow Standard Time) onUpdate:modelValue=fn  ... > 
  at <ElCol span=12 > 
  at <ElRow style= Object > 
  at <ElRow element-loading-text="Загрузка..." > 
  at <GanttTab ref="ganttComponent" onFindLinkedObject=fn<bound findLinkedObject> onScheduleChanged=fn<bound onScheduleChanged>  ... > 
  at <ElTabPane> 
  at <ElTabs type="border-card" class="topPanelTabs" ref="topPanelTabs" > 
  at <ElRow class="project-container" element-loading-text="::ProjectChangingPleaseWait::..." id="34" > 
  at <Project id="34" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy > > 
  at <RouterView> 
  at <ElMain> 
  at <Main onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy > > 
  at <RouterView> 
  at <App>
```
When i use **value** My date is undefined, and it's not working because i'm getting the data from an API call.
It does work only with: **value: new Date()**,
But it doen't work in my case :(

**Comment by JeremyWuuuuu** [comment] 2021-04-06 16:19
You need to return `dayjs` object, instead of plain date object, that is the main reason behind hiding this API to our users. 
do something like this:

```js
import dayjs from 'dayjs';
{
   onClick: (picker) => {
       picker.emit('pick', dayjs());
   }
}
```
Then you will get correct behavior.
For more info https://github.com/element-plus/element-plus/issues/1367#issuecomment-768160839

**Comment by JeremyWuuuuu** [comment] 2021-04-06 16:20
NOTE THIS: **The value you returned from onClick should be a dayjs object**, this is important, we do want to hide `dayjs` from our users, but if you do need this, you will need to do the conversion yourself, maybe we can do something with this, for your quick solution, use the code I wrote above.

**Comment by JeremyWuuuuu** [comment] 2021-04-07 02:22
If you solved your issue, please let me know.

**Comment by vadimt2** [comment] 2021-04-07 06:37
Yes, Thank you very much :), I got it, Thank you for your help)

**Comment by JeremyWuuuuu** [comment] 2021-04-07 07:54
Since the issue is solved, I will close this issue, feel free to reopen it.

**Closed by JeremyWuuuuu** 2021-04-07 07:54 UTC
Labels: enhancement
