### ISSUE TITLE
[Bug Report] When I use Form rules, the console prompts Vue Warning and the verification work error

### ISSUE THREAD

**Issue by chuan920826** [element-plus/element-plus#1196] opened 2021-01-05 03:49 UTC
### Element Plus version
1.0.1-beta.20

### OS/Browsers version
windows 10/Microsoft Edge  87.0.664.66

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/chuan920826/pen/yLajVpy
```
<template>
  <el-form v-model="user" :rules="formRule" ref="form">
    <el-form-item label="name" prop="name">
      <el-input v-model="user.Name" :disabled="type === 0"></el-input>
    </el-form-item>
  </el-form>
</template>

<script>
// import HelloWorldVue from "./components/HelloWorld.vue";
import { ref, defineComponent, reactive } from "vue";

export default defineComponent({
  name: "App",

  setup() {
    let user = ref({ Name: "" });
    let formRule = reactive({
      name: [
        { required: true, message: "input words,please", trigger: "blur" },
      ],
    });
    return { user, formRule };
  },
});
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

````

### Steps to reproduce
1、write words and let input loses focus
2、let input loses focus not write any words

### What is Expected?
No prompt and when the input has value no return message

### What is actually happening?
1、When the input loses focus, there will be a return message, regardless of whether the input has a value.
2、The console will prompt： [Vue warn]: Component emitted event "validate" but it is neither declared in the emits option nor as an "onValidate" prop. And  async-validator: ["name is required"]
3、I changed write and used

```
<template>
  <el-form v-model="user" :rules="formRule" ref="form">
    <el-form-item label="name" prop="name">
      <el-input v-model="user.Name" :disabled="type === 0"></el-input>
    </el-form-item>
  </el-form>
</template>

<script>
// import HelloWorldVue from "./components/HelloWorld.vue";
import { ref, defineComponent, reactive } from "vue";

export default defineComponent({
  name: "App",

  setup() {
    let user = ref({ Name: "" });
    return { user};
  },
   data(){
   return {
     formRule:{
      name: [
        { required: true, message: "input words,please", trigger: "blur" },
      ],
    }
   }
}
});
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>


```

,but didn't work;

So what should i do?

**Comment by JeremyWuuuuu** [comment] 2021-01-05 06:48
![Uploading image.png…]()
 Check this out.

**Comment by JeremyWuuuuu** [comment] 2021-01-05 06:50
For more detailed info, please refer to doc site [Validation](http://localhost:8080/#/en-US/component/form#validation)
Closing since this is not a bug, feel free to reopen.

**Closed by JeremyWuuuuu** 2021-01-05 06:50 UTC

**Comment by chuan920826** [comment] 2021-01-05 07:03
> For more detailed info, please refer to doc site [Validation](http://localhost:8080/#/en-US/component/form#validation)
> Closing since this is not a bug, feel free to reopen.

Thanks,according to your guidance, I have solved the problem. 
I always think that :model and :rules use two unrelated data. Thanks for pointing out my mistake

**Comment by JeremyWuuuuu** [comment] 2021-01-05 07:05
> > For more detailed info, please refer to doc site [Validation](http://localhost:8080/#/en-US/component/form#validation)
> > Closing since this is not a bug, feel free to reopen.
> 
> Thanks,according to your guidance, I have solved the problem.
> I always think that :model and :rules use two unrelated data. Thanks for pointing out my mistake

Maybe the API itself is just confusing, we should mention that on the documentation though.

**Comment by chuan920826** [comment] 2021-01-05 07:09
> > > For more detailed info, please refer to doc site [Validation](http://localhost:8080/#/en-US/component/form#validation)
> > > Closing since this is not a bug, feel free to reopen.
> > 
> > 
> > Thanks,according to your guidance, I have solved the problem.
> > I always think that :model and :rules use two unrelated data. Thanks for pointing out my mistake
> 
> Maybe the API itself is just confusing, we should mention that on the documentation though.

I read the document carefully again, you did mention it, I ignored it before

**Comment by JeremyWuuuuu** [comment] 2021-01-05 07:10
Yes, so I said that we SHOULD'VE MENTIONED that on doc site. We will add a tip section for that later.

**Comment by chuan920826** [comment] 2021-01-05 07:16
> Yes, so I said that we SHOULD'VE MENTIONED that on doc site. We will add a tip section for that later.

that's great
