### ISSUE TITLE
[Component] [input] ElForm在设置inline属性时且ElInput设置clearable=true时的宽度不是固定的

### ISSUE THREAD

**Issue by GuoJikun** [element-plus/element-plus#11370] opened 2023-01-31 08:05 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54`
- Build Tool: `Vue CLI`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5jb25zdCBmb3JtSXRlbSA9IHJlYWN0aXZlKHtcbiAgbmFtZTogJzEyMycsXG4gIGFnZTogXCIxMlwiXG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gOm1vZGVsPVwiZm9ybUl0ZW1cIiBpbmxpbmU+XG4gIFx0PGVsLWZvcm0taXRlbSBsYWJlbD1cIuWQjeensFwiPlxuICAgIFx0PGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtSXRlbS5uYW1lXCIgY2xlYXJhYmxlIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、给el-input设置clearable=true属性
2、给el-form设置inline属性
3、input框中输入内容
4、input组件获取焦点和失去焦点时的宽度不相等

### What is Expected?

input的宽度不变

### What is actually happening?

input的宽度不一致

**Comment by acyza** [comment] 2023-02-07 04:31
可以给他定个宽度。[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5jb25zdCBmb3JtSXRlbSA9IHJlYWN0aXZlKHtcbiAgbmFtZTogJzEyMycsXG4gIGFnZTogXCIxMlwiXG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gOm1vZGVsPVwiZm9ybUl0ZW1cIiBpbmxpbmU+XG4gIFx0PGVsLWZvcm0taXRlbSBsYWJlbD1cIuWQjeensFwiPlxuICAgIFx0PGVsLWlucHV0IHN0eWxlPVwid2lkdGg6MjAwcHhcIiB2LW1vZGVsPVwiZm9ybUl0ZW0ubmFtZVwiIGNsZWFyYWJsZSAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by tolking** [comment] 2023-02-07 07:57
Duplicate of #7287

**Closed by tolking** 2023-02-07 07:57 UTC
