### ISSUE TITLE
[Bug Report]: NavMenu bug

### ISSUE THREAD

**Issue by hsiangleev** [element-plus/element-plus#702] opened 2020-11-26 08:15 UTC
我在使用NavMenu组件配合vue-router的时候，发现使用vue-router在页面跳转的时候，如果跳转的页面的导航条没有打开，会报错，如果跳转的页面的导航条打开了，就不报错了
![https://hsiangleev.github.io/tool/test/images/1.png](https://hsiangleev.github.io/tool/test/images/1.png)

**Comment by JeremyWuuuuu** [comment] 2020-11-26 08:19
Could you specify this **BUG 🐛** with a minimal reproducible code or link? I think I already know what you said. But with a demo would be better for us to locate the bug. Thanks.
With reproducible steps would be better. A sample just for your reference:

----
### Reproducible Steps:

1. do something
2. do something.
3. then observe...

**Comment by hsiangleev** [comment] 2020-11-26 08:59
@JeremyWuuuuu Sorry, I re-created a project, only introduced element-plus and vue-router, and found that no errors were reported. I am not sure if it is the element-plus problem, let me check again

**Comment by mexumeng** [comment] 2020-11-26 09:28
English English English...

**Comment by hsiangleev** [comment] 2020-11-27 01:55
@JeremyWuuuuu 
I reproduced this error. It was a problem with this attribute ":unique-opened='true'". I removed this attribute and no error was reported.
You can see the effect at the address below, click "跳转" and an error will be reported
[https://codesandbox.io/s/trusting-wood-4b5vx?file=/index.html](https://codesandbox.io/s/trusting-wood-4b5vx?file=/index.html)

**Comment by JeremyWuuuuu** [comment] 2020-11-27 02:07
@hsiangleev Thanks for providing this information, I am going to take a look at the root cause of the bug.

**Comment by JeremyWuuuuu** [comment] 2020-12-01 03:56
This could be duplicated with #734

**Comment by JeremyWuuuuu** [comment] 2020-12-01 13:25
Fixed in #745

**Closed by JeremyWuuuuu** 2020-12-01 13:25 UTC
