### ISSUE TITLE
[Component] [table, table-v2] el-table height设置为calc()时的问题

### ISSUE THREAD

**Issue by zc-write-code** [element-plus/element-plus#17329] opened 2024-06-26 06:11 UTC
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIGJvcmRlciA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIiBoZWlnaHQ9XCJjYWxjKDEwMCUgLSAzMnB4KVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQgcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE1MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJzdGF0ZVwiIGxhYmVsPVwiU3RhdGVcIiB3aWR0aD1cIjEyMFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiY2l0eVwiIGxhYmVsPVwiQ2l0eVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgd2lkdGg9XCI2MDBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInppcFwiIGxhYmVsPVwiWmlwXCIgd2lkdGg9XCIxMjBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQ9XCJyaWdodFwiIGxhYmVsPVwiT3BlcmF0aW9uc1wiIG1pbi13aWR0aD1cIjEyMFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLWJ1dHRvblxuICAgICAgICAgIGxpbmtcbiAgICAgICAgICB0eXBlPVwicHJpbWFyeVwiXG4gICAgICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICAgICAgICBAY2xpY2sucHJldmVudD1cImRlbGV0ZVJvdyhzY29wZS4kaW5kZXgpXCJcbiAgICAgICAgPlxuICAgICAgICAgIFJlbW92ZVxuICAgICAgICA8L2VsLWJ1dHRvbj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwib25BZGRJdGVtXCI+XG4gICAgQWRkIEl0ZW1cbiAgPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IGRheWpzIGZyb20gJ2RheWpzJ1xuXG5jb25zdCBub3cgPSBuZXcgRGF0ZSgpXG5cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gIH0sXG5dKVxuXG5jb25zdCBkZWxldGVSb3cgPSAoaW5kZXg6IG51bWJlcikgPT4ge1xuICB0YWJsZURhdGEudmFsdWUuc3BsaWNlKGluZGV4LCAxKVxufVxuXG5jb25zdCBvbkFkZEl0ZW0gPSAoKSA9PiB7XG4gIG5vdy5zZXREYXRlKG5vdy5nZXREYXRlKCkgKyAxKVxuICB0YWJsZURhdGEudmFsdWUucHVzaCh7XG4gICAgZGF0ZTogbm93KycnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gIH0pXG59XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuI2FwcHtcbmhlaWdodDogMzAwcHg7XG5iYWNrZ3JvdW5kLWNvbG9yOiAjMDBmO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImRheWpzXCI6IFwiZGF5anNcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

如链接中的实例,,当height设置了calc(100% - 32px), el-table__inner-wrapper 这个节点上的style中height同样设置了相同的height导致了里面的wrapper在基础上再次减了32px,table设置了border后会出现一个留白部分,具体可以看复现,需要自己使用css设置el-table__inner-wrapper的height为100%!important才可以,希望能优化一下

### What is Expected?

el-table__inner-wrapper的高度跟随父节点table的高度100%,而不是再次设置同一个table的props的height

### What is actually happening?

el-table__inner-wrapper的高度跟是table的props的height..导致了使用计算方法时需要自己在css去设置

### Additional comments

_(empty)_

**Comment by btea** [comment] 2024-06-26 06:32
Duplicate of #16052

**Closed** 2024-06-26 06:32 UTC
