### ISSUE TITLE
[Bug Report] 全局设置语言locale和size失效

### ISSUE THREAD

**Issue by zycoJamie** [element-plus/element-plus#5084] opened 2021-12-31 07:27 UTC
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
chrome 96.0.4664.110

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/sleepy-swartz-yin7z?file=/src/main.js

### Steps to reproduce
createApp(App).use(ElementPlus, { locale, size: "large" }).mount("#app");
全局配置无效

### What is Expected?
全局配置可用

### What is actually happening?
全局配置无效

**Comment by emojiiii** [comment] 2021-12-31 07:49
Please use `config-provider` temporarily

**Comment by emojiiii** [comment] 2021-12-31 07:49
Duplicate of #5078

**Closed** 2021-12-31 07:49 UTC
Labels: duplicate, investigating
