### ISSUE TITLE
el-tabs lazy loading

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#926] opened 2020-12-09 11:24 UTC
当我有很多个tab需要切换的时候
初次加载的时候 content的内容都加载出来了 发送了很多不必要的请求
是否有什么好的解决办法

我觉得理想情况下是第一次显示页签的时候，页签里面的组件才会执行初始化操作，请求数据，渲染dom  
初次最好不要加载这么多的  
我记得antd好像初次不会将内容全部加载出来

**Comment by JeremyWuuuuu** [comment] 2020-12-09 11:54
cc @bastarder

**Comment by JeremyWuuuuu** [comment] 2020-12-09 11:54
I think the lazy loading feature is legit. Let's see if we can get this done.

**Comment by bastarder** [comment] 2020-12-10 03:00
`el-tab-pane` support `lazy` prop, did you try it? or it doesn't work?

**Comment by Lliuxs** [comment] 2020-12-11 09:43
@bastarder 大佬 我觉得应该是可以的吧 之前用antd的时候是支持lazy的。理论上把状态给parent去处理是不是可以满足

**Comment by JeremyWuuuuu** [comment] 2020-12-18 05:43
Could you give some demo in order to get the investigation started? If this is really confirmed as an issue, then it will need to be fixed.

**Comment by bastarder** [comment] 2020-12-21 05:21
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Closed by bastarder** 2020-12-21 05:21 UTC
